#!/usr/bin/env python3
"""gen_ndf_wrapper.py — PRINT the NDF top module. R8 item (4).

    python3 docs/hdl-tools/gen_ndf_wrapper.py > SaltWorks/Silicon/RTL/tt_um_saltworks_ndf.v

PRINTS, NEVER WRITES — the .v lives in silicon's slot.

⚠️ PROVENANCE, because the composed top module is the one file that becomes the DIE:
this generator is PURE PYTHON — no Lean, no fleet lock, no PDK — so the .v is
REPRODUCIBLE ON DEMAND from tracked bytes. Evidence verified that at 01:40 by
regenerating and diffing byte-identically, which also proves NO HAND-EDIT: the
file on disk is exactly what this script emits and nobody touched it after.
⇒ If the emitted .v is NOT committed, that is a deliberate generated-on-demand
  posture and this line is the record of it. Regenerate with the command above
  before any flow run rather than trusting a file that a `git clean -fd` can
  remove. (The ORGANS it instantiates are tracked separately by silicon.)

WHY A GENERATOR AND NOT A HAND-EDIT: emitSeq emits SCALAR ports (o0..o31), so the
composition needs 4 cells x 32 + 3 SERs x 32 = 224 scalar connections. Hand-wiring
those is the defect class this fleet has paid for twice (instOK certified the wrong
wire; a bound was placed at an occupied net). Generated, they are regenerable and
diffable; typed, they are a lottery.

⛔ THIS FILE IS HAND RTL BY RULING, NOT KERNEL EMISSION — D2(b)'s named exemption
list: the tt_um_ pin wrapper, the sequencer FSM, and the fabric. The CELLS and the
SER organ inside it ARE kernel-emitted (emitSeqShell / emitSeqMux). Any sentence
about this module must say which layer it means.

SPEC SOURCES (all frozen): pin map v1.1 D6 (Captain-confirmed, R5) · frame sync
D4(h) · the 2-2-1 timetable in docs/ndf-council-example-221.md · shell ports R6.

DERIVED FROM THE MAESTRO'S 01:2x DRAFT (docs/drafts/), adopted under the
author-anywhere / land-at-owner rule. Corrections made at adoption, all four
measured against the emitted artifacts rather than assumed:
  1. module name  mac_cell_signed_seq -> mac_cell_signed_shell  (L2 is ratified)
  2. shell ports  clear_acc/en_wsh/en_acc -> clr/en_acc/en_wsh  (L2's real names)
  3. scalar port expansion, o0..o31 per cell                    (mechanical, generated)
  4. the SER-SEAM's three idle stubs replaced by real ser_organ instances
Also dropped: a dead `reg [23:0] ext;` superseded by ext0/ext1/ext2 in the draft.

⛔ KNOWN GAP, MINE, REGISTERED NOT HIDDEN (draft v2 found it): ser_organ has NO
shift-enable - it shifts on every load-low cycle. So a 32-bit edge emission
spread over 4 frames would lose 24 bits into the header windows. Tonight's
artifact therefore emits ONE int8 frame per result (v2's decision, adopted).
The full-width emission needs a shift-enable port on serSeq (+32 selects, 99
-> 131 cells) or per-frame reloads; priced and OWED as a v1.1 item. The layout
this feeds measures area/timing/DRC/LVS/antenna, which that choice does not move.
"""

CELLS = 3          # cells 0-2 carry the 2-2-1 demo; cell 3 is clocked-but-idle
NBITS = 32

def cell_inst(k, x, ld, sg, enw, ena):
    ports = [".clk(clk)", ".clr(clr)", f".en_wsh({enw})", f".en_acc({ena})",
             f".i0({x})", f".i1({ld})", f".i2({sg})"]
    ports += [f".o{b}(acc{k}[{b}])" for b in range(NBITS)]
    body = ",\n    ".join(ports)
    return f"  mac_cell_signed_shell cell{k} (\n    {body}\n  );"

def ser_inst(k, load):
    # serSeq: i0 = load (parallel), i1..i32 = the word, o0 = serial out
    ports = [".clk(clk)", f".i0({load})"]
    ports += [f".i{b+1}(acc{k}[{b}])" for b in range(NBITS)]
    ports += [f".o0(ser{k}_out)"]
    body = ",\n    ".join(ports)
    return f"  ser_organ ser{k} (\n    {body}\n  );"

print(f'''// tt_um_saltworks_ndf — the NDF top module.
//
// HAND RTL BY RULING (D2(b) exemption list: pin wrapper + sequencer + fabric).
// The four MAC cells and the three SER organs instantiated below are KERNEL
// EMISSIONS (emitSeqShell / emitSeqMux) and carry their own counted criteria.
// Generated by docs/hdl-tools/gen_ndf_wrapper.py - edit the generator, not this.
//
// SCOPE (silicon's clause, adopted verbatim): a layout of this composition
// measures area / timing / DRC / LVS / antenna. It is NOT a functional demo
// and NOT a tile-fit signoff. Functional correctness is fence-held.
//
// POWER-GATING LAW: no `initial`. Every register reloads at its own strobe;
// the counters realign at sof or rst_n.

`default_nettype none

module tt_um_saltworks_ndf (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
  // ---- D6 pin map (frozen) ----
  wire       sof         = uio_in[6];
  wire       edge_in_dat = uio_in[2];
  wire       edge_in_vld = uio_in[3];
  wire [1:0] phase_o;
  wire       edge_out_dat, edge_out_vld, valid;
  assign uio_oe  = 8'b1011_0011;
  assign uio_out = {{valid, 1'b0, edge_out_vld, edge_out_dat,
                    1'b0, 1'b0, phase_o[1], phase_o[0]}};

  // ---- the core, as-is (R4: demonstrates on its own bus) ----
  slicea16bma core (
    .clk(clk), .rst_n(rst_n),
    .instr_byte(ui_in), .addr_byte(uo_out), .phase_o(phase_o)
  );

  // ---- the fabric. Port indices FROZEN (D6): 0-3 cells, 4 edge-in,
  //      5 edge-out, 6 CPU-stub, 7 spare ----
  wire [7:0] fab_in, fab_out;
  wire [3:0] cnt_o;
  banyan_fabric #(.PAYLOAD(8)) fab (
    .clk(clk), .rst_n(rst_n), .sof(sof),
    .din(fab_in), .dout(fab_out), .cnt_o(cnt_o), .valid(valid)
  );
  assign fab_in[4] = edge_in_dat;
  assign fab_in[5] = 1'b0;   // edge-out is a DESTINATION: nothing sends into it
  assign fab_in[6] = 1'b0;
  assign fab_in[7] = 1'b0;
  assign edge_out_dat = fab_out[5];
  assign edge_out_vld = valid;

  // ---- the 2-2-1 sequencer (hand RTL, D2(b)): 22 frames x 14 cycles ----
  reg [3:0] cyc;
  reg [4:0] frm;
  wire frame_end = (cyc == 4'd13);
  always @(posedge clk) begin
    if (!rst_n || sof) begin cyc <= 4'd0; frm <= 5'd0; end
    else begin
      cyc <= frame_end ? 4'd0 : cyc + 4'd1;
      if (frame_end && frm != 5'd22) frm <= frm + 5'd1;
    end
  end
  wire payload  = (cyc >= 4'd6);
  wire sign_cyc = (cyc == 4'd13);

  wire ld_f0 = (frm==5'd0)||(frm==5'd3)||(frm==5'd8);
  wire ld_f1 = (frm==5'd1)||(frm==5'd4)||(frm==5'd9);
  wire ld_f2 = (frm==5'd2)||(frm==5'd5)||(frm==5'd14);
  wire st_f0 = (frm==5'd6)||(frm==5'd11);
  wire st_f1 = (frm==5'd7)||(frm==5'd12);
  wire st_f2 = (frm==5'd13)||(frm==5'd17);

  // 24 sign-extension cycles after each 8-bit payload (LOAD_W = 32 canonical)
  reg [4:0] ext0, ext1, ext2;
  always @(posedge clk) begin
    if (!rst_n || sof) begin ext0<=5'd0; ext1<=5'd0; ext2<=5'd0; end
    else begin
      if (ld_f0 && frame_end) ext0 <= 5'd24; else if (ext0!=0) ext0 <= ext0-5'd1;
      if (ld_f1 && frame_end) ext1 <= 5'd24; else if (ext1!=0) ext1 <= ext1-5'd1;
      if (ld_f2 && frame_end) ext2 <= 5'd24; else if (ext2!=0) ext2 <= ext2-5'd1;
    end
  end

  // sign-hold: the sender sends 8 bits ONCE (D4h); replay the MSB through
  // the extension window. One flop per cell.
  reg sh0, sh1, sh2;
  always @(posedge clk) begin
    if (ld_f0 && sign_cyc) sh0 <= fab_out[0];
    if (ld_f1 && sign_cyc) sh1 <= fab_out[1];
    if (ld_f2 && sign_cyc) sh2 <= fab_out[2];
  end

  wire bias0 = (frm==5'd2) && (cyc==4'd11);
  wire bias1 = (frm==5'd3) && (cyc==4'd11);
  wire bias2 = (frm==5'd4) && (cyc==4'd11);

  wire x0 = bias0 ? 1'b1 : (ld_f0 && payload) ? fab_out[0]
          : (ext0!=0) ? sh0 : (st_f0 && payload) ? fab_out[0] : 1'b0;
  wire x1 = bias1 ? 1'b1 : (ld_f1 && payload) ? fab_out[1]
          : (ext1!=0) ? sh1 : (st_f1 && payload) ? fab_out[1] : 1'b0;
  wire x2 = bias2 ? 1'b1 : (ld_f2 && payload) ? fab_out[2]
          : (ext2!=0) ? sh2 : (st_f2 && payload) ? fab_out[2] : 1'b0;
  wire load0 = (ld_f0 && payload) || (ext0!=0);
  wire load1 = (ld_f1 && payload) || (ext1!=0);
  wire load2 = (ld_f2 && payload) || (ext2!=0);
  wire sgn0  = st_f0 && sign_cyc;
  wire sgn1  = st_f1 && sign_cyc;
  wire sgn2  = st_f2 && sign_cyc;

  // R6 shell strobes. en_wsh spans load/extension/stream/bias; en_acc only
  // stream+bias (the acc HOLDS during load, or the live AND row dribbles
  // andWord(w_bit, residue) into it).
  wire en_w0 = load0 || (st_f0 && payload) || bias0;
  wire en_w1 = load1 || (st_f1 && payload) || bias1;
  wire en_w2 = load2 || (st_f2 && payload) || bias2;
  wire en_a0 = (st_f0 && payload) || bias0;
  wire en_a1 = (st_f1 && payload) || bias1;
  wire en_a2 = (st_f2 && payload) || bias2;
  wire clr   = (frm==5'd0) && (cyc==4'd0);

  // ACTIVATE strobes: the SER parallel-load. c0@F12, c1@F13, c2@F18.
  // SER parallel-load: latch the SETTLED accumulator at frame end, one frame
  // before its emit window. (Draft v2's ser_ld1 carried an open ADOPTION CALL
  // between F13 and F16; F16 is taken - it latches immediately before the F17
  // emit window, and the acc holds either way because en_acc is low there.)
  wire act0 = (frm==5'd12) && frame_end;
  wire act1 = (frm==5'd16) && frame_end;
  wire act2 = (frm==5'd17) && frame_end;

  wire [31:0] acc0, acc1, acc2, acc3;
  wire ser0_out, ser1_out, ser2_out;

  // ---- the cells: KERNEL-EMITTED (emitSeqShell, L2) ----
{cell_inst(0,'x0','load0','sgn0','en_w0','en_a0')}
{cell_inst(1,'x1','load1','sgn1','en_w1','en_a1')}
{cell_inst(2,'x2','load2','sgn2','en_w2','en_a2')}
  // cell 3: k=4 is forced by fabric ports; idle in the 2-2-1 demo —
  // clocked and cleared, never enabled. Real state, zero schedule.
{cell_inst(3,"1'b0","1'b0","1'b0","1'b0","1'b0")}

  // ---- the SER/activation organs: KERNEL-EMITTED (emitSeqMux) ----
  // NOTE vs draft v2: v2 placed the activation as a BEHAVIOURAL CE-vs-0 mux in
  // this file. It is not needed - ser_organ applies ReLU internally
  // (act_k = and2(d_k, inv(d31))), so the accumulator feeds the organ directly
  // and THE ACTIVATION STAYS INSIDE THE KERNEL EMISSION rather than joining the
  // D2(b) hand-RTL exemption list. That is a boundary win, not a style choice.
{ser_inst(0,'act0')}
{ser_inst(1,'act1')}
{ser_inst(2,'act2')}

  // ---- emit-frame headers (adopted from draft v2, port-organ inlined) ----
  // Frame = [ACT,a2,ACT,a1,ACT,a0] in cycles 0..5, then payload 6..13.
  // dests: h0,h1 -> port 2 (010) · y -> port 5 (101). MSB-first (D4h).
  function hdr_bit; input [2:0] dest; input [3:0] c;
    hdr_bit = (c==4'd0||c==4'd2||c==4'd4) ? 1'b1
            : (c==4'd1) ? dest[2] : (c==4'd3) ? dest[1] : dest[0];
  endfunction
  wire em_f0 = (frm==5'd13);
  wire em_f1 = (frm==5'd17);
  wire em_f2 = (frm==5'd18);
  assign fab_in[0] = em_f0 ? (payload ? ser0_out : hdr_bit(3'd2, cyc)) : 1'b0;
  assign fab_in[1] = em_f1 ? (payload ? ser1_out : hdr_bit(3'd2, cyc)) : 1'b0;
  assign fab_in[2] = em_f2 ? (payload ? ser2_out : hdr_bit(3'd5, cyc)) : 1'b0;
  assign fab_in[3] = 1'b0;   // cell 3 idle

  wire _unused = &{{ena, uio_in[7], uio_in[5:4], uio_in[1:0],
                   edge_in_vld, fab_out[6], fab_out[7], cnt_o,
                   acc3, 1'b0}};

endmodule

`default_nettype wire''')
