/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module adder32(a, b, sub, sum, cout);
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  input sub;
  wire sub;
  output [31:0] sum;
  wire [31:0] sum;
  output cout;
  wire cout;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire [32:0] carry;
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(_045_),
    .B(_047_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__xor2_1 _161_ (
    .A(_043_),
    .B(_145_),
    .X(sum[12])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _162_ (
    .A(_040_),
    .SLEEP(_041_),
    .X(_146_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(carry[11]),
    .B(_146_),
    .Y(sum[11])
  );
  sky130_fd_sc_hd__xnor2_1 _164_ (
    .A(a[10]),
    .B(_036_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__xnor2_1 _165_ (
    .A(carry[10]),
    .B(_147_),
    .Y(sum[10])
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(_033_),
    .A2(_034_),
    .B1(carry[9]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _167_ (
    .A1(_033_),
    .A2(carry[10]),
    .B1(_148_),
    .Y(sum[9])
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(_029_),
    .B(_031_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _169_ (
    .A(_027_),
    .B(_149_),
    .X(sum[8])
  );
  sky130_fd_sc_hd__nor3_1 _170_ (
    .A(a[7]),
    .B(carry[7]),
    .C(_023_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a21oi_1 _171_ (
    .A1(carry[7]),
    .A2(_024_),
    .B1(_027_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(_150_),
    .B(_151_),
    .Y(sum[7])
  );
  sky130_fd_sc_hd__nor3_1 _173_ (
    .A(a[6]),
    .B(carry[6]),
    .C(_020_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand3_1 _174_ (
    .A(a[6]),
    .B(carry[6]),
    .C(_020_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _175_ (
    .A1(carry[7]),
    .A2(_152_),
    .B1(_153_),
    .Y(sum[6])
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(_017_),
    .B(_018_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__xor2_1 _177_ (
    .A(_015_),
    .B(_154_),
    .X(sum[5])
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(_012_),
    .B(_013_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__xor2_1 _179_ (
    .A(_010_),
    .B(_155_),
    .X(sum[4])
  );
  sky130_fd_sc_hd__o21ai_0 _180_ (
    .A1(_007_),
    .A2(_008_),
    .B1(carry[3]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__or3_1 _181_ (
    .A(carry[3]),
    .B(_007_),
    .C(_008_),
    .X(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_156_),
    .B(_157_),
    .Y(sum[3])
  );
  sky130_fd_sc_hd__nand2b_1 _183_ (
    .A_N(_004_),
    .B(_005_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__xnor2_1 _184_ (
    .A(carry[2]),
    .B(_158_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(a[1]),
    .B(_000_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__xnor2_1 _186_ (
    .A(carry[1]),
    .B(_159_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xor2_1 _187_ (
    .A(a[0]),
    .B(b[0]),
    .X(sum[0])
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(sub),
    .A1(a[0]),
    .S(b[0]),
    .X(carry[1])
  );
  sky130_fd_sc_hd__xor2_1 _189_ (
    .A(sub),
    .B(b[1]),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(a[1]),
    .B(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _191_ (
    .A1(a[1]),
    .A2(_000_),
    .B1(carry[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_001_),
    .B(_002_),
    .Y(carry[2])
  );
  sky130_fd_sc_hd__xor2_1 _193_ (
    .A(sub),
    .B(b[2]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _194_ (
    .A(a[2]),
    .B(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(a[2]),
    .B(_003_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a31oi_1 _196_ (
    .A1(_001_),
    .A2(_002_),
    .A3(_005_),
    .B1(_004_),
    .Y(carry[3])
  );
  sky130_fd_sc_hd__xor2_1 _197_ (
    .A(sub),
    .B(b[3]),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(a[3]),
    .B(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__and2_0 _199_ (
    .A(a[3]),
    .B(_006_),
    .X(_008_)
  );
  sky130_fd_sc_hd__a311oi_1 _200_ (
    .A1(_001_),
    .A2(_002_),
    .A3(_005_),
    .B1(_007_),
    .C1(_004_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _201_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _202_ (
    .A(_010_),
    .Y(carry[4])
  );
  sky130_fd_sc_hd__xor2_1 _203_ (
    .A(sub),
    .B(b[4]),
    .X(_011_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _204_ (
    .A(a[4]),
    .SLEEP(_011_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(a[4]),
    .B(_011_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _206_ (
    .A(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _207_ (
    .A1(carry[4]),
    .A2(_012_),
    .B1(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _208_ (
    .A(_015_),
    .Y(carry[5])
  );
  sky130_fd_sc_hd__xor2_1 _209_ (
    .A(sub),
    .B(b[5]),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _210_ (
    .A(a[5]),
    .SLEEP(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(a[5]),
    .B(_016_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o311ai_0 _212_ (
    .A1(_008_),
    .A2(_009_),
    .A3(_014_),
    .B1(_017_),
    .C1(_012_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(_018_),
    .B(_019_),
    .Y(carry[6])
  );
  sky130_fd_sc_hd__xor2_1 _214_ (
    .A(sub),
    .B(b[6]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(a[6]),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _216_ (
    .A(a[6]),
    .B(_020_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _217_ (
    .A1(_018_),
    .A2(_019_),
    .A3(_021_),
    .B1(_022_),
    .Y(carry[7])
  );
  sky130_fd_sc_hd__xor2_1 _218_ (
    .A(sub),
    .B(b[7]),
    .X(_023_)
  );
  sky130_fd_sc_hd__and2_0 _219_ (
    .A(a[7]),
    .B(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(a[7]),
    .B(_023_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a311oi_1 _221_ (
    .A1(_018_),
    .A2(_019_),
    .A3(_021_),
    .B1(_022_),
    .C1(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_024_),
    .B(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _223_ (
    .A(_027_),
    .Y(carry[8])
  );
  sky130_fd_sc_hd__xor2_1 _224_ (
    .A(sub),
    .B(b[8]),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(a[8]),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _226_ (
    .A(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _227_ (
    .A(a[8]),
    .SLEEP(_028_),
    .X(_031_)
  );
  sky130_fd_sc_hd__a21boi_0 _228_ (
    .A1(_027_),
    .A2(_029_),
    .B1_N(_031_),
    .Y(carry[9])
  );
  sky130_fd_sc_hd__xor2_1 _229_ (
    .A(sub),
    .B(b[9]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(a[9]),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _231_ (
    .A(a[9]),
    .SLEEP(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o311ai_0 _232_ (
    .A1(_024_),
    .A2(_026_),
    .A3(_030_),
    .B1(_031_),
    .C1(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_033_),
    .B(_035_),
    .Y(carry[10])
  );
  sky130_fd_sc_hd__xor2_1 _234_ (
    .A(sub),
    .B(b[10]),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(a[10]),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _236_ (
    .A(a[10]),
    .B(_036_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a31oi_1 _237_ (
    .A1(_033_),
    .A2(_035_),
    .A3(_037_),
    .B1(_038_),
    .Y(carry[11])
  );
  sky130_fd_sc_hd__xor2_1 _238_ (
    .A(sub),
    .B(b[11]),
    .X(_039_)
  );
  sky130_fd_sc_hd__and2_0 _239_ (
    .A(a[11]),
    .B(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(a[11]),
    .B(_039_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a311oi_1 _241_ (
    .A1(_033_),
    .A2(_035_),
    .A3(_037_),
    .B1(_038_),
    .C1(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_040_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(_043_),
    .Y(carry[12])
  );
  sky130_fd_sc_hd__xor2_1 _244_ (
    .A(sub),
    .B(b[12]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(a[12]),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _247_ (
    .A(a[12]),
    .SLEEP(_044_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(carry[12]),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(_045_),
    .B(_048_),
    .Y(carry[13])
  );
  sky130_fd_sc_hd__xor2_1 _250_ (
    .A(sub),
    .B(b[13]),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(a[13]),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _252_ (
    .A(a[13]),
    .SLEEP(_049_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o311ai_0 _253_ (
    .A1(_040_),
    .A2(_042_),
    .A3(_046_),
    .B1(_047_),
    .C1(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_050_),
    .B(_052_),
    .Y(carry[14])
  );
  sky130_fd_sc_hd__xor2_1 _255_ (
    .A(sub),
    .B(b[14]),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(a[14]),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(a[14]),
    .B(_053_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a31oi_1 _258_ (
    .A1(_050_),
    .A2(_052_),
    .A3(_054_),
    .B1(_055_),
    .Y(carry[15])
  );
  sky130_fd_sc_hd__xor2_1 _259_ (
    .A(sub),
    .B(b[15]),
    .X(_056_)
  );
  sky130_fd_sc_hd__and2_0 _260_ (
    .A(a[15]),
    .B(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _261_ (
    .A(a[15]),
    .B(_056_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a311oi_1 _262_ (
    .A1(_050_),
    .A2(_052_),
    .A3(_054_),
    .B1(_055_),
    .C1(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(_057_),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _264_ (
    .A(_060_),
    .Y(carry[16])
  );
  sky130_fd_sc_hd__xor2_1 _265_ (
    .A(sub),
    .B(b[16]),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2_0 _266_ (
    .A(a[16]),
    .B(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(a[16]),
    .B(_061_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _268_ (
    .A(a[16]),
    .SLEEP(_061_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21boi_0 _269_ (
    .A1(_060_),
    .A2(_063_),
    .B1_N(_064_),
    .Y(carry[17])
  );
  sky130_fd_sc_hd__xor2_1 _270_ (
    .A(sub),
    .B(b[17]),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(a[17]),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _272_ (
    .A(a[17]),
    .B(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o311ai_0 _274_ (
    .A1(_057_),
    .A2(_059_),
    .A3(_062_),
    .B1(_064_),
    .C1(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_066_),
    .B(_069_),
    .Y(carry[18])
  );
  sky130_fd_sc_hd__xor2_1 _276_ (
    .A(sub),
    .B(b[18]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(a[18]),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(a[18]),
    .B(_070_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a31oi_1 _279_ (
    .A1(_066_),
    .A2(_069_),
    .A3(_071_),
    .B1(_072_),
    .Y(carry[19])
  );
  sky130_fd_sc_hd__xor2_1 _280_ (
    .A(sub),
    .B(b[19]),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2_0 _281_ (
    .A(a[19]),
    .B(_073_),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _282_ (
    .A(a[19]),
    .B(_073_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a311oi_1 _283_ (
    .A1(_066_),
    .A2(_069_),
    .A3(_071_),
    .B1(_072_),
    .C1(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _284_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(_077_),
    .Y(carry[20])
  );
  sky130_fd_sc_hd__xor2_1 _286_ (
    .A(sub),
    .B(b[20]),
    .X(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(a[20]),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__clkinv_1 _288_ (
    .A(_079_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _289_ (
    .A(a[20]),
    .SLEEP(_078_),
    .X(_081_)
  );
  sky130_fd_sc_hd__o21ai_0 _290_ (
    .A1(carry[20]),
    .A2(_080_),
    .B1(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _291_ (
    .A(_082_),
    .Y(carry[21])
  );
  sky130_fd_sc_hd__xor2_1 _292_ (
    .A(sub),
    .B(b[21]),
    .X(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(a[21]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _294_ (
    .A(a[21]),
    .SLEEP(_083_),
    .X(_085_)
  );
  sky130_fd_sc_hd__o311ai_0 _295_ (
    .A1(_074_),
    .A2(_076_),
    .A3(_080_),
    .B1(_081_),
    .C1(_085_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(_084_),
    .B(_086_),
    .Y(carry[22])
  );
  sky130_fd_sc_hd__xor2_1 _297_ (
    .A(sub),
    .B(b[22]),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _298_ (
    .A(a[22]),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(a[22]),
    .B(_087_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a31oi_1 _300_ (
    .A1(_084_),
    .A2(_086_),
    .A3(_088_),
    .B1(_089_),
    .Y(carry[23])
  );
  sky130_fd_sc_hd__xor2_1 _301_ (
    .A(sub),
    .B(b[23]),
    .X(_090_)
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(a[23]),
    .B(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _303_ (
    .A(a[23]),
    .B(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a311oi_1 _304_ (
    .A1(_084_),
    .A2(_086_),
    .A3(_088_),
    .B1(_089_),
    .C1(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(_091_),
    .B(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(_094_),
    .Y(carry[24])
  );
  sky130_fd_sc_hd__xor2_1 _307_ (
    .A(sub),
    .B(b[24]),
    .X(_095_)
  );
  sky130_fd_sc_hd__and2_0 _308_ (
    .A(a[24]),
    .B(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(a[24]),
    .B(_095_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _310_ (
    .A(a[24]),
    .SLEEP(_095_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(carry[24]),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(_097_),
    .B(_099_),
    .Y(carry[25])
  );
  sky130_fd_sc_hd__xor2_1 _313_ (
    .A(sub),
    .B(b[25]),
    .X(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(a[25]),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _315_ (
    .A(a[25]),
    .B(_100_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o311ai_0 _317_ (
    .A1(_091_),
    .A2(_093_),
    .A3(_096_),
    .B1(_098_),
    .C1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_101_),
    .B(_104_),
    .Y(carry[26])
  );
  sky130_fd_sc_hd__xor2_1 _319_ (
    .A(sub),
    .B(b[26]),
    .X(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(a[26]),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(a[26]),
    .B(_105_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a31oi_1 _322_ (
    .A1(_101_),
    .A2(_104_),
    .A3(_106_),
    .B1(_107_),
    .Y(carry[27])
  );
  sky130_fd_sc_hd__xor2_1 _323_ (
    .A(sub),
    .B(b[27]),
    .X(_108_)
  );
  sky130_fd_sc_hd__and2_0 _324_ (
    .A(a[27]),
    .B(_108_),
    .X(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(a[27]),
    .B(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a311oi_1 _326_ (
    .A1(_101_),
    .A2(_104_),
    .A3(_106_),
    .B1(_107_),
    .C1(_110_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _327_ (
    .A(_109_),
    .SLEEP(_111_),
    .X(carry[28])
  );
  sky130_fd_sc_hd__xor2_1 _328_ (
    .A(sub),
    .B(b[28]),
    .X(_112_)
  );
  sky130_fd_sc_hd__and2_0 _329_ (
    .A(a[28]),
    .B(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _330_ (
    .A(a[28]),
    .SLEEP(_112_),
    .X(_114_)
  );
  sky130_fd_sc_hd__o31a_1 _331_ (
    .A1(_109_),
    .A2(_111_),
    .A3(_113_),
    .B1(_114_),
    .X(carry[29])
  );
  sky130_fd_sc_hd__xor2_1 _332_ (
    .A(sub),
    .B(b[29]),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(a[29]),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _334_ (
    .A(a[29]),
    .SLEEP(_115_),
    .X(_117_)
  );
  sky130_fd_sc_hd__o311ai_0 _335_ (
    .A1(_109_),
    .A2(_111_),
    .A3(_113_),
    .B1(_114_),
    .C1(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_116_),
    .B(_118_),
    .Y(carry[30])
  );
  sky130_fd_sc_hd__xor2_1 _337_ (
    .A(sub),
    .B(b[30]),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(a[30]),
    .B(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(a[30]),
    .B(_119_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a31oi_1 _340_ (
    .A1(_116_),
    .A2(_118_),
    .A3(_120_),
    .B1(_121_),
    .Y(carry[31])
  );
  sky130_fd_sc_hd__xor2_1 _341_ (
    .A(sub),
    .B(b[31]),
    .X(_122_)
  );
  sky130_fd_sc_hd__maj3_1 _342_ (
    .A(a[31]),
    .B(carry[31]),
    .C(_122_),
    .X(cout)
  );
  sky130_fd_sc_hd__xnor2_1 _343_ (
    .A(a[31]),
    .B(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _344_ (
    .A(carry[31]),
    .B(_123_),
    .Y(sum[31])
  );
  sky130_fd_sc_hd__xnor2_1 _345_ (
    .A(a[30]),
    .B(_119_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xnor2_1 _346_ (
    .A(carry[30]),
    .B(_124_),
    .Y(sum[30])
  );
  sky130_fd_sc_hd__a21oi_1 _347_ (
    .A1(_116_),
    .A2(_117_),
    .B1(carry[29]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a21oi_1 _348_ (
    .A1(_116_),
    .A2(carry[30]),
    .B1(_125_),
    .Y(sum[29])
  );
  sky130_fd_sc_hd__nor2b_1 _349_ (
    .A(_113_),
    .B_N(_114_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__xor2_1 _350_ (
    .A(carry[28]),
    .B(_126_),
    .X(sum[28])
  );
  sky130_fd_sc_hd__o21ai_0 _351_ (
    .A1(_109_),
    .A2(_110_),
    .B1(carry[27]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__or3_1 _352_ (
    .A(carry[27]),
    .B(_109_),
    .C(_110_),
    .X(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(_127_),
    .B(_128_),
    .Y(sum[27])
  );
  sky130_fd_sc_hd__xnor2_1 _354_ (
    .A(a[26]),
    .B(_105_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__xnor2_1 _355_ (
    .A(carry[26]),
    .B(_129_),
    .Y(sum[26])
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(_102_),
    .B(carry[26]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _357_ (
    .A1_N(carry[25]),
    .A2_N(_130_),
    .B1(carry[26]),
    .B2(_101_),
    .Y(sum[25])
  );
  sky130_fd_sc_hd__nand2_1 _358_ (
    .A(_097_),
    .B(_098_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xor2_1 _359_ (
    .A(_094_),
    .B(_131_),
    .X(sum[24])
  );
  sky130_fd_sc_hd__nor3_1 _360_ (
    .A(a[23]),
    .B(carry[23]),
    .C(_090_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _361_ (
    .A1(carry[23]),
    .A2(_091_),
    .B1(_094_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(_132_),
    .B(_133_),
    .Y(sum[23])
  );
  sky130_fd_sc_hd__o21ba_1 _363_ (
    .A1(_089_),
    .A2(carry[23]),
    .B1_N(carry[22]),
    .X(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _364_ (
    .A1(_088_),
    .A2(carry[23]),
    .B1(_134_),
    .Y(sum[22])
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(_084_),
    .B(_085_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__xor2_1 _366_ (
    .A(_082_),
    .B(_135_),
    .X(sum[21])
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(_079_),
    .B(_081_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xor2_1 _368_ (
    .A(_077_),
    .B(_136_),
    .X(sum[20])
  );
  sky130_fd_sc_hd__o21ai_0 _369_ (
    .A1(_074_),
    .A2(_075_),
    .B1(carry[19]),
    .Y(_137_)
  );
  sky130_fd_sc_hd__or3_1 _370_ (
    .A(carry[19]),
    .B(_074_),
    .C(_075_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _371_ (
    .A(_137_),
    .B(_138_),
    .Y(sum[19])
  );
  sky130_fd_sc_hd__xnor2_1 _372_ (
    .A(a[18]),
    .B(_070_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xnor2_1 _373_ (
    .A(carry[18]),
    .B(_139_),
    .Y(sum[18])
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(_067_),
    .B(carry[18]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _375_ (
    .A1_N(carry[17]),
    .A2_N(_140_),
    .B1(carry[18]),
    .B2(_066_),
    .Y(sum[17])
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(_063_),
    .B(_064_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__xor2_1 _377_ (
    .A(_060_),
    .B(_141_),
    .X(sum[16])
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(_057_),
    .B(_058_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xor2_1 _379_ (
    .A(carry[15]),
    .B(_142_),
    .X(sum[15])
  );
  sky130_fd_sc_hd__xnor2_1 _380_ (
    .A(a[14]),
    .B(_053_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xnor2_1 _381_ (
    .A(carry[14]),
    .B(_143_),
    .Y(sum[14])
  );
  sky130_fd_sc_hd__a21oi_1 _382_ (
    .A1(_050_),
    .A2(_051_),
    .B1(carry[13]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a21oi_1 _383_ (
    .A1(_050_),
    .A2(carry[14]),
    .B1(_144_),
    .Y(sum[13])
  );
  assign { carry[32], carry[0] } = { cout, sub };
endmodule
