/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module adder8r(a, b, cin, sum, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input cin;
  wire cin;
  output [7:0] sum;
  wire [7:0] sum;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__maj3_1 _16_ (
    .A(a[0]),
    .B(b[0]),
    .C(cin),
    .X(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _18_ (
    .A(a[1]),
    .B(b[1]),
    .C(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(a[2]),
    .B(b[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _20_ (
    .A(a[2]),
    .B(b[2]),
    .C(_03_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(a[3]),
    .B(b[3]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _22_ (
    .A(a[3]),
    .B(b[3]),
    .C(_05_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _23_ (
    .A(a[4]),
    .B(b[4]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__maj3_1 _24_ (
    .A(a[4]),
    .B(b[4]),
    .C(_07_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(a[5]),
    .B(b[5]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__maj3_1 _26_ (
    .A(a[5]),
    .B(b[5]),
    .C(_09_),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_1 _27_ (
    .A(a[6]),
    .B(b[6]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(_11_),
    .B(_12_),
    .Y(sum[6])
  );
  sky130_fd_sc_hd__xnor2_1 _29_ (
    .A(_09_),
    .B(_10_),
    .Y(sum[5])
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(_07_),
    .B(_08_),
    .Y(sum[4])
  );
  sky130_fd_sc_hd__xnor2_1 _31_ (
    .A(_05_),
    .B(_06_),
    .Y(sum[3])
  );
  sky130_fd_sc_hd__maj3_1 _32_ (
    .A(a[6]),
    .B(b[6]),
    .C(_11_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xnor2_1 _33_ (
    .A(a[7]),
    .B(b[7]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(_13_),
    .B(_14_),
    .Y(sum[7])
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(_03_),
    .B(_04_),
    .Y(sum[2])
  );
  sky130_fd_sc_hd__maj3_1 _36_ (
    .A(a[7]),
    .B(b[7]),
    .C(_13_),
    .X(cout)
  );
  sky130_fd_sc_hd__xnor2_1 _37_ (
    .A(_01_),
    .B(_02_),
    .Y(sum[1])
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(cin),
    .B(_00_),
    .Y(sum[0])
  );
endmodule
