/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module banyan_element(s0lo, s1lo, s0hi, s1hi, a, b, ylo, yhi);
  input s0lo;
  wire s0lo;
  input s1lo;
  wire s1lo;
  input s0hi;
  wire s0hi;
  input s1hi;
  wire s1hi;
  input a;
  wire a;
  input b;
  wire b;
  output ylo;
  wire ylo;
  output yhi;
  wire yhi;
  sky130_fd_sc_hd__a22o_1 _0_ (
    .A1(s0hi),
    .A2(a),
    .B1(s1hi),
    .B2(b),
    .X(yhi)
  );
  sky130_fd_sc_hd__a22o_1 _1_ (
    .A1(a),
    .A2(s0lo),
    .B1(s1lo),
    .B2(b),
    .X(ylo)
  );
endmodule
