/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module bitserial_switch(clk, rst_n, act_stb, sel_stb, in0, in1, out0, out1);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input act_stb;
  wire act_stb;
  input sel_stb;
  wire sel_stb;
  input in0;
  wire in0;
  input in1;
  wire in1;
  output out0;
  wire out0;
  output out1;
  wire out1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire act0;
  wire act1;
  wire sel0;
  wire sel1;
  sky130_fd_sc_hd__nand2_1 _12_ (
    .A(in0),
    .B(act0),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand3_1 _13_ (
    .A(sel0),
    .B(in0),
    .C(act0),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _14_ (
    .A(in1),
    .B(act1),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand3_1 _15_ (
    .A(sel1),
    .B(in1),
    .C(act1),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _16_ (
    .A(_05_),
    .B(_07_),
    .Y(out1)
  );
  sky130_fd_sc_hd__o22ai_1 _17_ (
    .A1(sel0),
    .A2(_04_),
    .B1(_06_),
    .B2(sel1),
    .Y(out0)
  );
  sky130_fd_sc_hd__mux2i_1 _18_ (
    .A0(act0),
    .A1(in0),
    .S(act_stb),
    .Y(_08_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _19_ (
    .A(rst_n),
    .SLEEP(_08_),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2i_1 _20_ (
    .A0(act1),
    .A1(in1),
    .S(act_stb),
    .Y(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _21_ (
    .A(rst_n),
    .SLEEP(_09_),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2i_1 _22_ (
    .A0(sel0),
    .A1(in0),
    .S(sel_stb),
    .Y(_10_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _23_ (
    .A(rst_n),
    .SLEEP(_10_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2i_1 _24_ (
    .A0(sel1),
    .A1(in1),
    .S(sel_stb),
    .Y(_11_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _25_ (
    .A(rst_n),
    .SLEEP(_11_),
    .X(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _26_ (
    .CLK(clk),
    .D(_02_),
    .Q(sel0)
  );
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(clk),
    .D(_01_),
    .Q(act1)
  );
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clk),
    .D(_00_),
    .Q(act0)
  );
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clk),
    .D(_03_),
    .Q(sel1)
  );
endmodule
