/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module comparator(a, b, lo, hi);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  output [7:0] lo;
  wire [7:0] lo;
  output [7:0] hi;
  wire [7:0] hi;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(b[7]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(a[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(a[2]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(a[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(a[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _25_ (
    .A(a[4]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _26_ (
    .A(b[6]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _27_ (
    .A(a[5]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(b[5]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _29_ (
    .A(b[7]),
    .SLEEP(a[7]),
    .X(hi[7])
  );
  sky130_fd_sc_hd__and2_0 _30_ (
    .A(b[7]),
    .B(a[7]),
    .X(lo[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _31_ (
    .A(b[3]),
    .SLEEP(a[3]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _32_ (
    .A(b[2]),
    .B(_02_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(b[1]),
    .B(_03_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a22oi_1 _34_ (
    .A1(b[4]),
    .A2(_05_),
    .B1(_07_),
    .B2(b[5]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o22ai_1 _35_ (
    .A1(b[1]),
    .A2(_03_),
    .B1(_04_),
    .B2(b[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o22ai_1 _36_ (
    .A1(b[3]),
    .A2(_01_),
    .B1(b[2]),
    .B2(_02_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a31oi_1 _37_ (
    .A1(_10_),
    .A2(_11_),
    .A3(_13_),
    .B1(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o22ai_1 _38_ (
    .A1(b[4]),
    .A2(_05_),
    .B1(_09_),
    .B2(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a222oi_1 _39_ (
    .A1(a[6]),
    .A2(_06_),
    .B1(a[5]),
    .B2(_08_),
    .C1(_12_),
    .C2(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o22ai_1 _40_ (
    .A1(_00_),
    .A2(a[7]),
    .B1(a[6]),
    .B2(_06_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _41_ (
    .A1_N(_00_),
    .A2_N(a[7]),
    .B1(_17_),
    .B2(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__mux2_1 _42_ (
    .A0(b[6]),
    .A1(a[6]),
    .S(_19_),
    .X(hi[6])
  );
  sky130_fd_sc_hd__mux2i_1 _43_ (
    .A0(_08_),
    .A1(_07_),
    .S(_19_),
    .Y(hi[5])
  );
  sky130_fd_sc_hd__mux2_1 _44_ (
    .A0(b[4]),
    .A1(a[4]),
    .S(_19_),
    .X(hi[4])
  );
  sky130_fd_sc_hd__mux2_1 _45_ (
    .A0(b[3]),
    .A1(a[3]),
    .S(_19_),
    .X(hi[3])
  );
  sky130_fd_sc_hd__mux2_1 _46_ (
    .A0(b[2]),
    .A1(a[2]),
    .S(_19_),
    .X(hi[2])
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(b[1]),
    .A1(a[1]),
    .S(_19_),
    .X(hi[1])
  );
  sky130_fd_sc_hd__mux2_1 _48_ (
    .A0(b[0]),
    .A1(a[0]),
    .S(_19_),
    .X(hi[0])
  );
  sky130_fd_sc_hd__mux2_1 _49_ (
    .A0(a[6]),
    .A1(b[6]),
    .S(_19_),
    .X(lo[6])
  );
  sky130_fd_sc_hd__mux2i_1 _50_ (
    .A0(_07_),
    .A1(_08_),
    .S(_19_),
    .Y(lo[5])
  );
  sky130_fd_sc_hd__mux2_1 _51_ (
    .A0(a[4]),
    .A1(b[4]),
    .S(_19_),
    .X(lo[4])
  );
  sky130_fd_sc_hd__mux2_1 _52_ (
    .A0(a[3]),
    .A1(b[3]),
    .S(_19_),
    .X(lo[3])
  );
  sky130_fd_sc_hd__mux2_1 _53_ (
    .A0(a[2]),
    .A1(b[2]),
    .S(_19_),
    .X(lo[2])
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(a[1]),
    .A1(b[1]),
    .S(_19_),
    .X(lo[1])
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(a[0]),
    .A1(b[0]),
    .S(_19_),
    .X(lo[0])
  );
endmodule
