/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module ctrl32(instr, pc, zero, lt, ltu, imm, pc_next, reg_we, mem_we, mem_re, alu_src, wb_sel, alu_op, br_taken);
  input [31:0] instr;
  wire [31:0] instr;
  input [31:0] pc;
  wire [31:0] pc;
  input zero;
  wire zero;
  input lt;
  wire lt;
  input ltu;
  wire ltu;
  output [31:0] imm;
  wire [31:0] imm;
  output [31:0] pc_next;
  wire [31:0] pc_next;
  output reg_we;
  wire reg_we;
  output mem_we;
  wire mem_we;
  output mem_re;
  wire mem_re;
  output alu_src;
  wire alu_src;
  output [1:0] wb_sel;
  wire [1:0] wb_sel;
  output [3:0] alu_op;
  wire [3:0] alu_op;
  output br_taken;
  wire br_taken;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire [31:0] imm_b;
  wire [31:0] imm_i;
  wire [31:0] imm_j;
  wire [31:0] imm_s;
  wire [31:0] imm_u;
  wire [31:0] pc_plus_4;
  wire [31:0] pc_plus_imm;
  sky130_fd_sc_hd__clkinv_1 _215_ (
    .A(pc[2]),
    .Y(pc_plus_4[2])
  );
  sky130_fd_sc_hd__clkinv_1 _216_ (
    .A(instr[20]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _217_ (
    .A(instr[7]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _218_ (
    .A(pc[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and3_1 _219_ (
    .A(instr[1]),
    .B(instr[0]),
    .C(instr[2]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand3_1 _220_ (
    .A(instr[1]),
    .B(instr[0]),
    .C(instr[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _221_ (
    .A(instr[5]),
    .SLEEP(instr[4]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2b_1 _222_ (
    .A_N(instr[4]),
    .B(instr[5]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and3b_1 _223_ (
    .A_N(instr[4]),
    .B(instr[6]),
    .C(instr[5]),
    .X(_007_)
  );
  sky130_fd_sc_hd__and2_0 _224_ (
    .A(_003_),
    .B(_007_),
    .X(wb_sel[1])
  );
  sky130_fd_sc_hd__clkinv_1 _225_ (
    .A(wb_sel[1]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3_1 _226_ (
    .A(instr[3]),
    .B(_003_),
    .C(_007_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _227_ (
    .A(instr[4]),
    .SLEEP(instr[6]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2b_1 _228_ (
    .A_N(instr[6]),
    .B(instr[4]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor3_1 _229_ (
    .A(instr[3]),
    .B(_004_),
    .C(_011_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__or3_1 _230_ (
    .A(instr[3]),
    .B(_004_),
    .C(_011_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(_009_),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__and2_0 _232_ (
    .A(instr[31]),
    .B(_013_),
    .X(_015_)
  );
  sky130_fd_sc_hd__and3_1 _233_ (
    .A(instr[31]),
    .B(_009_),
    .C(_013_),
    .X(_016_)
  );
  sky130_fd_sc_hd__a21o_1 _234_ (
    .A1(instr[15]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[15])
  );
  sky130_fd_sc_hd__a21oi_1 _235_ (
    .A1(instr[29]),
    .A2(_012_),
    .B1(_015_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _236_ (
    .A(_017_),
    .Y(imm[29])
  );
  sky130_fd_sc_hd__nand3_1 _237_ (
    .A(pc[2]),
    .B(pc[3]),
    .C(pc[4]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand4_1 _238_ (
    .A(pc[2]),
    .B(pc[3]),
    .C(pc[4]),
    .D(pc[5]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _239_ (
    .A(pc[6]),
    .SLEEP(_019_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand3_1 _240_ (
    .A(pc[7]),
    .B(pc[8]),
    .C(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _241_ (
    .A(pc[9]),
    .SLEEP(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand3_1 _242_ (
    .A(pc[10]),
    .B(pc[11]),
    .C(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _243_ (
    .A(pc[12]),
    .SLEEP(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _244_ (
    .A(pc[13]),
    .B(pc[14]),
    .C(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _245_ (
    .A(pc[15]),
    .SLEEP(_025_),
    .X(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _246_ (
    .A(pc[16]),
    .B(pc[17]),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _247_ (
    .A(pc[18]),
    .SLEEP(_027_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nand3_1 _248_ (
    .A(pc[19]),
    .B(pc[20]),
    .C(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _249_ (
    .A(pc[21]),
    .SLEEP(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand3_1 _250_ (
    .A(pc[22]),
    .B(pc[23]),
    .C(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _251_ (
    .A(pc[24]),
    .SLEEP(_031_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _252_ (
    .A(pc[25]),
    .B(_032_),
    .X(pc_plus_4[25])
  );
  sky130_fd_sc_hd__xnor2_1 _253_ (
    .A(pc[24]),
    .B(_031_),
    .Y(pc_plus_4[24])
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(pc[22]),
    .A2(_030_),
    .B1(pc[23]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _255_ (
    .A(_031_),
    .SLEEP(_033_),
    .X(pc_plus_4[23])
  );
  sky130_fd_sc_hd__xor2_1 _256_ (
    .A(pc[22]),
    .B(_030_),
    .X(pc_plus_4[22])
  );
  sky130_fd_sc_hd__xnor2_1 _257_ (
    .A(pc[21]),
    .B(_029_),
    .Y(pc_plus_4[21])
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(pc[19]),
    .A2(_028_),
    .B1(pc[20]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _259_ (
    .A(_029_),
    .SLEEP(_034_),
    .X(pc_plus_4[20])
  );
  sky130_fd_sc_hd__xor2_1 _260_ (
    .A(pc[19]),
    .B(_028_),
    .X(pc_plus_4[19])
  );
  sky130_fd_sc_hd__xnor2_1 _261_ (
    .A(pc[18]),
    .B(_027_),
    .Y(pc_plus_4[18])
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(pc[16]),
    .A2(_026_),
    .B1(pc[17]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _263_ (
    .A(_027_),
    .SLEEP(_035_),
    .X(pc_plus_4[17])
  );
  sky130_fd_sc_hd__xor2_1 _264_ (
    .A(pc[16]),
    .B(_026_),
    .X(pc_plus_4[16])
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(pc[15]),
    .B(_025_),
    .Y(pc_plus_4[15])
  );
  sky130_fd_sc_hd__a21oi_1 _266_ (
    .A1(pc[13]),
    .A2(_024_),
    .B1(pc[14]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _267_ (
    .A(_025_),
    .SLEEP(_036_),
    .X(pc_plus_4[14])
  );
  sky130_fd_sc_hd__xor2_1 _268_ (
    .A(pc[13]),
    .B(_024_),
    .X(pc_plus_4[13])
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(pc[12]),
    .B(_023_),
    .Y(pc_plus_4[12])
  );
  sky130_fd_sc_hd__a21oi_1 _270_ (
    .A1(pc[10]),
    .A2(_022_),
    .B1(pc[11]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _271_ (
    .A(_023_),
    .SLEEP(_037_),
    .X(pc_plus_4[11])
  );
  sky130_fd_sc_hd__a21oi_1 _272_ (
    .A1(instr[20]),
    .A2(_012_),
    .B1(_015_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(_038_),
    .Y(imm[20])
  );
  sky130_fd_sc_hd__and2_0 _274_ (
    .A(instr[27]),
    .B(_013_),
    .X(imm[7])
  );
  sky130_fd_sc_hd__a21oi_1 _275_ (
    .A1(instr[30]),
    .A2(_012_),
    .B1(_015_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _276_ (
    .A(_039_),
    .Y(imm[30])
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(instr[28]),
    .A2(_012_),
    .B1(_015_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _278_ (
    .A(_040_),
    .Y(imm[28])
  );
  sky130_fd_sc_hd__a21oi_1 _279_ (
    .A1(instr[27]),
    .A2(_012_),
    .B1(_015_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(_041_),
    .Y(imm[27])
  );
  sky130_fd_sc_hd__a21o_1 _281_ (
    .A1(instr[26]),
    .A2(_012_),
    .B1(_015_),
    .X(imm[26])
  );
  sky130_fd_sc_hd__a21o_1 _282_ (
    .A1(instr[25]),
    .A2(_012_),
    .B1(_015_),
    .X(imm[25])
  );
  sky130_fd_sc_hd__a21o_1 _283_ (
    .A1(instr[24]),
    .A2(_012_),
    .B1(_015_),
    .X(imm[24])
  );
  sky130_fd_sc_hd__a21oi_1 _284_ (
    .A1(instr[23]),
    .A2(_012_),
    .B1(_015_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(_042_),
    .Y(imm[23])
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(instr[22]),
    .A2(_012_),
    .B1(_015_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _287_ (
    .A(_043_),
    .Y(imm[22])
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(instr[21]),
    .A2(_012_),
    .B1(_015_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _289_ (
    .A(_044_),
    .Y(imm[21])
  );
  sky130_fd_sc_hd__a21o_1 _290_ (
    .A1(instr[19]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[19])
  );
  sky130_fd_sc_hd__a21o_1 _291_ (
    .A1(instr[18]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[18])
  );
  sky130_fd_sc_hd__a21o_1 _292_ (
    .A1(instr[17]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[17])
  );
  sky130_fd_sc_hd__a21o_1 _293_ (
    .A1(instr[16]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[16])
  );
  sky130_fd_sc_hd__a21o_1 _294_ (
    .A1(instr[14]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[14])
  );
  sky130_fd_sc_hd__a21o_1 _295_ (
    .A1(instr[13]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[13])
  );
  sky130_fd_sc_hd__a21o_1 _296_ (
    .A1(instr[12]),
    .A2(_014_),
    .B1(_016_),
    .X(imm[12])
  );
  sky130_fd_sc_hd__nor4bb_1 _297_ (
    .A(instr[2]),
    .B(instr[3]),
    .C_N(instr[1]),
    .D_N(instr[0]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand4bb_1 _298_ (
    .A_N(instr[2]),
    .B_N(instr[3]),
    .C(instr[1]),
    .D(instr[0]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _299_ (
    .A(_006_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(_005_),
    .B(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(_007_),
    .B(_045_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(_000_),
    .A2(_009_),
    .B1(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o22ai_1 _303_ (
    .A1(instr[7]),
    .A2(_049_),
    .B1(_050_),
    .B2(_016_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _304_ (
    .A(_051_),
    .Y(imm[11])
  );
  sky130_fd_sc_hd__and2_0 _305_ (
    .A(instr[30]),
    .B(_013_),
    .X(imm[10])
  );
  sky130_fd_sc_hd__and2_0 _306_ (
    .A(instr[29]),
    .B(_013_),
    .X(imm[9])
  );
  sky130_fd_sc_hd__and2_0 _307_ (
    .A(instr[28]),
    .B(_013_),
    .X(imm[8])
  );
  sky130_fd_sc_hd__and2_0 _308_ (
    .A(instr[26]),
    .B(_013_),
    .X(imm[6])
  );
  sky130_fd_sc_hd__and2_0 _309_ (
    .A(instr[25]),
    .B(_013_),
    .X(imm[5])
  );
  sky130_fd_sc_hd__and3_1 _310_ (
    .A(instr[24]),
    .B(_013_),
    .C(_048_),
    .X(_052_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(instr[11]),
    .A2(_047_),
    .B1(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(_053_),
    .Y(imm[4])
  );
  sky130_fd_sc_hd__o21ai_0 _313_ (
    .A1(_006_),
    .A2(_046_),
    .B1(instr[23]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _314_ (
    .A1_N(instr[10]),
    .A2_N(_047_),
    .B1(_054_),
    .B2(_012_),
    .Y(imm[3])
  );
  sky130_fd_sc_hd__o21ai_0 _315_ (
    .A1(_006_),
    .A2(_046_),
    .B1(instr[22]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _316_ (
    .A1_N(instr[9]),
    .A2_N(_047_),
    .B1(_055_),
    .B2(_012_),
    .Y(imm[2])
  );
  sky130_fd_sc_hd__o31ai_1 _317_ (
    .A1(instr[3]),
    .A2(_004_),
    .A3(_011_),
    .B1(instr[21]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _318_ (
    .A(instr[8]),
    .B(_006_),
    .C(_046_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _319_ (
    .A1(_006_),
    .A2(_046_),
    .B1(instr[21]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand3_1 _320_ (
    .A(instr[8]),
    .B(_005_),
    .C(_045_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _321_ (
    .A1(_048_),
    .A2(_056_),
    .B1(_057_),
    .Y(imm[1])
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(instr[6]),
    .B(_048_),
    .Y(mem_we)
  );
  sky130_fd_sc_hd__nor4_1 _323_ (
    .A(instr[6]),
    .B(_001_),
    .C(_006_),
    .D(_046_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a41o_1 _324_ (
    .A1(instr[20]),
    .A2(_009_),
    .A3(_013_),
    .A4(_048_),
    .B1(_060_),
    .X(imm[0])
  );
  sky130_fd_sc_hd__nand2_1 _325_ (
    .A(pc[30]),
    .B(imm[30]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xnor2_1 _326_ (
    .A(pc[30]),
    .B(_039_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _328_ (
    .A(pc[29]),
    .B(imm[29]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _329_ (
    .A(pc[29]),
    .SLEEP(_017_),
    .X(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _330_ (
    .A(pc[28]),
    .SLEEP(_040_),
    .X(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _331_ (
    .A(pc[28]),
    .B(_040_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2b_1 _332_ (
    .A_N(pc[27]),
    .B(_041_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(pc[27]),
    .B(imm[27]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _334_ (
    .A(pc[26]),
    .B(imm[26]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__xnor2_1 _335_ (
    .A(pc[26]),
    .B(imm[26]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(pc[25]),
    .B(imm[25]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__and2_0 _337_ (
    .A(pc[25]),
    .B(imm[25]),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2_0 _338_ (
    .A(pc[24]),
    .B(imm[24]),
    .X(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _339_ (
    .A(pc[24]),
    .B(imm[24]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2b_1 _341_ (
    .A_N(pc[23]),
    .B(_042_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(pc[23]),
    .B(imm[23]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(pc[22]),
    .B(imm[22]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(pc[22]),
    .B(imm[22]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _345_ (
    .A(_079_),
    .SLEEP(_080_),
    .X(_081_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _346_ (
    .A(pc[21]),
    .SLEEP(_044_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(pc[21]),
    .B(imm[21]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _348_ (
    .A(pc[20]),
    .SLEEP(_038_),
    .X(_084_)
  );
  sky130_fd_sc_hd__xnor2_1 _349_ (
    .A(pc[20]),
    .B(_038_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(pc[19]),
    .B(imm[19]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _351_ (
    .A(pc[19]),
    .SLEEP(imm[19]),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(pc[18]),
    .B(imm[18]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(pc[18]),
    .B(imm[18]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _354_ (
    .A(_088_),
    .SLEEP(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _355_ (
    .A(pc[17]),
    .B(imm[17]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and2_0 _356_ (
    .A(pc[17]),
    .B(imm[17]),
    .X(_092_)
  );
  sky130_fd_sc_hd__and2_0 _357_ (
    .A(pc[16]),
    .B(imm[16]),
    .X(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(pc[16]),
    .B(imm[16]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _359_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _360_ (
    .A(pc[15]),
    .SLEEP(imm[15]),
    .X(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(pc[15]),
    .B(imm[15]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _362_ (
    .A(pc[14]),
    .B(imm[14]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__xnor2_1 _363_ (
    .A(pc[14]),
    .B(imm[14]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _364_ (
    .A(pc[13]),
    .B(imm[13]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__and2_0 _365_ (
    .A(pc[13]),
    .B(imm[13]),
    .X(_101_)
  );
  sky130_fd_sc_hd__and2_0 _366_ (
    .A(pc[12]),
    .B(imm[12]),
    .X(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(pc[12]),
    .B(imm[12]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _368_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _369_ (
    .A(pc[11]),
    .SLEEP(_051_),
    .X(_105_)
  );
  sky130_fd_sc_hd__clkinv_1 _370_ (
    .A(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2b_1 _371_ (
    .A_N(pc[11]),
    .B(_051_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(pc[10]),
    .B(imm[10]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _373_ (
    .A(pc[10]),
    .B(imm[10]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(pc[9]),
    .B(imm[9]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__and3_1 _375_ (
    .A(instr[29]),
    .B(pc[9]),
    .C(_013_),
    .X(_111_)
  );
  sky130_fd_sc_hd__and3_1 _376_ (
    .A(pc[8]),
    .B(instr[28]),
    .C(_013_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _377_ (
    .A(pc[8]),
    .B(imm[8]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(_112_),
    .B(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _379_ (
    .A(pc[7]),
    .SLEEP(imm[7]),
    .X(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _380_ (
    .A(pc[7]),
    .B(imm[7]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _381_ (
    .A(pc[6]),
    .B(imm[6]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__xnor2_1 _382_ (
    .A(pc[6]),
    .B(imm[6]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__and3_1 _383_ (
    .A(pc[5]),
    .B(instr[25]),
    .C(_013_),
    .X(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(pc[5]),
    .B(imm[5]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _385_ (
    .A(pc[4]),
    .SLEEP(_053_),
    .X(_121_)
  );
  sky130_fd_sc_hd__nand2b_1 _386_ (
    .A_N(pc[4]),
    .B(_053_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2b_1 _387_ (
    .A(_121_),
    .B_N(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _388_ (
    .A(pc[3]),
    .B(imm[3]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _389_ (
    .A(pc[3]),
    .SLEEP(imm[3]),
    .X(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(pc[2]),
    .B(imm[2]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a211oi_1 _391_ (
    .A1(_048_),
    .A2(_056_),
    .B1(_057_),
    .C1(_002_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _392_ (
    .A(pc[0]),
    .B(imm[0]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o211ai_1 _393_ (
    .A1(_012_),
    .A2(_058_),
    .B1(_059_),
    .C1(_002_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2b_1 _394_ (
    .A_N(_127_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__a31oi_1 _395_ (
    .A1(pc[0]),
    .A2(imm[0]),
    .A3(_129_),
    .B1(_127_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__xnor2_1 _396_ (
    .A(pc[2]),
    .B(imm[2]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21a_1 _397_ (
    .A1(_131_),
    .A2(_132_),
    .B1(_126_),
    .X(_133_)
  );
  sky130_fd_sc_hd__o211ai_1 _398_ (
    .A1(_131_),
    .A2(_132_),
    .B1(_124_),
    .C1(_126_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_125_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a31oi_1 _400_ (
    .A1(_122_),
    .A2(_125_),
    .A3(_134_),
    .B1(_121_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a311oi_1 _401_ (
    .A1(_122_),
    .A2(_125_),
    .A3(_134_),
    .B1(_121_),
    .C1(_119_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(_120_),
    .B(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__o31ai_1 _403_ (
    .A1(_118_),
    .A2(_120_),
    .A3(_137_),
    .B1(_117_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o311ai_0 _404_ (
    .A1(_118_),
    .A2(_120_),
    .A3(_137_),
    .B1(_117_),
    .C1(_116_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand3_1 _405_ (
    .A(_114_),
    .B(_115_),
    .C(_140_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a31oi_1 _406_ (
    .A1(_114_),
    .A2(_115_),
    .A3(_140_),
    .B1(_112_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a311oi_1 _407_ (
    .A1(_114_),
    .A2(_115_),
    .A3(_140_),
    .B1(_112_),
    .C1(_111_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor2_1 _408_ (
    .A(_110_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o31ai_1 _409_ (
    .A1(_109_),
    .A2(_110_),
    .A3(_143_),
    .B1(_108_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o311ai_0 _410_ (
    .A1(_109_),
    .A2(_110_),
    .A3(_143_),
    .B1(_108_),
    .C1(_106_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__and3_1 _411_ (
    .A(_104_),
    .B(_107_),
    .C(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(_102_),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a311oi_1 _413_ (
    .A1(_104_),
    .A2(_107_),
    .A3(_146_),
    .B1(_102_),
    .C1(_101_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _414_ (
    .A(_100_),
    .B(_149_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o31a_1 _415_ (
    .A1(_099_),
    .A2(_100_),
    .A3(_149_),
    .B1(_098_),
    .X(_151_)
  );
  sky130_fd_sc_hd__o311ai_0 _416_ (
    .A1(_099_),
    .A2(_100_),
    .A3(_149_),
    .B1(_098_),
    .C1(_097_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _417_ (
    .A(_096_),
    .B(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__a31oi_1 _418_ (
    .A1(_095_),
    .A2(_096_),
    .A3(_152_),
    .B1(_093_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a311oi_1 _419_ (
    .A1(_095_),
    .A2(_096_),
    .A3(_152_),
    .B1(_093_),
    .C1(_092_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(_091_),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(_090_),
    .B(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(_088_),
    .B(_157_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o311ai_0 _423_ (
    .A1(_089_),
    .A2(_091_),
    .A3(_155_),
    .B1(_088_),
    .C1(_086_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(_087_),
    .B(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a31oi_1 _425_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_159_),
    .B1(_084_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a311oi_1 _426_ (
    .A1(_085_),
    .A2(_087_),
    .A3(_159_),
    .B1(_084_),
    .C1(_082_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _427_ (
    .A(_083_),
    .SLEEP(_162_),
    .X(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _428_ (
    .A1(_080_),
    .A2(_163_),
    .B1(_079_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__o311ai_0 _429_ (
    .A1(_080_),
    .A2(_083_),
    .A3(_162_),
    .B1(_079_),
    .C1(_078_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_1 _430_ (
    .A(_077_),
    .B(_165_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__a31oi_1 _431_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_165_),
    .B1(_074_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a311oi_1 _432_ (
    .A1(_076_),
    .A2(_077_),
    .A3(_165_),
    .B1(_074_),
    .C1(_073_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _433_ (
    .A(_072_),
    .B(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o31ai_1 _434_ (
    .A1(_071_),
    .A2(_072_),
    .A3(_168_),
    .B1(_070_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o311ai_0 _435_ (
    .A1(_071_),
    .A2(_072_),
    .A3(_168_),
    .B1(_070_),
    .C1(_069_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__and3_1 _436_ (
    .A(_067_),
    .B(_068_),
    .C(_171_),
    .X(_172_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_066_),
    .B(_172_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a311oi_1 _438_ (
    .A1(_067_),
    .A2(_068_),
    .A3(_171_),
    .B1(_066_),
    .C1(_065_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(_064_),
    .B(_174_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__o31ai_1 _440_ (
    .A1(_063_),
    .A2(_064_),
    .A3(_174_),
    .B1(_061_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__xnor2_1 _441_ (
    .A(instr[31]),
    .B(pc[31]),
    .Y(_177_)
  );
  sky130_fd_sc_hd__xnor2_1 _442_ (
    .A(_176_),
    .B(_177_),
    .Y(pc_plus_imm[31])
  );
  sky130_fd_sc_hd__xnor2_1 _443_ (
    .A(_063_),
    .B(_175_),
    .Y(pc_plus_imm[30])
  );
  sky130_fd_sc_hd__nor2_1 _444_ (
    .A(_064_),
    .B(_065_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__xnor2_1 _445_ (
    .A(_173_),
    .B(_178_),
    .Y(pc_plus_imm[29])
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(_068_),
    .A2(_171_),
    .B1(_067_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nor2_1 _447_ (
    .A(_172_),
    .B(_179_),
    .Y(pc_plus_imm[28])
  );
  sky130_fd_sc_hd__and2_0 _448_ (
    .A(_068_),
    .B(_069_),
    .X(_180_)
  );
  sky130_fd_sc_hd__xor2_1 _449_ (
    .A(_170_),
    .B(_180_),
    .X(pc_plus_imm[27])
  );
  sky130_fd_sc_hd__xnor2_1 _450_ (
    .A(_071_),
    .B(_169_),
    .Y(pc_plus_imm[26])
  );
  sky130_fd_sc_hd__nor2_1 _451_ (
    .A(_072_),
    .B(_073_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _452_ (
    .A(_167_),
    .B(_181_),
    .Y(pc_plus_imm[25])
  );
  sky130_fd_sc_hd__xnor2_1 _453_ (
    .A(_076_),
    .B(_166_),
    .Y(pc_plus_imm[24])
  );
  sky130_fd_sc_hd__and2_0 _454_ (
    .A(_077_),
    .B(_078_),
    .X(_182_)
  );
  sky130_fd_sc_hd__xor2_1 _455_ (
    .A(_164_),
    .B(_182_),
    .X(pc_plus_imm[23])
  );
  sky130_fd_sc_hd__xnor2_1 _456_ (
    .A(_081_),
    .B(_163_),
    .Y(pc_plus_imm[22])
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_082_),
    .B(_083_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__xnor2_1 _458_ (
    .A(_161_),
    .B(_183_),
    .Y(pc_plus_imm[21])
  );
  sky130_fd_sc_hd__xnor2_1 _459_ (
    .A(_085_),
    .B(_160_),
    .Y(pc_plus_imm[20])
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(_086_),
    .B(_087_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__xnor2_1 _461_ (
    .A(_158_),
    .B(_184_),
    .Y(pc_plus_imm[19])
  );
  sky130_fd_sc_hd__xor2_1 _462_ (
    .A(_090_),
    .B(_156_),
    .X(pc_plus_imm[18])
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(_091_),
    .B(_092_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__xnor2_1 _464_ (
    .A(_154_),
    .B(_185_),
    .Y(pc_plus_imm[17])
  );
  sky130_fd_sc_hd__xnor2_1 _465_ (
    .A(_095_),
    .B(_153_),
    .Y(pc_plus_imm[16])
  );
  sky130_fd_sc_hd__and2_0 _466_ (
    .A(_096_),
    .B(_097_),
    .X(_186_)
  );
  sky130_fd_sc_hd__xnor2_1 _467_ (
    .A(_151_),
    .B(_186_),
    .Y(pc_plus_imm[15])
  );
  sky130_fd_sc_hd__xnor2_1 _468_ (
    .A(_099_),
    .B(_150_),
    .Y(pc_plus_imm[14])
  );
  sky130_fd_sc_hd__nor2_1 _469_ (
    .A(_100_),
    .B(_101_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__xnor2_1 _470_ (
    .A(_148_),
    .B(_187_),
    .Y(pc_plus_imm[13])
  );
  sky130_fd_sc_hd__a21oi_1 _471_ (
    .A1(_107_),
    .A2(_146_),
    .B1(_104_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(_147_),
    .B(_188_),
    .Y(pc_plus_imm[12])
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(_106_),
    .B(_107_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xnor2_1 _474_ (
    .A(_145_),
    .B(_189_),
    .Y(pc_plus_imm[11])
  );
  sky130_fd_sc_hd__xnor2_1 _475_ (
    .A(_109_),
    .B(_144_),
    .Y(pc_plus_imm[10])
  );
  sky130_fd_sc_hd__nor2_1 _476_ (
    .A(_110_),
    .B(_111_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xnor2_1 _477_ (
    .A(_142_),
    .B(_190_),
    .Y(pc_plus_imm[9])
  );
  sky130_fd_sc_hd__a21oi_1 _478_ (
    .A1(_115_),
    .A2(_140_),
    .B1(_114_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _479_ (
    .A(_141_),
    .SLEEP(_191_),
    .X(pc_plus_imm[8])
  );
  sky130_fd_sc_hd__nand2_1 _480_ (
    .A(_115_),
    .B(_116_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__xnor2_1 _481_ (
    .A(_139_),
    .B(_192_),
    .Y(pc_plus_imm[7])
  );
  sky130_fd_sc_hd__xnor2_1 _482_ (
    .A(_118_),
    .B(_138_),
    .Y(pc_plus_imm[6])
  );
  sky130_fd_sc_hd__nor2_1 _483_ (
    .A(_119_),
    .B(_120_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__xnor2_1 _484_ (
    .A(_136_),
    .B(_193_),
    .Y(pc_plus_imm[5])
  );
  sky130_fd_sc_hd__xnor2_1 _485_ (
    .A(_123_),
    .B(_135_),
    .Y(pc_plus_imm[4])
  );
  sky130_fd_sc_hd__nand2_1 _486_ (
    .A(_124_),
    .B(_125_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__xor2_1 _487_ (
    .A(_133_),
    .B(_194_),
    .X(pc_plus_imm[3])
  );
  sky130_fd_sc_hd__xor2_1 _488_ (
    .A(_131_),
    .B(_132_),
    .X(pc_plus_imm[2])
  );
  sky130_fd_sc_hd__xor2_1 _489_ (
    .A(_128_),
    .B(_130_),
    .X(pc_plus_imm[1])
  );
  sky130_fd_sc_hd__nand3_1 _490_ (
    .A(pc[25]),
    .B(pc[26]),
    .C(_032_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _491_ (
    .A(pc[27]),
    .SLEEP(_195_),
    .X(_196_)
  );
  sky130_fd_sc_hd__nand3_1 _492_ (
    .A(pc[29]),
    .B(pc[28]),
    .C(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand4_1 _493_ (
    .A(pc[30]),
    .B(pc[29]),
    .C(pc[28]),
    .D(_196_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__xnor2_1 _494_ (
    .A(pc[30]),
    .B(_197_),
    .Y(pc_plus_4[30])
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(instr[14]),
    .B(instr[13]),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _496_ (
    .A1(instr[12]),
    .A2(ltu),
    .B1(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__o21ai_0 _497_ (
    .A1(instr[12]),
    .A2(ltu),
    .B1(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__mux2_1 _498_ (
    .A0(zero),
    .A1(lt),
    .S(instr[14]),
    .X(_202_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(instr[12]),
    .A2(_202_),
    .B1(instr[13]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__o21ai_0 _500_ (
    .A1(instr[12]),
    .A2(_202_),
    .B1(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a21oi_1 _501_ (
    .A1(_201_),
    .A2(_204_),
    .B1(_049_),
    .Y(br_taken)
  );
  sky130_fd_sc_hd__a21o_1 _502_ (
    .A1(instr[3]),
    .A2(wb_sel[1]),
    .B1(br_taken),
    .X(_205_)
  );
  sky130_fd_sc_hd__mux2_1 _503_ (
    .A0(pc_plus_4[30]),
    .A1(pc_plus_imm[30]),
    .S(_205_),
    .X(pc_next[30])
  );
  sky130_fd_sc_hd__a21oi_1 _504_ (
    .A1(pc[28]),
    .A2(_196_),
    .B1(pc[29]),
    .Y(_206_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _505_ (
    .A(_197_),
    .SLEEP(_206_),
    .X(pc_plus_4[29])
  );
  sky130_fd_sc_hd__mux2_1 _506_ (
    .A0(pc_plus_4[29]),
    .A1(pc_plus_imm[29]),
    .S(_205_),
    .X(pc_next[29])
  );
  sky130_fd_sc_hd__xor2_1 _507_ (
    .A(pc[28]),
    .B(_196_),
    .X(pc_plus_4[28])
  );
  sky130_fd_sc_hd__mux2_1 _508_ (
    .A0(pc_plus_4[28]),
    .A1(pc_plus_imm[28]),
    .S(_205_),
    .X(pc_next[28])
  );
  sky130_fd_sc_hd__xnor2_1 _509_ (
    .A(pc[27]),
    .B(_195_),
    .Y(pc_plus_4[27])
  );
  sky130_fd_sc_hd__mux2_1 _510_ (
    .A0(pc_plus_4[27]),
    .A1(pc_plus_imm[27]),
    .S(_205_),
    .X(pc_next[27])
  );
  sky130_fd_sc_hd__a21oi_1 _511_ (
    .A1(pc[25]),
    .A2(_032_),
    .B1(pc[26]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _512_ (
    .A(_195_),
    .SLEEP(_207_),
    .X(pc_plus_4[26])
  );
  sky130_fd_sc_hd__mux2_1 _513_ (
    .A0(pc_plus_4[26]),
    .A1(pc_plus_imm[26]),
    .S(_205_),
    .X(pc_next[26])
  );
  sky130_fd_sc_hd__mux2_1 _514_ (
    .A0(pc_plus_4[25]),
    .A1(pc_plus_imm[25]),
    .S(_205_),
    .X(pc_next[25])
  );
  sky130_fd_sc_hd__mux2_1 _515_ (
    .A0(pc_plus_4[24]),
    .A1(pc_plus_imm[24]),
    .S(_205_),
    .X(pc_next[24])
  );
  sky130_fd_sc_hd__mux2_1 _516_ (
    .A0(pc_plus_4[23]),
    .A1(pc_plus_imm[23]),
    .S(_205_),
    .X(pc_next[23])
  );
  sky130_fd_sc_hd__mux2_1 _517_ (
    .A0(pc_plus_4[22]),
    .A1(pc_plus_imm[22]),
    .S(_205_),
    .X(pc_next[22])
  );
  sky130_fd_sc_hd__mux2_1 _518_ (
    .A0(pc_plus_4[21]),
    .A1(pc_plus_imm[21]),
    .S(_205_),
    .X(pc_next[21])
  );
  sky130_fd_sc_hd__mux2_1 _519_ (
    .A0(pc_plus_4[20]),
    .A1(pc_plus_imm[20]),
    .S(_205_),
    .X(pc_next[20])
  );
  sky130_fd_sc_hd__mux2_1 _520_ (
    .A0(pc_plus_4[19]),
    .A1(pc_plus_imm[19]),
    .S(_205_),
    .X(pc_next[19])
  );
  sky130_fd_sc_hd__mux2_1 _521_ (
    .A0(pc_plus_4[18]),
    .A1(pc_plus_imm[18]),
    .S(_205_),
    .X(pc_next[18])
  );
  sky130_fd_sc_hd__mux2_1 _522_ (
    .A0(pc_plus_4[17]),
    .A1(pc_plus_imm[17]),
    .S(_205_),
    .X(pc_next[17])
  );
  sky130_fd_sc_hd__mux2_1 _523_ (
    .A0(pc_plus_4[16]),
    .A1(pc_plus_imm[16]),
    .S(_205_),
    .X(pc_next[16])
  );
  sky130_fd_sc_hd__mux2_1 _524_ (
    .A0(pc_plus_4[15]),
    .A1(pc_plus_imm[15]),
    .S(_205_),
    .X(pc_next[15])
  );
  sky130_fd_sc_hd__mux2_1 _525_ (
    .A0(pc_plus_4[14]),
    .A1(pc_plus_imm[14]),
    .S(_205_),
    .X(pc_next[14])
  );
  sky130_fd_sc_hd__mux2_1 _526_ (
    .A0(pc_plus_4[13]),
    .A1(pc_plus_imm[13]),
    .S(_205_),
    .X(pc_next[13])
  );
  sky130_fd_sc_hd__mux2_1 _527_ (
    .A0(pc_plus_4[12]),
    .A1(pc_plus_imm[12]),
    .S(_205_),
    .X(pc_next[12])
  );
  sky130_fd_sc_hd__mux2_1 _528_ (
    .A0(pc_plus_4[11]),
    .A1(pc_plus_imm[11]),
    .S(_205_),
    .X(pc_next[11])
  );
  sky130_fd_sc_hd__xor2_1 _529_ (
    .A(pc[10]),
    .B(_022_),
    .X(pc_plus_4[10])
  );
  sky130_fd_sc_hd__mux2_1 _530_ (
    .A0(pc_plus_4[10]),
    .A1(pc_plus_imm[10]),
    .S(_205_),
    .X(pc_next[10])
  );
  sky130_fd_sc_hd__xnor2_1 _531_ (
    .A(pc[9]),
    .B(_021_),
    .Y(pc_plus_4[9])
  );
  sky130_fd_sc_hd__mux2_1 _532_ (
    .A0(pc_plus_4[9]),
    .A1(pc_plus_imm[9]),
    .S(_205_),
    .X(pc_next[9])
  );
  sky130_fd_sc_hd__a21oi_1 _533_ (
    .A1(pc[7]),
    .A2(_020_),
    .B1(pc[8]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _534_ (
    .A(_021_),
    .SLEEP(_208_),
    .X(pc_plus_4[8])
  );
  sky130_fd_sc_hd__mux2_1 _535_ (
    .A0(pc_plus_4[8]),
    .A1(pc_plus_imm[8]),
    .S(_205_),
    .X(pc_next[8])
  );
  sky130_fd_sc_hd__xor2_1 _536_ (
    .A(pc[7]),
    .B(_020_),
    .X(pc_plus_4[7])
  );
  sky130_fd_sc_hd__mux2_1 _537_ (
    .A0(pc_plus_4[7]),
    .A1(pc_plus_imm[7]),
    .S(_205_),
    .X(pc_next[7])
  );
  sky130_fd_sc_hd__xnor2_1 _538_ (
    .A(pc[6]),
    .B(_019_),
    .Y(pc_plus_4[6])
  );
  sky130_fd_sc_hd__mux2_1 _539_ (
    .A0(pc_plus_4[6]),
    .A1(pc_plus_imm[6]),
    .S(_205_),
    .X(pc_next[6])
  );
  sky130_fd_sc_hd__xnor2_1 _540_ (
    .A(pc[5]),
    .B(_018_),
    .Y(pc_plus_4[5])
  );
  sky130_fd_sc_hd__mux2_1 _541_ (
    .A0(pc_plus_4[5]),
    .A1(pc_plus_imm[5]),
    .S(_205_),
    .X(pc_next[5])
  );
  sky130_fd_sc_hd__a21oi_1 _542_ (
    .A1(pc[2]),
    .A2(pc[3]),
    .B1(pc[4]),
    .Y(_209_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _543_ (
    .A(_018_),
    .SLEEP(_209_),
    .X(pc_plus_4[4])
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(pc_plus_4[4]),
    .A1(pc_plus_imm[4]),
    .S(_205_),
    .X(pc_next[4])
  );
  sky130_fd_sc_hd__xor2_1 _545_ (
    .A(pc[2]),
    .B(pc[3]),
    .X(pc_plus_4[3])
  );
  sky130_fd_sc_hd__mux2_1 _546_ (
    .A0(pc_plus_4[3]),
    .A1(pc_plus_imm[3]),
    .S(_205_),
    .X(pc_next[3])
  );
  sky130_fd_sc_hd__nand2_1 _547_ (
    .A(pc_plus_imm[2]),
    .B(_205_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o21ai_0 _548_ (
    .A1(pc[2]),
    .A2(_205_),
    .B1(_210_),
    .Y(pc_next[2])
  );
  sky130_fd_sc_hd__nand2_1 _549_ (
    .A(pc_plus_imm[1]),
    .B(_205_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o21ai_0 _550_ (
    .A1(_002_),
    .A2(_205_),
    .B1(_211_),
    .Y(pc_next[1])
  );
  sky130_fd_sc_hd__xor2_1 _551_ (
    .A(pc[0]),
    .B(imm[0]),
    .X(pc_plus_imm[0])
  );
  sky130_fd_sc_hd__and3_1 _552_ (
    .A(instr[14]),
    .B(_010_),
    .C(_045_),
    .X(alu_op[2])
  );
  sky130_fd_sc_hd__and3_1 _553_ (
    .A(instr[13]),
    .B(_010_),
    .C(_045_),
    .X(alu_op[1])
  );
  sky130_fd_sc_hd__and3_1 _554_ (
    .A(instr[12]),
    .B(_010_),
    .C(_045_),
    .X(alu_op[0])
  );
  sky130_fd_sc_hd__nor3_1 _555_ (
    .A(instr[5]),
    .B(instr[6]),
    .C(_046_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nor4_1 _556_ (
    .A(instr[5]),
    .B(instr[4]),
    .C(instr[6]),
    .D(_046_),
    .Y(mem_re)
  );
  sky130_fd_sc_hd__xnor2_1 _557_ (
    .A(pc[31]),
    .B(_198_),
    .Y(pc_plus_4[31])
  );
  sky130_fd_sc_hd__nand2_1 _558_ (
    .A(instr[5]),
    .B(instr[30]),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor3_1 _559_ (
    .A(_011_),
    .B(_046_),
    .C(_213_),
    .Y(alu_op[3])
  );
  sky130_fd_sc_hd__nor2_1 _560_ (
    .A(mem_we),
    .B(_212_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o21ai_0 _561_ (
    .A1(instr[3]),
    .A2(_008_),
    .B1(_214_),
    .Y(alu_src)
  );
  sky130_fd_sc_hd__o311ai_0 _562_ (
    .A1(instr[6]),
    .A2(_005_),
    .A3(_046_),
    .B1(_013_),
    .C1(_008_),
    .Y(reg_we)
  );
  sky130_fd_sc_hd__mux2_1 _563_ (
    .A0(pc_plus_4[31]),
    .A1(pc_plus_imm[31]),
    .S(_205_),
    .X(pc_next[31])
  );
  assign pc_plus_4[1:0] = pc[1:0];
  assign imm_j = { instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[19:12], instr[20], instr[30:21], 1'h0 };
  assign imm_u = { instr[31:12], 12'h000 };
  assign imm_b = { instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[7], instr[30:25], instr[11:8], 1'h0 };
  assign imm_s = { instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31:25], instr[11:7] };
  assign imm_i = { instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31], instr[31:20] };
  assign wb_sel[0] = mem_re;
  assign pc_next[0] = pc[0];
  assign imm[31] = instr[31];
endmodule
