/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module dmem_addr8(\byte_addr[0] , \byte_addr[1] , \byte_addr[2] , \byte_addr[3] , \byte_addr[4] , \byte_addr[5] , \byte_addr[6] , \byte_addr[7] , \byte_addr[8] , \byte_addr[9] , \byte_addr[10] , \byte_addr[11] , \byte_addr[12] , \byte_addr[13] , \byte_addr[14] , \byte_addr[15] , \byte_addr[16] , \byte_addr[17] , \byte_addr[18] , \byte_addr[19] , \byte_addr[20] 
, \byte_addr[21] , \byte_addr[22] , \byte_addr[23] , \byte_addr[24] , \byte_addr[25] , \byte_addr[26] , \byte_addr[27] , \byte_addr[28] , \byte_addr[29] , \byte_addr[30] , \byte_addr[31] , req, we_in, misaligned, out_of_range, trap, we_out, \word_index[0] , \word_index[1] , \word_index[2] );
  input \byte_addr[0] ;
  wire \byte_addr[0] ;
  input \byte_addr[1] ;
  wire \byte_addr[1] ;
  input \byte_addr[2] ;
  wire \byte_addr[2] ;
  input \byte_addr[3] ;
  wire \byte_addr[3] ;
  input \byte_addr[4] ;
  wire \byte_addr[4] ;
  input \byte_addr[5] ;
  wire \byte_addr[5] ;
  input \byte_addr[6] ;
  wire \byte_addr[6] ;
  input \byte_addr[7] ;
  wire \byte_addr[7] ;
  input \byte_addr[8] ;
  wire \byte_addr[8] ;
  input \byte_addr[9] ;
  wire \byte_addr[9] ;
  input \byte_addr[10] ;
  wire \byte_addr[10] ;
  input \byte_addr[11] ;
  wire \byte_addr[11] ;
  input \byte_addr[12] ;
  wire \byte_addr[12] ;
  input \byte_addr[13] ;
  wire \byte_addr[13] ;
  input \byte_addr[14] ;
  wire \byte_addr[14] ;
  input \byte_addr[15] ;
  wire \byte_addr[15] ;
  input \byte_addr[16] ;
  wire \byte_addr[16] ;
  input \byte_addr[17] ;
  wire \byte_addr[17] ;
  input \byte_addr[18] ;
  wire \byte_addr[18] ;
  input \byte_addr[19] ;
  wire \byte_addr[19] ;
  input \byte_addr[20] ;
  wire \byte_addr[20] ;
  input \byte_addr[21] ;
  wire \byte_addr[21] ;
  input \byte_addr[22] ;
  wire \byte_addr[22] ;
  input \byte_addr[23] ;
  wire \byte_addr[23] ;
  input \byte_addr[24] ;
  wire \byte_addr[24] ;
  input \byte_addr[25] ;
  wire \byte_addr[25] ;
  input \byte_addr[26] ;
  wire \byte_addr[26] ;
  input \byte_addr[27] ;
  wire \byte_addr[27] ;
  input \byte_addr[28] ;
  wire \byte_addr[28] ;
  input \byte_addr[29] ;
  wire \byte_addr[29] ;
  input \byte_addr[30] ;
  wire \byte_addr[30] ;
  input \byte_addr[31] ;
  wire \byte_addr[31] ;
  input req;
  wire req;
  input we_in;
  wire we_in;
  output misaligned;
  wire misaligned;
  output out_of_range;
  wire out_of_range;
  output trap;
  wire trap;
  output we_out;
  wire we_out;
  output \word_index[0] ;
  wire \word_index[0] ;
  output \word_index[1] ;
  wire \word_index[1] ;
  output \word_index[2] ;
  wire \word_index[2] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _10_ (
    .A(\byte_addr[1] ),
    .SLEEP(\byte_addr[0] ),
    .X(misaligned)
  );
  sky130_fd_sc_hd__nor3_1 _11_ (
    .A(\byte_addr[21] ),
    .B(\byte_addr[22] ),
    .C(\byte_addr[19] ),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor4_1 _12_ (
    .A(\byte_addr[17] ),
    .B(\byte_addr[18] ),
    .C(\byte_addr[15] ),
    .D(\byte_addr[24] ),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4_1 _13_ (
    .A(\byte_addr[29] ),
    .B(\byte_addr[30] ),
    .C(\byte_addr[27] ),
    .D(\byte_addr[20] ),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand3_1 _14_ (
    .A(_00_),
    .B(_01_),
    .C(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor4_1 _15_ (
    .A(\byte_addr[9] ),
    .B(\byte_addr[10] ),
    .C(\byte_addr[7] ),
    .D(\byte_addr[16] ),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor4_1 _16_ (
    .A(\byte_addr[8] ),
    .B(\byte_addr[5] ),
    .C(\byte_addr[6] ),
    .D(\byte_addr[12] ),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor4_1 _17_ (
    .A(\byte_addr[25] ),
    .B(\byte_addr[26] ),
    .C(\byte_addr[23] ),
    .D(\byte_addr[31] ),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor4_1 _18_ (
    .A(\byte_addr[13] ),
    .B(\byte_addr[14] ),
    .C(\byte_addr[11] ),
    .D(\byte_addr[28] ),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand4_1 _19_ (
    .A(_04_),
    .B(_05_),
    .C(_06_),
    .D(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _20_ (
    .A(_03_),
    .SLEEP(_08_),
    .X(out_of_range)
  );
  sky130_fd_sc_hd__nand2_1 _21_ (
    .A(we_in),
    .B(req),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor4_1 _22_ (
    .A(misaligned),
    .B(_03_),
    .C(_08_),
    .D(_09_),
    .Y(we_out)
  );
  sky130_fd_sc_hd__o31a_1 _23_ (
    .A1(misaligned),
    .A2(_03_),
    .A3(_08_),
    .B1(req),
    .X(trap)
  );
  assign \word_index[0]  = \byte_addr[2] ;
  assign \word_index[2]  = \byte_addr[4] ;
  assign \word_index[1]  = \byte_addr[3] ;
endmodule
