/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module fetch32(clk, rst_n, br_taken, is_jal, is_jalr, imm, rs1, pc, imem_addr, misaligned);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input br_taken;
  wire br_taken;
  input is_jal;
  wire is_jal;
  input is_jalr;
  wire is_jalr;
  input [31:0] imm;
  wire [31:0] imm;
  input [31:0] rs1;
  wire [31:0] rs1;
  output [31:0] pc;
  wire [31:0] pc;
  output [31:0] imem_addr;
  wire [31:0] imem_addr;
  output misaligned;
  wire misaligned;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire [31:0] jalr_target;
  wire [31:0] pc_next;
  wire [31:0] pc_plus_4;
  wire [31:0] pc_plus_imm;
  sky130_fd_sc_hd__clkinv_1 _402_ (
    .A(imem_addr[2]),
    .Y(pc_plus_4[2])
  );
  sky130_fd_sc_hd__clkinv_1 _403_ (
    .A(is_jalr),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _404_ (
    .A(rst_n),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _405_ (
    .A(is_jal),
    .B(br_taken),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(is_jalr),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o21ai_0 _407_ (
    .A1(is_jal),
    .A2(br_taken),
    .B1(_032_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(imm[0]),
    .B(pc[0]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(pc[1]),
    .B(imm[1]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(pc[1]),
    .B(imm[1]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _411_ (
    .A(_038_),
    .SLEEP(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _412_ (
    .A(_037_),
    .B(_040_),
    .Y(pc_plus_imm[1])
  );
  sky130_fd_sc_hd__nand2_1 _413_ (
    .A(imm[0]),
    .B(rs1[0]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _414_ (
    .A(imm[1]),
    .B(rs1[1]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _415_ (
    .A(imm[1]),
    .B(rs1[1]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _416_ (
    .A(_042_),
    .SLEEP(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _417_ (
    .A(_041_),
    .B(_044_),
    .Y(jalr_target[1])
  );
  sky130_fd_sc_hd__a22o_1 _418_ (
    .A1(_035_),
    .A2(pc_plus_imm[1]),
    .B1(jalr_target[1]),
    .B2(is_jalr),
    .X(pc_next[1])
  );
  sky130_fd_sc_hd__and2_0 _419_ (
    .A(imm[30]),
    .B(rs1[30]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _420_ (
    .A(imm[30]),
    .B(rs1[30]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _421_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _422_ (
    .A(imm[29]),
    .B(rs1[29]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _423_ (
    .A(imm[29]),
    .SLEEP(rs1[29]),
    .X(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _424_ (
    .A(imm[28]),
    .B(rs1[28]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _425_ (
    .A(imm[28]),
    .B(rs1[28]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and2_0 _426_ (
    .A(imm[27]),
    .B(rs1[27]),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(imm[27]),
    .B(rs1[27]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__and2_0 _428_ (
    .A(imm[26]),
    .B(rs1[26]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(imm[26]),
    .B(rs1[26]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _430_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _431_ (
    .A(imm[25]),
    .B(rs1[25]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _432_ (
    .A(imm[25]),
    .SLEEP(rs1[25]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(imm[24]),
    .B(rs1[24]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _434_ (
    .A(imm[24]),
    .B(rs1[24]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _435_ (
    .A(_059_),
    .SLEEP(_060_),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2_0 _436_ (
    .A(imm[23]),
    .B(rs1[23]),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(imm[23]),
    .B(rs1[23]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__and2_0 _438_ (
    .A(imm[22]),
    .B(rs1[22]),
    .X(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _439_ (
    .A(imm[22]),
    .B(rs1[22]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _440_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(imm[21]),
    .B(rs1[21]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _442_ (
    .A(imm[21]),
    .SLEEP(rs1[21]),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(imm[20]),
    .B(rs1[20]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__xnor2_1 _444_ (
    .A(imm[20]),
    .B(rs1[20]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__and2_0 _445_ (
    .A(imm[19]),
    .B(rs1[19]),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _446_ (
    .A(imm[19]),
    .B(rs1[19]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__and2_0 _447_ (
    .A(imm[18]),
    .B(rs1[18]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _448_ (
    .A(imm[18]),
    .B(rs1[18]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(imm[17]),
    .B(rs1[17]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _451_ (
    .A(imm[17]),
    .SLEEP(rs1[17]),
    .X(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(imm[16]),
    .B(rs1[16]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _453_ (
    .A(imm[16]),
    .B(rs1[16]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__and2_0 _454_ (
    .A(imm[15]),
    .B(rs1[15]),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(imm[15]),
    .B(rs1[15]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__and2_0 _456_ (
    .A(imm[14]),
    .B(rs1[14]),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(imm[14]),
    .B(rs1[14]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _458_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _459_ (
    .A(imm[13]),
    .B(rs1[13]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _460_ (
    .A(imm[13]),
    .SLEEP(rs1[13]),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _461_ (
    .A(imm[12]),
    .B(rs1[12]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__xnor2_1 _462_ (
    .A(imm[12]),
    .B(rs1[12]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__and2_0 _463_ (
    .A(imm[11]),
    .B(rs1[11]),
    .X(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(imm[11]),
    .B(rs1[11]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__and2_0 _465_ (
    .A(imm[10]),
    .B(rs1[10]),
    .X(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(imm[10]),
    .B(rs1[10]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(imm[9]),
    .B(rs1[9]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _469_ (
    .A(imm[9]),
    .SLEEP(rs1[9]),
    .X(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(imm[8]),
    .B(rs1[8]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _471_ (
    .A(imm[8]),
    .B(rs1[8]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and2_0 _472_ (
    .A(imm[7]),
    .B(rs1[7]),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor2_1 _473_ (
    .A(imm[7]),
    .B(rs1[7]),
    .Y(_099_)
  );
  sky130_fd_sc_hd__and2_0 _474_ (
    .A(imm[6]),
    .B(rs1[6]),
    .X(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _475_ (
    .A(imm[6]),
    .B(rs1[6]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor2_1 _476_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(imm[5]),
    .B(rs1[5]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _478_ (
    .A(imm[5]),
    .SLEEP(rs1[5]),
    .X(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _479_ (
    .A(imm[4]),
    .B(rs1[4]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xnor2_1 _480_ (
    .A(imm[4]),
    .B(rs1[4]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__and2_0 _481_ (
    .A(imm[3]),
    .B(rs1[3]),
    .X(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _482_ (
    .A(imm[3]),
    .B(rs1[3]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__and2_0 _483_ (
    .A(imm[2]),
    .B(rs1[2]),
    .X(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _484_ (
    .A1(_041_),
    .A2(_043_),
    .B1(_042_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _485_ (
    .A(imm[2]),
    .B(rs1[2]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _486_ (
    .A(_109_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21o_1 _487_ (
    .A1(_110_),
    .A2(_112_),
    .B1(_109_),
    .X(_113_)
  );
  sky130_fd_sc_hd__a211oi_1 _488_ (
    .A1(_110_),
    .A2(_112_),
    .B1(_107_),
    .C1(_109_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _489_ (
    .A(_108_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o31ai_1 _490_ (
    .A1(_106_),
    .A2(_108_),
    .A3(_114_),
    .B1(_105_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o311ai_0 _491_ (
    .A1(_106_),
    .A2(_108_),
    .A3(_114_),
    .B1(_105_),
    .C1(_103_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__and2_0 _492_ (
    .A(_104_),
    .B(_117_),
    .X(_118_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(_102_),
    .A2(_118_),
    .B1(_100_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a311oi_1 _494_ (
    .A1(_102_),
    .A2(_104_),
    .A3(_117_),
    .B1(_100_),
    .C1(_098_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_1 _495_ (
    .A(_099_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o31ai_1 _496_ (
    .A1(_097_),
    .A2(_099_),
    .A3(_120_),
    .B1(_096_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__o311ai_0 _497_ (
    .A1(_097_),
    .A2(_099_),
    .A3(_120_),
    .B1(_096_),
    .C1(_094_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__and2_0 _498_ (
    .A(_095_),
    .B(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__a21oi_1 _499_ (
    .A1(_093_),
    .A2(_124_),
    .B1(_091_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a311oi_1 _500_ (
    .A1(_093_),
    .A2(_095_),
    .A3(_123_),
    .B1(_091_),
    .C1(_089_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(_090_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o31ai_1 _502_ (
    .A1(_088_),
    .A2(_090_),
    .A3(_126_),
    .B1(_087_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__o311ai_0 _503_ (
    .A1(_088_),
    .A2(_090_),
    .A3(_126_),
    .B1(_087_),
    .C1(_085_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__and2_0 _504_ (
    .A(_086_),
    .B(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__a21o_1 _505_ (
    .A1(_084_),
    .A2(_130_),
    .B1(_082_),
    .X(_131_)
  );
  sky130_fd_sc_hd__a311oi_1 _506_ (
    .A1(_084_),
    .A2(_086_),
    .A3(_129_),
    .B1(_082_),
    .C1(_080_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _507_ (
    .A(_081_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o31ai_1 _508_ (
    .A1(_079_),
    .A2(_081_),
    .A3(_132_),
    .B1(_078_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o311ai_0 _509_ (
    .A1(_079_),
    .A2(_081_),
    .A3(_132_),
    .B1(_078_),
    .C1(_076_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__and2_0 _510_ (
    .A(_077_),
    .B(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd__a21oi_1 _511_ (
    .A1(_075_),
    .A2(_136_),
    .B1(_073_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a311oi_1 _512_ (
    .A1(_075_),
    .A2(_077_),
    .A3(_135_),
    .B1(_073_),
    .C1(_071_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _513_ (
    .A(_072_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o31ai_1 _514_ (
    .A1(_070_),
    .A2(_072_),
    .A3(_138_),
    .B1(_069_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o311ai_0 _515_ (
    .A1(_070_),
    .A2(_072_),
    .A3(_138_),
    .B1(_069_),
    .C1(_067_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__and2_0 _516_ (
    .A(_068_),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _517_ (
    .A1(_066_),
    .A2(_142_),
    .B1(_064_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a311oi_1 _518_ (
    .A1(_066_),
    .A2(_068_),
    .A3(_141_),
    .B1(_064_),
    .C1(_062_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _519_ (
    .A(_063_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2_1 _520_ (
    .A(_061_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _521_ (
    .A(_059_),
    .B(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o311ai_0 _522_ (
    .A1(_060_),
    .A2(_063_),
    .A3(_144_),
    .B1(_059_),
    .C1(_057_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__and2_0 _523_ (
    .A(_058_),
    .B(_148_),
    .X(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _524_ (
    .A1(_056_),
    .A2(_149_),
    .B1(_054_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a311oi_1 _525_ (
    .A1(_056_),
    .A2(_058_),
    .A3(_148_),
    .B1(_054_),
    .C1(_052_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor3_1 _526_ (
    .A(_051_),
    .B(_053_),
    .C(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__o31ai_1 _527_ (
    .A1(_051_),
    .A2(_053_),
    .A3(_151_),
    .B1(_050_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o311ai_0 _528_ (
    .A1(_051_),
    .A2(_053_),
    .A3(_151_),
    .B1(_050_),
    .C1(_048_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nand3_1 _529_ (
    .A(_047_),
    .B(_049_),
    .C(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a31oi_1 _530_ (
    .A1(_047_),
    .A2(_049_),
    .A3(_154_),
    .B1(_045_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _531_ (
    .A(imm[31]),
    .B(rs1[31]),
    .X(_157_)
  );
  sky130_fd_sc_hd__xnor2_1 _532_ (
    .A(_156_),
    .B(_157_),
    .Y(jalr_target[31])
  );
  sky130_fd_sc_hd__a21o_1 _533_ (
    .A1(_049_),
    .A2(_154_),
    .B1(_047_),
    .X(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _534_ (
    .A(_155_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__clkinv_1 _535_ (
    .A(_159_),
    .Y(jalr_target[30])
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(_048_),
    .B(_049_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__xnor2_1 _537_ (
    .A(_153_),
    .B(_160_),
    .Y(jalr_target[29])
  );
  sky130_fd_sc_hd__o21ai_0 _538_ (
    .A1(_053_),
    .A2(_151_),
    .B1(_051_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2b_1 _539_ (
    .A_N(_152_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__clkinv_1 _540_ (
    .A(_162_),
    .Y(jalr_target[28])
  );
  sky130_fd_sc_hd__nor2_1 _541_ (
    .A(_052_),
    .B(_053_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__xnor2_1 _542_ (
    .A(_150_),
    .B(_163_),
    .Y(jalr_target[27])
  );
  sky130_fd_sc_hd__xnor2_1 _543_ (
    .A(_056_),
    .B(_149_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _544_ (
    .A(_164_),
    .Y(jalr_target[26])
  );
  sky130_fd_sc_hd__nand2_1 _545_ (
    .A(_057_),
    .B(_058_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__xnor2_1 _546_ (
    .A(_147_),
    .B(_165_),
    .Y(jalr_target[25])
  );
  sky130_fd_sc_hd__xnor2_1 _547_ (
    .A(_061_),
    .B(_145_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__clkinv_1 _548_ (
    .A(_166_),
    .Y(jalr_target[24])
  );
  sky130_fd_sc_hd__nor2_1 _549_ (
    .A(_062_),
    .B(_063_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__xnor2_1 _550_ (
    .A(_143_),
    .B(_167_),
    .Y(jalr_target[23])
  );
  sky130_fd_sc_hd__xnor2_1 _551_ (
    .A(_066_),
    .B(_142_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__clkinv_1 _552_ (
    .A(_168_),
    .Y(jalr_target[22])
  );
  sky130_fd_sc_hd__nand2_1 _553_ (
    .A(_067_),
    .B(_068_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__xnor2_1 _554_ (
    .A(_140_),
    .B(_169_),
    .Y(jalr_target[21])
  );
  sky130_fd_sc_hd__xnor2_1 _555_ (
    .A(_070_),
    .B(_139_),
    .Y(jalr_target[20])
  );
  sky130_fd_sc_hd__nor2_1 _556_ (
    .A(_071_),
    .B(_072_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__xnor2_1 _557_ (
    .A(_137_),
    .B(_170_),
    .Y(jalr_target[19])
  );
  sky130_fd_sc_hd__xnor2_1 _558_ (
    .A(_075_),
    .B(_136_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _559_ (
    .A(_171_),
    .Y(jalr_target[18])
  );
  sky130_fd_sc_hd__nand2_1 _560_ (
    .A(_076_),
    .B(_077_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xnor2_1 _561_ (
    .A(_134_),
    .B(_172_),
    .Y(jalr_target[17])
  );
  sky130_fd_sc_hd__xor2_1 _562_ (
    .A(_079_),
    .B(_133_),
    .X(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _563_ (
    .A(_173_),
    .Y(jalr_target[16])
  );
  sky130_fd_sc_hd__nor2_1 _564_ (
    .A(_080_),
    .B(_081_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__xor2_1 _565_ (
    .A(_131_),
    .B(_174_),
    .X(jalr_target[15])
  );
  sky130_fd_sc_hd__xnor2_1 _566_ (
    .A(_084_),
    .B(_130_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__clkinv_1 _567_ (
    .A(_175_),
    .Y(jalr_target[14])
  );
  sky130_fd_sc_hd__nand2_1 _568_ (
    .A(_085_),
    .B(_086_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__xnor2_1 _569_ (
    .A(_128_),
    .B(_176_),
    .Y(jalr_target[13])
  );
  sky130_fd_sc_hd__xnor2_1 _570_ (
    .A(_088_),
    .B(_127_),
    .Y(jalr_target[12])
  );
  sky130_fd_sc_hd__nor2_1 _571_ (
    .A(_089_),
    .B(_090_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__xnor2_1 _572_ (
    .A(_125_),
    .B(_177_),
    .Y(jalr_target[11])
  );
  sky130_fd_sc_hd__xor2_1 _573_ (
    .A(_093_),
    .B(_124_),
    .X(jalr_target[10])
  );
  sky130_fd_sc_hd__nand2_1 _574_ (
    .A(_094_),
    .B(_095_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__xnor2_1 _575_ (
    .A(_122_),
    .B(_178_),
    .Y(jalr_target[9])
  );
  sky130_fd_sc_hd__xnor2_1 _576_ (
    .A(_097_),
    .B(_121_),
    .Y(jalr_target[8])
  );
  sky130_fd_sc_hd__nor2_1 _577_ (
    .A(_098_),
    .B(_099_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xnor2_1 _578_ (
    .A(_119_),
    .B(_179_),
    .Y(jalr_target[7])
  );
  sky130_fd_sc_hd__xor2_1 _579_ (
    .A(_102_),
    .B(_118_),
    .X(jalr_target[6])
  );
  sky130_fd_sc_hd__nand2_1 _580_ (
    .A(_103_),
    .B(_104_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__xnor2_1 _581_ (
    .A(_116_),
    .B(_180_),
    .Y(jalr_target[5])
  );
  sky130_fd_sc_hd__xnor2_1 _582_ (
    .A(_106_),
    .B(_115_),
    .Y(jalr_target[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _583_ (
    .A(_107_),
    .SLEEP(_108_),
    .X(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _584_ (
    .A(_113_),
    .B(_181_),
    .Y(jalr_target[3])
  );
  sky130_fd_sc_hd__xor2_1 _585_ (
    .A(_110_),
    .B(_112_),
    .X(jalr_target[2])
  );
  sky130_fd_sc_hd__nand2_1 _586_ (
    .A(imm[30]),
    .B(imem_addr[30]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xnor2_1 _587_ (
    .A(imm[30]),
    .B(imem_addr[30]),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nand2_1 _588_ (
    .A(imm[29]),
    .B(imem_addr[29]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _589_ (
    .A(imm[29]),
    .B(imem_addr[29]),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _590_ (
    .A(imm[28]),
    .B(imem_addr[28]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xnor2_1 _591_ (
    .A(imm[28]),
    .B(imem_addr[28]),
    .Y(_187_)
  );
  sky130_fd_sc_hd__and2_0 _592_ (
    .A(imm[27]),
    .B(imem_addr[27]),
    .X(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _593_ (
    .A(imm[27]),
    .B(imem_addr[27]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__and2_0 _594_ (
    .A(imm[26]),
    .B(imem_addr[26]),
    .X(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _595_ (
    .A(imm[26]),
    .B(imem_addr[26]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _596_ (
    .A(_190_),
    .B(_191_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _597_ (
    .A(imm[25]),
    .B(imem_addr[25]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _598_ (
    .A(imm[25]),
    .SLEEP(imem_addr[25]),
    .X(_194_)
  );
  sky130_fd_sc_hd__nand2_1 _599_ (
    .A(imm[24]),
    .B(imem_addr[24]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xnor2_1 _600_ (
    .A(imm[24]),
    .B(imem_addr[24]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _601_ (
    .A(imm[23]),
    .B(imem_addr[23]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__and2_0 _602_ (
    .A(imm[23]),
    .B(imem_addr[23]),
    .X(_198_)
  );
  sky130_fd_sc_hd__and2_0 _603_ (
    .A(imm[22]),
    .B(imem_addr[22]),
    .X(_199_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _604_ (
    .A(imm[22]),
    .SLEEP(imem_addr[22]),
    .X(_200_)
  );
  sky130_fd_sc_hd__nand2b_1 _605_ (
    .A_N(_199_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand2_1 _606_ (
    .A(imm[21]),
    .B(imem_addr[21]),
    .Y(_202_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _607_ (
    .A(imm[21]),
    .SLEEP(imem_addr[21]),
    .X(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _608_ (
    .A(imm[20]),
    .B(imem_addr[20]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(imm[20]),
    .B(imem_addr[20]),
    .Y(_205_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _610_ (
    .A(_204_),
    .SLEEP(_205_),
    .X(_206_)
  );
  sky130_fd_sc_hd__and2_0 _611_ (
    .A(imm[19]),
    .B(imem_addr[19]),
    .X(_207_)
  );
  sky130_fd_sc_hd__nor2_1 _612_ (
    .A(imm[19]),
    .B(imem_addr[19]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__and2_0 _613_ (
    .A(imm[18]),
    .B(imem_addr[18]),
    .X(_209_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _614_ (
    .A(imm[18]),
    .SLEEP(imem_addr[18]),
    .X(_210_)
  );
  sky130_fd_sc_hd__nand2b_1 _615_ (
    .A_N(_209_),
    .B(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand2_1 _616_ (
    .A(imm[17]),
    .B(imem_addr[17]),
    .Y(_212_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _617_ (
    .A(imm[17]),
    .SLEEP(imem_addr[17]),
    .X(_213_)
  );
  sky130_fd_sc_hd__nand2_1 _618_ (
    .A(imm[16]),
    .B(imem_addr[16]),
    .Y(_214_)
  );
  sky130_fd_sc_hd__xnor2_1 _619_ (
    .A(imm[16]),
    .B(imem_addr[16]),
    .Y(_215_)
  );
  sky130_fd_sc_hd__and2_0 _620_ (
    .A(imm[15]),
    .B(imem_addr[15]),
    .X(_216_)
  );
  sky130_fd_sc_hd__nor2_1 _621_ (
    .A(imm[15]),
    .B(imem_addr[15]),
    .Y(_217_)
  );
  sky130_fd_sc_hd__and2_0 _622_ (
    .A(imm[14]),
    .B(imem_addr[14]),
    .X(_218_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _623_ (
    .A(imm[14]),
    .SLEEP(imem_addr[14]),
    .X(_219_)
  );
  sky130_fd_sc_hd__nand2b_1 _624_ (
    .A_N(_218_),
    .B(_219_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _625_ (
    .A(imm[13]),
    .B(imem_addr[13]),
    .Y(_221_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _626_ (
    .A(imm[13]),
    .SLEEP(imem_addr[13]),
    .X(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _627_ (
    .A(imm[12]),
    .B(imem_addr[12]),
    .Y(_223_)
  );
  sky130_fd_sc_hd__xnor2_1 _628_ (
    .A(imm[12]),
    .B(imem_addr[12]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__and2_0 _629_ (
    .A(imm[11]),
    .B(imem_addr[11]),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor2_1 _630_ (
    .A(imm[11]),
    .B(imem_addr[11]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__and2_0 _631_ (
    .A(imm[10]),
    .B(imem_addr[10]),
    .X(_227_)
  );
  sky130_fd_sc_hd__nor2_1 _632_ (
    .A(imm[10]),
    .B(imem_addr[10]),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor2_1 _633_ (
    .A(_227_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2_1 _634_ (
    .A(imm[9]),
    .B(imem_addr[9]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _635_ (
    .A(imm[9]),
    .SLEEP(imem_addr[9]),
    .X(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _636_ (
    .A(imm[8]),
    .B(imem_addr[8]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xnor2_1 _637_ (
    .A(imm[8]),
    .B(imem_addr[8]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nand2_1 _638_ (
    .A(imm[7]),
    .B(imem_addr[7]),
    .Y(_234_)
  );
  sky130_fd_sc_hd__nor2_1 _639_ (
    .A(imm[7]),
    .B(imem_addr[7]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand2_1 _640_ (
    .A(imm[6]),
    .B(imem_addr[6]),
    .Y(_236_)
  );
  sky130_fd_sc_hd__xnor2_1 _641_ (
    .A(imm[6]),
    .B(imem_addr[6]),
    .Y(_237_)
  );
  sky130_fd_sc_hd__and2_0 _642_ (
    .A(imm[5]),
    .B(imem_addr[5]),
    .X(_238_)
  );
  sky130_fd_sc_hd__nor2_1 _643_ (
    .A(imm[5]),
    .B(imem_addr[5]),
    .Y(_239_)
  );
  sky130_fd_sc_hd__and2_0 _644_ (
    .A(imm[4]),
    .B(imem_addr[4]),
    .X(_240_)
  );
  sky130_fd_sc_hd__xnor2_1 _645_ (
    .A(imm[4]),
    .B(imem_addr[4]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__clkinv_1 _646_ (
    .A(_241_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nand2_1 _647_ (
    .A(imm[3]),
    .B(imem_addr[3]),
    .Y(_243_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _648_ (
    .A(imm[3]),
    .SLEEP(imem_addr[3]),
    .X(_244_)
  );
  sky130_fd_sc_hd__and2_0 _649_ (
    .A(imem_addr[2]),
    .B(imm[2]),
    .X(_245_)
  );
  sky130_fd_sc_hd__o21ai_0 _650_ (
    .A1(_037_),
    .A2(_039_),
    .B1(_038_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor2_1 _651_ (
    .A(imem_addr[2]),
    .B(imm[2]),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nor2_1 _652_ (
    .A(_245_),
    .B(_247_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__a21o_1 _653_ (
    .A1(_246_),
    .A2(_248_),
    .B1(_245_),
    .X(_249_)
  );
  sky130_fd_sc_hd__a221o_1 _654_ (
    .A1(imm[3]),
    .A2(imem_addr[3]),
    .B1(_246_),
    .B2(_248_),
    .C1(_245_),
    .X(_250_)
  );
  sky130_fd_sc_hd__and2_0 _655_ (
    .A(_244_),
    .B(_250_),
    .X(_251_)
  );
  sky130_fd_sc_hd__a21o_1 _656_ (
    .A1(_242_),
    .A2(_251_),
    .B1(_240_),
    .X(_252_)
  );
  sky130_fd_sc_hd__a311oi_1 _657_ (
    .A1(_242_),
    .A2(_244_),
    .A3(_250_),
    .B1(_240_),
    .C1(_238_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor2_1 _658_ (
    .A(_239_),
    .B(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__o31ai_1 _659_ (
    .A1(_237_),
    .A2(_239_),
    .A3(_253_),
    .B1(_236_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o311a_1 _660_ (
    .A1(_237_),
    .A2(_239_),
    .A3(_253_),
    .B1(_236_),
    .C1(_234_),
    .X(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _661_ (
    .A(_235_),
    .B(_256_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__o31ai_1 _662_ (
    .A1(_233_),
    .A2(_235_),
    .A3(_256_),
    .B1(_232_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__o311ai_0 _663_ (
    .A1(_233_),
    .A2(_235_),
    .A3(_256_),
    .B1(_232_),
    .C1(_230_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nand3_1 _664_ (
    .A(_229_),
    .B(_231_),
    .C(_259_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a31oi_1 _665_ (
    .A1(_229_),
    .A2(_231_),
    .A3(_259_),
    .B1(_227_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__a311oi_1 _666_ (
    .A1(_229_),
    .A2(_231_),
    .A3(_259_),
    .B1(_227_),
    .C1(_225_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _667_ (
    .A(_226_),
    .B(_262_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__o31ai_1 _668_ (
    .A1(_224_),
    .A2(_226_),
    .A3(_262_),
    .B1(_223_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__o311ai_0 _669_ (
    .A1(_224_),
    .A2(_226_),
    .A3(_262_),
    .B1(_223_),
    .C1(_221_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__and2_0 _670_ (
    .A(_222_),
    .B(_265_),
    .X(_266_)
  );
  sky130_fd_sc_hd__a21oi_1 _671_ (
    .A1(_219_),
    .A2(_266_),
    .B1(_218_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a311oi_1 _672_ (
    .A1(_219_),
    .A2(_222_),
    .A3(_265_),
    .B1(_218_),
    .C1(_216_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _673_ (
    .A(_217_),
    .B(_268_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__o31ai_1 _674_ (
    .A1(_215_),
    .A2(_217_),
    .A3(_268_),
    .B1(_214_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__o311ai_0 _675_ (
    .A1(_215_),
    .A2(_217_),
    .A3(_268_),
    .B1(_214_),
    .C1(_212_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__and2_0 _676_ (
    .A(_213_),
    .B(_271_),
    .X(_272_)
  );
  sky130_fd_sc_hd__a21oi_1 _677_ (
    .A1(_210_),
    .A2(_272_),
    .B1(_209_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__a311oi_1 _678_ (
    .A1(_210_),
    .A2(_213_),
    .A3(_271_),
    .B1(_209_),
    .C1(_207_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _679_ (
    .A(_208_),
    .SLEEP(_274_),
    .X(_275_)
  );
  sky130_fd_sc_hd__o21ai_0 _680_ (
    .A1(_205_),
    .A2(_275_),
    .B1(_204_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nand2_1 _681_ (
    .A(_203_),
    .B(_276_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__o311ai_0 _682_ (
    .A1(_205_),
    .A2(_208_),
    .A3(_274_),
    .B1(_204_),
    .C1(_202_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__a21oi_1 _683_ (
    .A1(_202_),
    .A2(_277_),
    .B1(_201_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nor2_1 _684_ (
    .A(_199_),
    .B(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__a311oi_1 _685_ (
    .A1(_200_),
    .A2(_203_),
    .A3(_278_),
    .B1(_199_),
    .C1(_198_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nor2_1 _686_ (
    .A(_197_),
    .B(_281_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__o31ai_1 _687_ (
    .A1(_196_),
    .A2(_197_),
    .A3(_281_),
    .B1(_195_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__o311ai_0 _688_ (
    .A1(_196_),
    .A2(_197_),
    .A3(_281_),
    .B1(_195_),
    .C1(_193_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__nand2_1 _689_ (
    .A(_194_),
    .B(_284_),
    .Y(_285_)
  );
  sky130_fd_sc_hd__a31oi_1 _690_ (
    .A1(_192_),
    .A2(_194_),
    .A3(_284_),
    .B1(_190_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__a311oi_1 _691_ (
    .A1(_192_),
    .A2(_194_),
    .A3(_284_),
    .B1(_190_),
    .C1(_188_),
    .Y(_287_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _692_ (
    .A(_189_),
    .SLEEP(_287_),
    .X(_288_)
  );
  sky130_fd_sc_hd__o21ai_0 _693_ (
    .A1(_187_),
    .A2(_288_),
    .B1(_186_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__o311a_1 _694_ (
    .A1(_187_),
    .A2(_189_),
    .A3(_287_),
    .B1(_186_),
    .C1(_184_),
    .X(_290_)
  );
  sky130_fd_sc_hd__nor3_1 _695_ (
    .A(_183_),
    .B(_185_),
    .C(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__o31a_1 _696_ (
    .A1(_183_),
    .A2(_185_),
    .A3(_290_),
    .B1(_182_),
    .X(_292_)
  );
  sky130_fd_sc_hd__xor2_1 _697_ (
    .A(imm[31]),
    .B(imem_addr[31]),
    .X(_293_)
  );
  sky130_fd_sc_hd__xnor2_1 _698_ (
    .A(_292_),
    .B(_293_),
    .Y(pc_plus_imm[31])
  );
  sky130_fd_sc_hd__o21ai_0 _699_ (
    .A1(_185_),
    .A2(_290_),
    .B1(_183_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nor2b_1 _700_ (
    .A(_291_),
    .B_N(_294_),
    .Y(pc_plus_imm[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _701_ (
    .A(_184_),
    .SLEEP(_185_),
    .X(_295_)
  );
  sky130_fd_sc_hd__xor2_1 _702_ (
    .A(_289_),
    .B(_295_),
    .X(pc_plus_imm[29])
  );
  sky130_fd_sc_hd__xor2_1 _703_ (
    .A(_187_),
    .B(_288_),
    .X(pc_plus_imm[28])
  );
  sky130_fd_sc_hd__nor2_1 _704_ (
    .A(_188_),
    .B(_189_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__xnor2_1 _705_ (
    .A(_286_),
    .B(_296_),
    .Y(pc_plus_imm[27])
  );
  sky130_fd_sc_hd__xnor2_1 _706_ (
    .A(_192_),
    .B(_285_),
    .Y(pc_plus_imm[26])
  );
  sky130_fd_sc_hd__nand2_1 _707_ (
    .A(_193_),
    .B(_194_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__xnor2_1 _708_ (
    .A(_283_),
    .B(_297_),
    .Y(pc_plus_imm[25])
  );
  sky130_fd_sc_hd__xnor2_1 _709_ (
    .A(_196_),
    .B(_282_),
    .Y(pc_plus_imm[24])
  );
  sky130_fd_sc_hd__nor2_1 _710_ (
    .A(_197_),
    .B(_198_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__xnor2_1 _711_ (
    .A(_280_),
    .B(_298_),
    .Y(pc_plus_imm[23])
  );
  sky130_fd_sc_hd__and3_1 _712_ (
    .A(_201_),
    .B(_202_),
    .C(_277_),
    .X(_299_)
  );
  sky130_fd_sc_hd__nor2_1 _713_ (
    .A(_279_),
    .B(_299_),
    .Y(pc_plus_imm[22])
  );
  sky130_fd_sc_hd__nand2_1 _714_ (
    .A(_202_),
    .B(_203_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__xnor2_1 _715_ (
    .A(_276_),
    .B(_300_),
    .Y(pc_plus_imm[21])
  );
  sky130_fd_sc_hd__xnor2_1 _716_ (
    .A(_206_),
    .B(_275_),
    .Y(pc_plus_imm[20])
  );
  sky130_fd_sc_hd__nor2_1 _717_ (
    .A(_207_),
    .B(_208_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__xnor2_1 _718_ (
    .A(_273_),
    .B(_301_),
    .Y(pc_plus_imm[19])
  );
  sky130_fd_sc_hd__xnor2_1 _719_ (
    .A(_211_),
    .B(_272_),
    .Y(pc_plus_imm[18])
  );
  sky130_fd_sc_hd__nand2_1 _720_ (
    .A(_212_),
    .B(_213_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__xnor2_1 _721_ (
    .A(_270_),
    .B(_302_),
    .Y(pc_plus_imm[17])
  );
  sky130_fd_sc_hd__xnor2_1 _722_ (
    .A(_215_),
    .B(_269_),
    .Y(pc_plus_imm[16])
  );
  sky130_fd_sc_hd__nor2_1 _723_ (
    .A(_216_),
    .B(_217_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__xnor2_1 _724_ (
    .A(_267_),
    .B(_303_),
    .Y(pc_plus_imm[15])
  );
  sky130_fd_sc_hd__xnor2_1 _725_ (
    .A(_220_),
    .B(_266_),
    .Y(pc_plus_imm[14])
  );
  sky130_fd_sc_hd__nand2_1 _726_ (
    .A(_221_),
    .B(_222_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__xnor2_1 _727_ (
    .A(_264_),
    .B(_304_),
    .Y(pc_plus_imm[13])
  );
  sky130_fd_sc_hd__xnor2_1 _728_ (
    .A(_224_),
    .B(_263_),
    .Y(pc_plus_imm[12])
  );
  sky130_fd_sc_hd__nor2_1 _729_ (
    .A(_225_),
    .B(_226_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__xnor2_1 _730_ (
    .A(_261_),
    .B(_305_),
    .Y(pc_plus_imm[11])
  );
  sky130_fd_sc_hd__a21oi_1 _731_ (
    .A1(_231_),
    .A2(_259_),
    .B1(_229_),
    .Y(_306_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _732_ (
    .A(_260_),
    .SLEEP(_306_),
    .X(pc_plus_imm[10])
  );
  sky130_fd_sc_hd__nand2_1 _733_ (
    .A(_230_),
    .B(_231_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__xnor2_1 _734_ (
    .A(_258_),
    .B(_307_),
    .Y(pc_plus_imm[9])
  );
  sky130_fd_sc_hd__xnor2_1 _735_ (
    .A(_233_),
    .B(_257_),
    .Y(pc_plus_imm[8])
  );
  sky130_fd_sc_hd__xnor2_1 _736_ (
    .A(imm[7]),
    .B(imem_addr[7]),
    .Y(_308_)
  );
  sky130_fd_sc_hd__xnor2_1 _737_ (
    .A(_255_),
    .B(_308_),
    .Y(pc_plus_imm[7])
  );
  sky130_fd_sc_hd__xnor2_1 _738_ (
    .A(_237_),
    .B(_254_),
    .Y(pc_plus_imm[6])
  );
  sky130_fd_sc_hd__nor2_1 _739_ (
    .A(_238_),
    .B(_239_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__xor2_1 _740_ (
    .A(_252_),
    .B(_309_),
    .X(pc_plus_imm[5])
  );
  sky130_fd_sc_hd__xnor2_1 _741_ (
    .A(_241_),
    .B(_251_),
    .Y(pc_plus_imm[4])
  );
  sky130_fd_sc_hd__nand2_1 _742_ (
    .A(_243_),
    .B(_244_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__xnor2_1 _743_ (
    .A(_249_),
    .B(_310_),
    .Y(pc_plus_imm[3])
  );
  sky130_fd_sc_hd__xnor2_1 _744_ (
    .A(_246_),
    .B(_248_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__clkinv_1 _745_ (
    .A(_311_),
    .Y(pc_plus_imm[2])
  );
  sky130_fd_sc_hd__xor2_1 _746_ (
    .A(imm[0]),
    .B(pc[0]),
    .X(pc_plus_imm[0])
  );
  sky130_fd_sc_hd__nand2_1 _747_ (
    .A(imem_addr[2]),
    .B(imem_addr[3]),
    .Y(_312_)
  );
  sky130_fd_sc_hd__and4_1 _748_ (
    .A(imem_addr[2]),
    .B(imem_addr[5]),
    .C(imem_addr[4]),
    .D(imem_addr[3]),
    .X(_313_)
  );
  sky130_fd_sc_hd__nand3_1 _749_ (
    .A(imem_addr[7]),
    .B(imem_addr[6]),
    .C(_313_),
    .Y(_314_)
  );
  sky130_fd_sc_hd__nand4_1 _750_ (
    .A(imem_addr[8]),
    .B(imem_addr[7]),
    .C(imem_addr[6]),
    .D(_313_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _751_ (
    .A(imem_addr[9]),
    .SLEEP(_315_),
    .X(_316_)
  );
  sky130_fd_sc_hd__nand2_1 _752_ (
    .A(imem_addr[10]),
    .B(_316_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__nand3_1 _753_ (
    .A(imem_addr[11]),
    .B(imem_addr[10]),
    .C(_316_),
    .Y(_318_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _754_ (
    .A(imem_addr[12]),
    .SLEEP(_318_),
    .X(_319_)
  );
  sky130_fd_sc_hd__nand3_1 _755_ (
    .A(imem_addr[14]),
    .B(imem_addr[13]),
    .C(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _756_ (
    .A(imem_addr[15]),
    .SLEEP(_320_),
    .X(_321_)
  );
  sky130_fd_sc_hd__nand3_1 _757_ (
    .A(imem_addr[17]),
    .B(imem_addr[16]),
    .C(_321_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _758_ (
    .A(imem_addr[18]),
    .SLEEP(_322_),
    .X(_323_)
  );
  sky130_fd_sc_hd__nand3_1 _759_ (
    .A(imem_addr[20]),
    .B(imem_addr[19]),
    .C(_323_),
    .Y(_324_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _760_ (
    .A(imem_addr[21]),
    .SLEEP(_324_),
    .X(_325_)
  );
  sky130_fd_sc_hd__nand3_1 _761_ (
    .A(imem_addr[23]),
    .B(imem_addr[22]),
    .C(_325_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _762_ (
    .A(imem_addr[24]),
    .SLEEP(_326_),
    .X(_327_)
  );
  sky130_fd_sc_hd__nand3_1 _763_ (
    .A(imem_addr[26]),
    .B(imem_addr[25]),
    .C(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _764_ (
    .A(imem_addr[27]),
    .SLEEP(_328_),
    .X(_329_)
  );
  sky130_fd_sc_hd__nand3_1 _765_ (
    .A(imem_addr[29]),
    .B(imem_addr[28]),
    .C(_329_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__nand4_1 _766_ (
    .A(imem_addr[30]),
    .B(imem_addr[29]),
    .C(imem_addr[28]),
    .D(_329_),
    .Y(_331_)
  );
  sky130_fd_sc_hd__xor2_1 _767_ (
    .A(imem_addr[31]),
    .B(_331_),
    .X(_332_)
  );
  sky130_fd_sc_hd__clkinv_1 _768_ (
    .A(_332_),
    .Y(pc_plus_4[31])
  );
  sky130_fd_sc_hd__xnor2_1 _769_ (
    .A(imem_addr[30]),
    .B(_330_),
    .Y(pc_plus_4[30])
  );
  sky130_fd_sc_hd__a21oi_1 _770_ (
    .A1(imem_addr[28]),
    .A2(_329_),
    .B1(imem_addr[29]),
    .Y(_333_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _771_ (
    .A(_330_),
    .SLEEP(_333_),
    .X(pc_plus_4[29])
  );
  sky130_fd_sc_hd__xor2_1 _772_ (
    .A(imem_addr[28]),
    .B(_329_),
    .X(pc_plus_4[28])
  );
  sky130_fd_sc_hd__xnor2_1 _773_ (
    .A(imem_addr[27]),
    .B(_328_),
    .Y(pc_plus_4[27])
  );
  sky130_fd_sc_hd__a21oi_1 _774_ (
    .A1(imem_addr[25]),
    .A2(_327_),
    .B1(imem_addr[26]),
    .Y(_334_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _775_ (
    .A(_328_),
    .SLEEP(_334_),
    .X(pc_plus_4[26])
  );
  sky130_fd_sc_hd__xor2_1 _776_ (
    .A(imem_addr[25]),
    .B(_327_),
    .X(pc_plus_4[25])
  );
  sky130_fd_sc_hd__xnor2_1 _777_ (
    .A(imem_addr[24]),
    .B(_326_),
    .Y(pc_plus_4[24])
  );
  sky130_fd_sc_hd__a21oi_1 _778_ (
    .A1(imem_addr[22]),
    .A2(_325_),
    .B1(imem_addr[23]),
    .Y(_335_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _779_ (
    .A(_326_),
    .SLEEP(_335_),
    .X(pc_plus_4[23])
  );
  sky130_fd_sc_hd__xor2_1 _780_ (
    .A(imem_addr[22]),
    .B(_325_),
    .X(pc_plus_4[22])
  );
  sky130_fd_sc_hd__xnor2_1 _781_ (
    .A(imem_addr[21]),
    .B(_324_),
    .Y(pc_plus_4[21])
  );
  sky130_fd_sc_hd__a21oi_1 _782_ (
    .A1(imem_addr[19]),
    .A2(_323_),
    .B1(imem_addr[20]),
    .Y(_336_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _783_ (
    .A(_324_),
    .SLEEP(_336_),
    .X(pc_plus_4[20])
  );
  sky130_fd_sc_hd__xor2_1 _784_ (
    .A(imem_addr[19]),
    .B(_323_),
    .X(pc_plus_4[19])
  );
  sky130_fd_sc_hd__xnor2_1 _785_ (
    .A(imem_addr[18]),
    .B(_322_),
    .Y(pc_plus_4[18])
  );
  sky130_fd_sc_hd__a21oi_1 _786_ (
    .A1(imem_addr[16]),
    .A2(_321_),
    .B1(imem_addr[17]),
    .Y(_337_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _787_ (
    .A(_322_),
    .SLEEP(_337_),
    .X(pc_plus_4[17])
  );
  sky130_fd_sc_hd__xor2_1 _788_ (
    .A(imem_addr[16]),
    .B(_321_),
    .X(pc_plus_4[16])
  );
  sky130_fd_sc_hd__xnor2_1 _789_ (
    .A(imem_addr[15]),
    .B(_320_),
    .Y(pc_plus_4[15])
  );
  sky130_fd_sc_hd__a21oi_1 _790_ (
    .A1(imem_addr[13]),
    .A2(_319_),
    .B1(imem_addr[14]),
    .Y(_338_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _791_ (
    .A(_320_),
    .SLEEP(_338_),
    .X(pc_plus_4[14])
  );
  sky130_fd_sc_hd__xor2_1 _792_ (
    .A(imem_addr[13]),
    .B(_319_),
    .X(pc_plus_4[13])
  );
  sky130_fd_sc_hd__xnor2_1 _793_ (
    .A(imem_addr[12]),
    .B(_318_),
    .Y(pc_plus_4[12])
  );
  sky130_fd_sc_hd__xor2_1 _794_ (
    .A(imem_addr[11]),
    .B(_317_),
    .X(_339_)
  );
  sky130_fd_sc_hd__clkinv_1 _795_ (
    .A(_339_),
    .Y(pc_plus_4[11])
  );
  sky130_fd_sc_hd__xor2_1 _796_ (
    .A(imem_addr[10]),
    .B(_316_),
    .X(pc_plus_4[10])
  );
  sky130_fd_sc_hd__xnor2_1 _797_ (
    .A(imem_addr[9]),
    .B(_315_),
    .Y(pc_plus_4[9])
  );
  sky130_fd_sc_hd__xnor2_1 _798_ (
    .A(imem_addr[8]),
    .B(_314_),
    .Y(pc_plus_4[8])
  );
  sky130_fd_sc_hd__a21oi_1 _799_ (
    .A1(imem_addr[6]),
    .A2(_313_),
    .B1(imem_addr[7]),
    .Y(_340_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _800_ (
    .A(_314_),
    .SLEEP(_340_),
    .X(pc_plus_4[7])
  );
  sky130_fd_sc_hd__xor2_1 _801_ (
    .A(imem_addr[6]),
    .B(_313_),
    .X(pc_plus_4[6])
  );
  sky130_fd_sc_hd__a31oi_1 _802_ (
    .A1(imem_addr[2]),
    .A2(imem_addr[4]),
    .A3(imem_addr[3]),
    .B1(imem_addr[5]),
    .Y(_341_)
  );
  sky130_fd_sc_hd__nor2_1 _803_ (
    .A(_313_),
    .B(_341_),
    .Y(pc_plus_4[5])
  );
  sky130_fd_sc_hd__xnor2_1 _804_ (
    .A(imem_addr[4]),
    .B(_312_),
    .Y(pc_plus_4[4])
  );
  sky130_fd_sc_hd__xor2_1 _805_ (
    .A(imem_addr[2]),
    .B(imem_addr[3]),
    .X(pc_plus_4[3])
  );
  sky130_fd_sc_hd__nor2_1 _806_ (
    .A(_036_),
    .B(pc_plus_imm[30]),
    .Y(_342_)
  );
  sky130_fd_sc_hd__nor3_1 _807_ (
    .A(is_jalr),
    .B(is_jal),
    .C(br_taken),
    .Y(_343_)
  );
  sky130_fd_sc_hd__nand2_1 _808_ (
    .A(_032_),
    .B(_034_),
    .Y(_344_)
  );
  sky130_fd_sc_hd__nor2_1 _809_ (
    .A(pc_plus_4[30]),
    .B(_344_),
    .Y(_345_)
  );
  sky130_fd_sc_hd__a211oi_1 _810_ (
    .A1(is_jalr),
    .A2(_159_),
    .B1(_342_),
    .C1(_345_),
    .Y(pc_next[30])
  );
  sky130_fd_sc_hd__nor2_1 _811_ (
    .A(_036_),
    .B(pc_plus_imm[29]),
    .Y(_346_)
  );
  sky130_fd_sc_hd__o22ai_1 _812_ (
    .A1(_032_),
    .A2(jalr_target[29]),
    .B1(pc_plus_4[29]),
    .B2(_344_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__nor2_1 _813_ (
    .A(_346_),
    .B(_347_),
    .Y(pc_next[29])
  );
  sky130_fd_sc_hd__nor2_1 _814_ (
    .A(_036_),
    .B(pc_plus_imm[28]),
    .Y(_348_)
  );
  sky130_fd_sc_hd__o22ai_1 _815_ (
    .A1(_032_),
    .A2(jalr_target[28]),
    .B1(pc_plus_4[28]),
    .B2(_344_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__nor2_1 _816_ (
    .A(_348_),
    .B(_349_),
    .Y(pc_next[28])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _817_ (
    .A(_032_),
    .SLEEP(jalr_target[27]),
    .X(_350_)
  );
  sky130_fd_sc_hd__o221a_1 _818_ (
    .A1(_036_),
    .A2(pc_plus_imm[27]),
    .B1(pc_plus_4[27]),
    .B2(_344_),
    .C1(_350_),
    .X(pc_next[27])
  );
  sky130_fd_sc_hd__nor2_1 _819_ (
    .A(_036_),
    .B(pc_plus_imm[26]),
    .Y(_351_)
  );
  sky130_fd_sc_hd__a21oi_1 _820_ (
    .A1(is_jalr),
    .A2(_164_),
    .B1(_351_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__o21a_1 _821_ (
    .A1(pc_plus_4[26]),
    .A2(_344_),
    .B1(_352_),
    .X(pc_next[26])
  );
  sky130_fd_sc_hd__nor2_1 _822_ (
    .A(pc_plus_4[25]),
    .B(_344_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__o22ai_1 _823_ (
    .A1(_032_),
    .A2(jalr_target[25]),
    .B1(pc_plus_imm[25]),
    .B2(_036_),
    .Y(_354_)
  );
  sky130_fd_sc_hd__nor2_1 _824_ (
    .A(_353_),
    .B(_354_),
    .Y(pc_next[25])
  );
  sky130_fd_sc_hd__nor2_1 _825_ (
    .A(_036_),
    .B(pc_plus_imm[24]),
    .Y(_355_)
  );
  sky130_fd_sc_hd__o22ai_1 _826_ (
    .A1(_032_),
    .A2(jalr_target[24]),
    .B1(pc_plus_4[24]),
    .B2(_344_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__nor2_1 _827_ (
    .A(_355_),
    .B(_356_),
    .Y(pc_next[24])
  );
  sky130_fd_sc_hd__nor2_1 _828_ (
    .A(_032_),
    .B(jalr_target[23]),
    .Y(_357_)
  );
  sky130_fd_sc_hd__o22ai_1 _829_ (
    .A1(_036_),
    .A2(pc_plus_imm[23]),
    .B1(pc_plus_4[23]),
    .B2(_344_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__nor2_1 _830_ (
    .A(_357_),
    .B(_358_),
    .Y(pc_next[23])
  );
  sky130_fd_sc_hd__o21ai_0 _831_ (
    .A1(_279_),
    .A2(_299_),
    .B1(_035_),
    .Y(_359_)
  );
  sky130_fd_sc_hd__nand2_1 _832_ (
    .A(is_jalr),
    .B(_168_),
    .Y(_360_)
  );
  sky130_fd_sc_hd__o211a_1 _833_ (
    .A1(pc_plus_4[22]),
    .A2(_344_),
    .B1(_359_),
    .C1(_360_),
    .X(pc_next[22])
  );
  sky130_fd_sc_hd__o22ai_1 _834_ (
    .A1(_036_),
    .A2(pc_plus_imm[21]),
    .B1(pc_plus_4[21]),
    .B2(_344_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__o21ba_1 _835_ (
    .A1(_032_),
    .A2(jalr_target[21]),
    .B1_N(_361_),
    .X(pc_next[21])
  );
  sky130_fd_sc_hd__nor2_1 _836_ (
    .A(_032_),
    .B(jalr_target[20]),
    .Y(_362_)
  );
  sky130_fd_sc_hd__o22ai_1 _837_ (
    .A1(_036_),
    .A2(pc_plus_imm[20]),
    .B1(pc_plus_4[20]),
    .B2(_344_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__nor2_1 _838_ (
    .A(_362_),
    .B(_363_),
    .Y(pc_next[20])
  );
  sky130_fd_sc_hd__nor2_1 _839_ (
    .A(_032_),
    .B(jalr_target[19]),
    .Y(_364_)
  );
  sky130_fd_sc_hd__o22ai_1 _840_ (
    .A1(_036_),
    .A2(pc_plus_imm[19]),
    .B1(pc_plus_4[19]),
    .B2(_344_),
    .Y(_365_)
  );
  sky130_fd_sc_hd__nor2_1 _841_ (
    .A(_364_),
    .B(_365_),
    .Y(pc_next[19])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _842_ (
    .A(_036_),
    .SLEEP(pc_plus_imm[18]),
    .X(_366_)
  );
  sky130_fd_sc_hd__nand2_1 _843_ (
    .A(is_jalr),
    .B(_171_),
    .Y(_367_)
  );
  sky130_fd_sc_hd__o211a_1 _844_ (
    .A1(pc_plus_4[18]),
    .A2(_344_),
    .B1(_366_),
    .C1(_367_),
    .X(pc_next[18])
  );
  sky130_fd_sc_hd__nor2_1 _845_ (
    .A(_036_),
    .B(pc_plus_imm[17]),
    .Y(_368_)
  );
  sky130_fd_sc_hd__nor2_1 _846_ (
    .A(_032_),
    .B(jalr_target[17]),
    .Y(_369_)
  );
  sky130_fd_sc_hd__nor2_1 _847_ (
    .A(pc_plus_4[17]),
    .B(_344_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__nor3_1 _848_ (
    .A(_368_),
    .B(_369_),
    .C(_370_),
    .Y(pc_next[17])
  );
  sky130_fd_sc_hd__nor2_1 _849_ (
    .A(pc_plus_4[16]),
    .B(_344_),
    .Y(_371_)
  );
  sky130_fd_sc_hd__a21oi_1 _850_ (
    .A1(is_jalr),
    .A2(_173_),
    .B1(_371_),
    .Y(_372_)
  );
  sky130_fd_sc_hd__o21a_1 _851_ (
    .A1(_036_),
    .A2(pc_plus_imm[16]),
    .B1(_372_),
    .X(pc_next[16])
  );
  sky130_fd_sc_hd__o22ai_1 _852_ (
    .A1(_036_),
    .A2(pc_plus_imm[15]),
    .B1(pc_plus_4[15]),
    .B2(_344_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__o21ba_1 _853_ (
    .A1(_032_),
    .A2(jalr_target[15]),
    .B1_N(_373_),
    .X(pc_next[15])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _854_ (
    .A(_036_),
    .SLEEP(pc_plus_imm[14]),
    .X(_374_)
  );
  sky130_fd_sc_hd__nand2_1 _855_ (
    .A(is_jalr),
    .B(_175_),
    .Y(_375_)
  );
  sky130_fd_sc_hd__o211a_1 _856_ (
    .A1(pc_plus_4[14]),
    .A2(_344_),
    .B1(_374_),
    .C1(_375_),
    .X(pc_next[14])
  );
  sky130_fd_sc_hd__nor2_1 _857_ (
    .A(_036_),
    .B(pc_plus_imm[13]),
    .Y(_376_)
  );
  sky130_fd_sc_hd__nor2_1 _858_ (
    .A(_032_),
    .B(jalr_target[13]),
    .Y(_377_)
  );
  sky130_fd_sc_hd__nor2_1 _859_ (
    .A(pc_plus_4[13]),
    .B(_344_),
    .Y(_378_)
  );
  sky130_fd_sc_hd__nor3_1 _860_ (
    .A(_376_),
    .B(_377_),
    .C(_378_),
    .Y(pc_next[13])
  );
  sky130_fd_sc_hd__o22ai_1 _861_ (
    .A1(_032_),
    .A2(jalr_target[12]),
    .B1(pc_plus_imm[12]),
    .B2(_036_),
    .Y(_379_)
  );
  sky130_fd_sc_hd__o21ba_1 _862_ (
    .A1(pc_plus_4[12]),
    .A2(_344_),
    .B1_N(_379_),
    .X(pc_next[12])
  );
  sky130_fd_sc_hd__nor2_1 _863_ (
    .A(_036_),
    .B(pc_plus_imm[11]),
    .Y(_380_)
  );
  sky130_fd_sc_hd__nor2_1 _864_ (
    .A(_032_),
    .B(jalr_target[11]),
    .Y(_381_)
  );
  sky130_fd_sc_hd__a211oi_1 _865_ (
    .A1(_339_),
    .A2(_343_),
    .B1(_380_),
    .C1(_381_),
    .Y(pc_next[11])
  );
  sky130_fd_sc_hd__nor2_1 _866_ (
    .A(pc_plus_4[10]),
    .B(_344_),
    .Y(_382_)
  );
  sky130_fd_sc_hd__o22ai_1 _867_ (
    .A1(_032_),
    .A2(jalr_target[10]),
    .B1(pc_plus_imm[10]),
    .B2(_036_),
    .Y(_383_)
  );
  sky130_fd_sc_hd__nor2_1 _868_ (
    .A(_382_),
    .B(_383_),
    .Y(pc_next[10])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _869_ (
    .A(pc_plus_4[9]),
    .SLEEP(_344_),
    .X(_384_)
  );
  sky130_fd_sc_hd__o221a_1 _870_ (
    .A1(_032_),
    .A2(jalr_target[9]),
    .B1(pc_plus_imm[9]),
    .B2(_036_),
    .C1(_384_),
    .X(pc_next[9])
  );
  sky130_fd_sc_hd__nor2_1 _871_ (
    .A(pc_plus_4[8]),
    .B(_344_),
    .Y(_385_)
  );
  sky130_fd_sc_hd__o22ai_1 _872_ (
    .A1(_032_),
    .A2(jalr_target[8]),
    .B1(pc_plus_imm[8]),
    .B2(_036_),
    .Y(_386_)
  );
  sky130_fd_sc_hd__nor2_1 _873_ (
    .A(_385_),
    .B(_386_),
    .Y(pc_next[8])
  );
  sky130_fd_sc_hd__nor2_1 _874_ (
    .A(_032_),
    .B(jalr_target[7]),
    .Y(_387_)
  );
  sky130_fd_sc_hd__o22ai_1 _875_ (
    .A1(_036_),
    .A2(pc_plus_imm[7]),
    .B1(pc_plus_4[7]),
    .B2(_344_),
    .Y(_388_)
  );
  sky130_fd_sc_hd__nor2_1 _876_ (
    .A(_387_),
    .B(_388_),
    .Y(pc_next[7])
  );
  sky130_fd_sc_hd__nor2_1 _877_ (
    .A(pc_plus_4[6]),
    .B(_344_),
    .Y(_389_)
  );
  sky130_fd_sc_hd__o22ai_1 _878_ (
    .A1(_032_),
    .A2(jalr_target[6]),
    .B1(pc_plus_imm[6]),
    .B2(_036_),
    .Y(_390_)
  );
  sky130_fd_sc_hd__nor2_1 _879_ (
    .A(_389_),
    .B(_390_),
    .Y(pc_next[6])
  );
  sky130_fd_sc_hd__o21ai_0 _880_ (
    .A1(_313_),
    .A2(_341_),
    .B1(_034_),
    .Y(_391_)
  );
  sky130_fd_sc_hd__o211ai_1 _881_ (
    .A1(_034_),
    .A2(pc_plus_imm[5]),
    .B1(_391_),
    .C1(_032_),
    .Y(_392_)
  );
  sky130_fd_sc_hd__nand2_1 _882_ (
    .A(is_jalr),
    .B(jalr_target[5]),
    .Y(_393_)
  );
  sky130_fd_sc_hd__nand2_1 _883_ (
    .A(_392_),
    .B(_393_),
    .Y(pc_next[5])
  );
  sky130_fd_sc_hd__nor2_1 _884_ (
    .A(_032_),
    .B(jalr_target[4]),
    .Y(_394_)
  );
  sky130_fd_sc_hd__o22ai_1 _885_ (
    .A1(_036_),
    .A2(pc_plus_imm[4]),
    .B1(pc_plus_4[4]),
    .B2(_344_),
    .Y(_395_)
  );
  sky130_fd_sc_hd__nor2_1 _886_ (
    .A(_394_),
    .B(_395_),
    .Y(pc_next[4])
  );
  sky130_fd_sc_hd__nand2_1 _887_ (
    .A(is_jalr),
    .B(jalr_target[3]),
    .Y(_396_)
  );
  sky130_fd_sc_hd__a22oi_1 _888_ (
    .A1(_035_),
    .A2(pc_plus_imm[3]),
    .B1(pc_plus_4[3]),
    .B2(_343_),
    .Y(_397_)
  );
  sky130_fd_sc_hd__nand2_1 _889_ (
    .A(_396_),
    .B(_397_),
    .Y(pc_next[3])
  );
  sky130_fd_sc_hd__nand2_1 _890_ (
    .A(is_jalr),
    .B(jalr_target[2]),
    .Y(_398_)
  );
  sky130_fd_sc_hd__o221ai_1 _891_ (
    .A1(_036_),
    .A2(_311_),
    .B1(_344_),
    .B2(imem_addr[2]),
    .C1(_398_),
    .Y(pc_next[2])
  );
  sky130_fd_sc_hd__a22o_1 _892_ (
    .A1(_035_),
    .A2(pc_plus_imm[0]),
    .B1(_343_),
    .B2(pc[0]),
    .X(pc_next[0])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _893_ (
    .A(pc[1]),
    .SLEEP(pc[0]),
    .X(misaligned)
  );
  sky130_fd_sc_hd__nand2_1 _894_ (
    .A(pc_plus_4[31]),
    .B(_343_),
    .Y(_399_)
  );
  sky130_fd_sc_hd__a22oi_1 _895_ (
    .A1(is_jalr),
    .A2(jalr_target[31]),
    .B1(pc_plus_imm[31]),
    .B2(_035_),
    .Y(_400_)
  );
  sky130_fd_sc_hd__nand2_1 _896_ (
    .A(_399_),
    .B(_400_),
    .Y(pc_next[31])
  );
  sky130_fd_sc_hd__nor3_1 _897_ (
    .A(_033_),
    .B(_362_),
    .C(_363_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor3_1 _898_ (
    .A(_033_),
    .B(_364_),
    .C(_365_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and2_0 _899_ (
    .A(rst_n),
    .B(pc_next[18]),
    .X(_002_)
  );
  sky130_fd_sc_hd__nor4_1 _900_ (
    .A(_033_),
    .B(_368_),
    .C(_369_),
    .D(_370_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__and2_0 _901_ (
    .A(rst_n),
    .B(pc_next[16]),
    .X(_004_)
  );
  sky130_fd_sc_hd__and2_0 _902_ (
    .A(rst_n),
    .B(pc_next[15]),
    .X(_005_)
  );
  sky130_fd_sc_hd__and2_0 _903_ (
    .A(rst_n),
    .B(pc_next[14]),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor4_1 _904_ (
    .A(_033_),
    .B(_376_),
    .C(_377_),
    .D(_378_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__and2_0 _905_ (
    .A(rst_n),
    .B(pc_next[12]),
    .X(_008_)
  );
  sky130_fd_sc_hd__and2_0 _906_ (
    .A(rst_n),
    .B(pc_next[11]),
    .X(_009_)
  );
  sky130_fd_sc_hd__nor3_1 _907_ (
    .A(_033_),
    .B(_382_),
    .C(_383_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__and2_0 _908_ (
    .A(rst_n),
    .B(pc_next[9]),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor3_1 _909_ (
    .A(_033_),
    .B(_385_),
    .C(_386_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3_1 _910_ (
    .A(_033_),
    .B(_387_),
    .C(_388_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _911_ (
    .A(_033_),
    .B(_389_),
    .C(_390_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _912_ (
    .A1(_392_),
    .A2(_393_),
    .B1(_033_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _913_ (
    .A(_033_),
    .B(_394_),
    .C(_395_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _914_ (
    .A1(_396_),
    .A2(_397_),
    .B1(_033_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__and2_0 _915_ (
    .A(rst_n),
    .B(pc_next[2]),
    .X(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _916_ (
    .A1(_399_),
    .A2(_400_),
    .B1(_033_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a2111oi_0 _917_ (
    .A1(is_jalr),
    .A2(_159_),
    .B1(_342_),
    .C1(_345_),
    .D1(_033_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _918_ (
    .A(_033_),
    .B(_346_),
    .C(_347_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_1 _919_ (
    .A1(pc[1]),
    .A2(_343_),
    .B1(pc_next[1]),
    .Y(_401_)
  );
  sky130_fd_sc_hd__nor2_1 _920_ (
    .A(_033_),
    .B(_401_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _921_ (
    .A(_033_),
    .B(_348_),
    .C(_349_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__and2_0 _922_ (
    .A(rst_n),
    .B(pc_next[27]),
    .X(_024_)
  );
  sky130_fd_sc_hd__and2_0 _923_ (
    .A(rst_n),
    .B(pc_next[26]),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _924_ (
    .A(_033_),
    .B(_353_),
    .C(_354_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _925_ (
    .A(_033_),
    .B(_355_),
    .C(_356_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and2_0 _926_ (
    .A(rst_n),
    .B(pc_next[0]),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _927_ (
    .A(_033_),
    .B(_357_),
    .C(_358_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__and2_0 _928_ (
    .A(rst_n),
    .B(pc_next[22]),
    .X(_030_)
  );
  sky130_fd_sc_hd__and2_0 _929_ (
    .A(rst_n),
    .B(pc_next[21]),
    .X(_031_)
  );
  sky130_fd_sc_hd__dfxtp_1 _930_ (
    .CLK(clk),
    .D(_018_),
    .Q(imem_addr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _931_ (
    .CLK(clk),
    .D(_017_),
    .Q(imem_addr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _932_ (
    .CLK(clk),
    .D(_016_),
    .Q(imem_addr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _933_ (
    .CLK(clk),
    .D(_015_),
    .Q(imem_addr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _934_ (
    .CLK(clk),
    .D(_014_),
    .Q(imem_addr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _935_ (
    .CLK(clk),
    .D(_013_),
    .Q(imem_addr[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _936_ (
    .CLK(clk),
    .D(_012_),
    .Q(imem_addr[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _937_ (
    .CLK(clk),
    .D(_011_),
    .Q(imem_addr[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _938_ (
    .CLK(clk),
    .D(_010_),
    .Q(imem_addr[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _939_ (
    .CLK(clk),
    .D(_009_),
    .Q(imem_addr[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _940_ (
    .CLK(clk),
    .D(_008_),
    .Q(imem_addr[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _941_ (
    .CLK(clk),
    .D(_007_),
    .Q(imem_addr[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _942_ (
    .CLK(clk),
    .D(_006_),
    .Q(imem_addr[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _943_ (
    .CLK(clk),
    .D(_005_),
    .Q(imem_addr[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _944_ (
    .CLK(clk),
    .D(_004_),
    .Q(imem_addr[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _945_ (
    .CLK(clk),
    .D(_003_),
    .Q(imem_addr[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _946_ (
    .CLK(clk),
    .D(_002_),
    .Q(imem_addr[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _947_ (
    .CLK(clk),
    .D(_001_),
    .Q(imem_addr[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _948_ (
    .CLK(clk),
    .D(_000_),
    .Q(imem_addr[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _949_ (
    .CLK(clk),
    .D(_031_),
    .Q(imem_addr[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _950_ (
    .CLK(clk),
    .D(_030_),
    .Q(imem_addr[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _951_ (
    .CLK(clk),
    .D(_029_),
    .Q(imem_addr[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _952_ (
    .CLK(clk),
    .D(_027_),
    .Q(imem_addr[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _953_ (
    .CLK(clk),
    .D(_026_),
    .Q(imem_addr[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _954_ (
    .CLK(clk),
    .D(_025_),
    .Q(imem_addr[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _955_ (
    .CLK(clk),
    .D(_024_),
    .Q(imem_addr[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _956_ (
    .CLK(clk),
    .D(_023_),
    .Q(imem_addr[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _957_ (
    .CLK(clk),
    .D(_021_),
    .Q(imem_addr[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _958_ (
    .CLK(clk),
    .D(_020_),
    .Q(imem_addr[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _959_ (
    .CLK(clk),
    .D(_019_),
    .Q(imem_addr[31])
  );
  sky130_fd_sc_hd__dfxtp_1 _960_ (
    .CLK(clk),
    .D(_022_),
    .Q(pc[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _961_ (
    .CLK(clk),
    .D(_028_),
    .Q(pc[0])
  );
  assign jalr_target[0] = 1'h0;
  assign pc_plus_4[1:0] = pc[1:0];
  assign imem_addr[1:0] = 2'h0;
  assign pc[31:2] = imem_addr[31:2];
endmodule
