/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module mac_wshift(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i20
, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32, i33, o0, o1, o2, o3, o4, o5, o6, o7
, o8, o9, o10, o11, o12, o13, o14, o15, o16, o17, o18, o19, o20, o21, o22, o23, o24, o25, o26, o27, o28
, o29, o30, o31, o32, o33, o34, o35, o36, o37, o38, o39, o40, o41, o42, o43, o44, o45, o46, o47, o48, o49
, o50, o51, o52, o53, o54, o55, o56, o57, o58, o59, o60, o61, o62, o63);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input i4;
  wire i4;
  input i5;
  wire i5;
  input i6;
  wire i6;
  input i7;
  wire i7;
  input i8;
  wire i8;
  input i9;
  wire i9;
  input i10;
  wire i10;
  input i11;
  wire i11;
  input i12;
  wire i12;
  input i13;
  wire i13;
  input i14;
  wire i14;
  input i15;
  wire i15;
  input i16;
  wire i16;
  input i17;
  wire i17;
  input i18;
  wire i18;
  input i19;
  wire i19;
  input i20;
  wire i20;
  input i21;
  wire i21;
  input i22;
  wire i22;
  input i23;
  wire i23;
  input i24;
  wire i24;
  input i25;
  wire i25;
  input i26;
  wire i26;
  input i27;
  wire i27;
  input i28;
  wire i28;
  input i29;
  wire i29;
  input i30;
  wire i30;
  input i31;
  wire i31;
  input i32;
  wire i32;
  input i33;
  wire i33;
  output o0;
  wire o0;
  output o1;
  wire o1;
  output o2;
  wire o2;
  output o3;
  wire o3;
  output o4;
  wire o4;
  output o5;
  wire o5;
  output o6;
  wire o6;
  output o7;
  wire o7;
  output o8;
  wire o8;
  output o9;
  wire o9;
  output o10;
  wire o10;
  output o11;
  wire o11;
  output o12;
  wire o12;
  output o13;
  wire o13;
  output o14;
  wire o14;
  output o15;
  wire o15;
  output o16;
  wire o16;
  output o17;
  wire o17;
  output o18;
  wire o18;
  output o19;
  wire o19;
  output o20;
  wire o20;
  output o21;
  wire o21;
  output o22;
  wire o22;
  output o23;
  wire o23;
  output o24;
  wire o24;
  output o25;
  wire o25;
  output o26;
  wire o26;
  output o27;
  wire o27;
  output o28;
  wire o28;
  output o29;
  wire o29;
  output o30;
  wire o30;
  output o31;
  wire o31;
  output o32;
  wire o32;
  output o33;
  wire o33;
  output o34;
  wire o34;
  output o35;
  wire o35;
  output o36;
  wire o36;
  output o37;
  wire o37;
  output o38;
  wire o38;
  output o39;
  wire o39;
  output o40;
  wire o40;
  output o41;
  wire o41;
  output o42;
  wire o42;
  output o43;
  wire o43;
  output o44;
  wire o44;
  output o45;
  wire o45;
  output o46;
  wire o46;
  output o47;
  wire o47;
  output o48;
  wire o48;
  output o49;
  wire o49;
  output o50;
  wire o50;
  output o51;
  wire o51;
  output o52;
  wire o52;
  output o53;
  wire o53;
  output o54;
  wire o54;
  output o55;
  wire o55;
  output o56;
  wire o56;
  output o57;
  wire o57;
  output o58;
  wire o58;
  output o59;
  wire o59;
  output o60;
  wire o60;
  output o61;
  wire o61;
  output o62;
  wire o62;
  output o63;
  wire o63;
  sky130_fd_sc_hd__and2_1 g34 (
    .A(i1),
    .B(i0),
    .X(o32)
  );
  sky130_fd_sc_hd__and2_1 g35 (
    .A(i0),
    .B(i2),
    .X(o0)
  );
  sky130_fd_sc_hd__and2_1 g36 (
    .A(i0),
    .B(i3),
    .X(o1)
  );
  sky130_fd_sc_hd__and2_1 g37 (
    .A(i0),
    .B(i4),
    .X(o2)
  );
  sky130_fd_sc_hd__and2_1 g38 (
    .A(i0),
    .B(i5),
    .X(o3)
  );
  sky130_fd_sc_hd__and2_1 g39 (
    .A(i0),
    .B(i6),
    .X(o4)
  );
  sky130_fd_sc_hd__and2_1 g40 (
    .A(i0),
    .B(i7),
    .X(o5)
  );
  sky130_fd_sc_hd__and2_1 g41 (
    .A(i0),
    .B(i8),
    .X(o6)
  );
  sky130_fd_sc_hd__and2_1 g42 (
    .A(i0),
    .B(i9),
    .X(o7)
  );
  sky130_fd_sc_hd__and2_1 g43 (
    .A(i0),
    .B(i10),
    .X(o8)
  );
  sky130_fd_sc_hd__and2_1 g44 (
    .A(i0),
    .B(i11),
    .X(o9)
  );
  sky130_fd_sc_hd__and2_1 g45 (
    .A(i0),
    .B(i12),
    .X(o10)
  );
  sky130_fd_sc_hd__and2_1 g46 (
    .A(i0),
    .B(i13),
    .X(o11)
  );
  sky130_fd_sc_hd__and2_1 g47 (
    .A(i0),
    .B(i14),
    .X(o12)
  );
  sky130_fd_sc_hd__and2_1 g48 (
    .A(i0),
    .B(i15),
    .X(o13)
  );
  sky130_fd_sc_hd__and2_1 g49 (
    .A(i0),
    .B(i16),
    .X(o14)
  );
  sky130_fd_sc_hd__and2_1 g50 (
    .A(i0),
    .B(i17),
    .X(o15)
  );
  sky130_fd_sc_hd__and2_1 g51 (
    .A(i0),
    .B(i18),
    .X(o16)
  );
  sky130_fd_sc_hd__and2_1 g52 (
    .A(i0),
    .B(i19),
    .X(o17)
  );
  sky130_fd_sc_hd__and2_1 g53 (
    .A(i0),
    .B(i20),
    .X(o18)
  );
  sky130_fd_sc_hd__and2_1 g54 (
    .A(i0),
    .B(i21),
    .X(o19)
  );
  sky130_fd_sc_hd__and2_1 g55 (
    .A(i0),
    .B(i22),
    .X(o20)
  );
  sky130_fd_sc_hd__and2_1 g56 (
    .A(i0),
    .B(i23),
    .X(o21)
  );
  sky130_fd_sc_hd__and2_1 g57 (
    .A(i0),
    .B(i24),
    .X(o22)
  );
  sky130_fd_sc_hd__and2_1 g58 (
    .A(i0),
    .B(i25),
    .X(o23)
  );
  sky130_fd_sc_hd__and2_1 g59 (
    .A(i0),
    .B(i26),
    .X(o24)
  );
  sky130_fd_sc_hd__and2_1 g60 (
    .A(i0),
    .B(i27),
    .X(o25)
  );
  sky130_fd_sc_hd__and2_1 g61 (
    .A(i0),
    .B(i28),
    .X(o26)
  );
  sky130_fd_sc_hd__and2_1 g62 (
    .A(i0),
    .B(i29),
    .X(o27)
  );
  sky130_fd_sc_hd__and2_1 g63 (
    .A(i0),
    .B(i30),
    .X(o28)
  );
  sky130_fd_sc_hd__and2_1 g64 (
    .A(i0),
    .B(i31),
    .X(o29)
  );
  sky130_fd_sc_hd__and2_1 g65 (
    .A(i0),
    .B(i32),
    .X(o30)
  );
  sky130_fd_sc_hd__and2_1 g66 (
    .A(i0),
    .B(i33),
    .X(o31)
  );
  assign o63 = i32;
  assign o62 = i31;
  assign o61 = i30;
  assign o60 = i29;
  assign o59 = i28;
  assign o58 = i27;
  assign o57 = i26;
  assign o56 = i25;
  assign o55 = i24;
  assign o54 = i23;
  assign o53 = i22;
  assign o52 = i21;
  assign o51 = i20;
  assign o50 = i19;
  assign o49 = i18;
  assign o48 = i17;
  assign o47 = i16;
  assign o46 = i15;
  assign o45 = i14;
  assign o44 = i13;
  assign o43 = i12;
  assign o42 = i11;
  assign o41 = i10;
  assign o40 = i9;
  assign o39 = i8;
  assign o38 = i7;
  assign o37 = i6;
  assign o36 = i5;
  assign o35 = i4;
  assign o34 = i3;
  assign o33 = i2;
endmodule
