/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module mac_acc(i0, i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i20
, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32, i33, i34, i35, i36, i37, i38, i39, i40, i41
, i42, i43, i44, i45, i46, i47, i48, i49, i50, i51, i52, i53, i54, i55, i56, i57, i58, i59, i60, i61, i62
, i63, i64, o0, o1, o2, o3, o4, o5, o6, o7, o8, o9, o10, o11, o12, o13, o14, o15, o16, o17, o18
, o19, o20, o21, o22, o23, o24, o25, o26, o27, o28, o29, o30, o31, o32, o33, o34, o35, o36, o37, o38, o39
, o40, o41, o42, o43, o44, o45, o46, o47, o48, o49, o50, o51, o52, o53, o54, o55, o56, o57, o58, o59, o60
, o61, o62, o63);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input i4;
  wire i4;
  input i5;
  wire i5;
  input i6;
  wire i6;
  input i7;
  wire i7;
  input i8;
  wire i8;
  input i9;
  wire i9;
  input i10;
  wire i10;
  input i11;
  wire i11;
  input i12;
  wire i12;
  input i13;
  wire i13;
  input i14;
  wire i14;
  input i15;
  wire i15;
  input i16;
  wire i16;
  input i17;
  wire i17;
  input i18;
  wire i18;
  input i19;
  wire i19;
  input i20;
  wire i20;
  input i21;
  wire i21;
  input i22;
  wire i22;
  input i23;
  wire i23;
  input i24;
  wire i24;
  input i25;
  wire i25;
  input i26;
  wire i26;
  input i27;
  wire i27;
  input i28;
  wire i28;
  input i29;
  wire i29;
  input i30;
  wire i30;
  input i31;
  wire i31;
  input i32;
  wire i32;
  input i33;
  wire i33;
  input i34;
  wire i34;
  input i35;
  wire i35;
  input i36;
  wire i36;
  input i37;
  wire i37;
  input i38;
  wire i38;
  input i39;
  wire i39;
  input i40;
  wire i40;
  input i41;
  wire i41;
  input i42;
  wire i42;
  input i43;
  wire i43;
  input i44;
  wire i44;
  input i45;
  wire i45;
  input i46;
  wire i46;
  input i47;
  wire i47;
  input i48;
  wire i48;
  input i49;
  wire i49;
  input i50;
  wire i50;
  input i51;
  wire i51;
  input i52;
  wire i52;
  input i53;
  wire i53;
  input i54;
  wire i54;
  input i55;
  wire i55;
  input i56;
  wire i56;
  input i57;
  wire i57;
  input i58;
  wire i58;
  input i59;
  wire i59;
  input i60;
  wire i60;
  input i61;
  wire i61;
  input i62;
  wire i62;
  input i63;
  wire i63;
  input i64;
  wire i64;
  output o0;
  wire o0;
  output o1;
  wire o1;
  output o2;
  wire o2;
  output o3;
  wire o3;
  output o4;
  wire o4;
  output o5;
  wire o5;
  output o6;
  wire o6;
  output o7;
  wire o7;
  output o8;
  wire o8;
  output o9;
  wire o9;
  output o10;
  wire o10;
  output o11;
  wire o11;
  output o12;
  wire o12;
  output o13;
  wire o13;
  output o14;
  wire o14;
  output o15;
  wire o15;
  output o16;
  wire o16;
  output o17;
  wire o17;
  output o18;
  wire o18;
  output o19;
  wire o19;
  output o20;
  wire o20;
  output o21;
  wire o21;
  output o22;
  wire o22;
  output o23;
  wire o23;
  output o24;
  wire o24;
  output o25;
  wire o25;
  output o26;
  wire o26;
  output o27;
  wire o27;
  output o28;
  wire o28;
  output o29;
  wire o29;
  output o30;
  wire o30;
  output o31;
  wire o31;
  output o32;
  wire o32;
  output o33;
  wire o33;
  output o34;
  wire o34;
  output o35;
  wire o35;
  output o36;
  wire o36;
  output o37;
  wire o37;
  output o38;
  wire o38;
  output o39;
  wire o39;
  output o40;
  wire o40;
  output o41;
  wire o41;
  output o42;
  wire o42;
  output o43;
  wire o43;
  output o44;
  wire o44;
  output o45;
  wire o45;
  output o46;
  wire o46;
  output o47;
  wire o47;
  output o48;
  wire o48;
  output o49;
  wire o49;
  output o50;
  wire o50;
  output o51;
  wire o51;
  output o52;
  wire o52;
  output o53;
  wire o53;
  output o54;
  wire o54;
  output o55;
  wire o55;
  output o56;
  wire o56;
  output o57;
  wire o57;
  output o58;
  wire o58;
  output o59;
  wire o59;
  output o60;
  wire o60;
  output o61;
  wire o61;
  output o62;
  wire o62;
  output o63;
  wire o63;
  wire n100;
  wire n102;
  wire n103;
  wire n104;
  wire n105;
  wire n107;
  wire n108;
  wire n109;
  wire n110;
  wire n112;
  wire n113;
  wire n114;
  wire n115;
  wire n117;
  wire n118;
  wire n119;
  wire n120;
  wire n122;
  wire n123;
  wire n124;
  wire n125;
  wire n127;
  wire n128;
  wire n129;
  wire n130;
  wire n132;
  wire n133;
  wire n134;
  wire n135;
  wire n137;
  wire n138;
  wire n139;
  wire n140;
  wire n142;
  wire n143;
  wire n144;
  wire n145;
  wire n147;
  wire n148;
  wire n149;
  wire n150;
  wire n152;
  wire n153;
  wire n154;
  wire n155;
  wire n157;
  wire n158;
  wire n159;
  wire n160;
  wire n162;
  wire n163;
  wire n164;
  wire n165;
  wire n167;
  wire n168;
  wire n169;
  wire n170;
  wire n172;
  wire n173;
  wire n174;
  wire n175;
  wire n177;
  wire n178;
  wire n179;
  wire n180;
  wire n182;
  wire n183;
  wire n184;
  wire n185;
  wire n187;
  wire n188;
  wire n189;
  wire n190;
  wire n192;
  wire n193;
  wire n194;
  wire n195;
  wire n197;
  wire n198;
  wire n199;
  wire n200;
  wire n202;
  wire n203;
  wire n204;
  wire n205;
  wire n207;
  wire n208;
  wire n209;
  wire n210;
  wire n212;
  wire n213;
  wire n214;
  wire n215;
  wire n217;
  wire n218;
  wire n219;
  wire n220;
  wire n65;
  wire n67;
  wire n68;
  wire n69;
  wire n70;
  wire n72;
  wire n73;
  wire n74;
  wire n75;
  wire n77;
  wire n78;
  wire n79;
  wire n80;
  wire n82;
  wire n83;
  wire n84;
  wire n85;
  wire n87;
  wire n88;
  wire n89;
  wire n90;
  wire n92;
  wire n93;
  wire n94;
  wire n95;
  wire n97;
  wire n98;
  wire n99;
  sky130_fd_sc_hd__xor2_1 g100 (
    .A(i40),
    .B(i7),
    .X(n100)
  );
  sky130_fd_sc_hd__xor2_1 g101 (
    .A(n100),
    .B(n99),
    .X(o39)
  );
  sky130_fd_sc_hd__and2_1 g102 (
    .A(i40),
    .B(i7),
    .X(n102)
  );
  sky130_fd_sc_hd__and2_1 g103 (
    .A(n100),
    .B(n99),
    .X(n103)
  );
  sky130_fd_sc_hd__or2_1 g104 (
    .A(n102),
    .B(n103),
    .X(n104)
  );
  sky130_fd_sc_hd__xor2_1 g105 (
    .A(i41),
    .B(i8),
    .X(n105)
  );
  sky130_fd_sc_hd__xor2_1 g106 (
    .A(n105),
    .B(n104),
    .X(o40)
  );
  sky130_fd_sc_hd__and2_1 g107 (
    .A(i41),
    .B(i8),
    .X(n107)
  );
  sky130_fd_sc_hd__and2_1 g108 (
    .A(n105),
    .B(n104),
    .X(n108)
  );
  sky130_fd_sc_hd__or2_1 g109 (
    .A(n107),
    .B(n108),
    .X(n109)
  );
  sky130_fd_sc_hd__xor2_1 g110 (
    .A(i42),
    .B(i9),
    .X(n110)
  );
  sky130_fd_sc_hd__xor2_1 g111 (
    .A(n110),
    .B(n109),
    .X(o41)
  );
  sky130_fd_sc_hd__and2_1 g112 (
    .A(i42),
    .B(i9),
    .X(n112)
  );
  sky130_fd_sc_hd__and2_1 g113 (
    .A(n110),
    .B(n109),
    .X(n113)
  );
  sky130_fd_sc_hd__or2_1 g114 (
    .A(n112),
    .B(n113),
    .X(n114)
  );
  sky130_fd_sc_hd__xor2_1 g115 (
    .A(i43),
    .B(i10),
    .X(n115)
  );
  sky130_fd_sc_hd__xor2_1 g116 (
    .A(n115),
    .B(n114),
    .X(o10)
  );
  sky130_fd_sc_hd__and2_1 g117 (
    .A(i43),
    .B(i10),
    .X(n117)
  );
  sky130_fd_sc_hd__and2_1 g118 (
    .A(n115),
    .B(n114),
    .X(n118)
  );
  sky130_fd_sc_hd__or2_1 g119 (
    .A(n117),
    .B(n118),
    .X(n119)
  );
  sky130_fd_sc_hd__xor2_1 g120 (
    .A(i44),
    .B(i11),
    .X(n120)
  );
  sky130_fd_sc_hd__xor2_1 g121 (
    .A(n120),
    .B(n119),
    .X(o11)
  );
  sky130_fd_sc_hd__and2_1 g122 (
    .A(i44),
    .B(i11),
    .X(n122)
  );
  sky130_fd_sc_hd__and2_1 g123 (
    .A(n120),
    .B(n119),
    .X(n123)
  );
  sky130_fd_sc_hd__or2_1 g124 (
    .A(n122),
    .B(n123),
    .X(n124)
  );
  sky130_fd_sc_hd__xor2_1 g125 (
    .A(i45),
    .B(i12),
    .X(n125)
  );
  sky130_fd_sc_hd__xor2_1 g126 (
    .A(n125),
    .B(n124),
    .X(o12)
  );
  sky130_fd_sc_hd__and2_1 g127 (
    .A(i45),
    .B(i12),
    .X(n127)
  );
  sky130_fd_sc_hd__and2_1 g128 (
    .A(n125),
    .B(n124),
    .X(n128)
  );
  sky130_fd_sc_hd__or2_1 g129 (
    .A(n127),
    .B(n128),
    .X(n129)
  );
  sky130_fd_sc_hd__xor2_1 g130 (
    .A(i46),
    .B(i13),
    .X(n130)
  );
  sky130_fd_sc_hd__xor2_1 g131 (
    .A(n130),
    .B(n129),
    .X(o13)
  );
  sky130_fd_sc_hd__and2_1 g132 (
    .A(i46),
    .B(i13),
    .X(n132)
  );
  sky130_fd_sc_hd__and2_1 g133 (
    .A(n130),
    .B(n129),
    .X(n133)
  );
  sky130_fd_sc_hd__or2_1 g134 (
    .A(n132),
    .B(n133),
    .X(n134)
  );
  sky130_fd_sc_hd__xor2_1 g135 (
    .A(i47),
    .B(i14),
    .X(n135)
  );
  sky130_fd_sc_hd__xor2_1 g136 (
    .A(n135),
    .B(n134),
    .X(o14)
  );
  sky130_fd_sc_hd__and2_1 g137 (
    .A(i47),
    .B(i14),
    .X(n137)
  );
  sky130_fd_sc_hd__and2_1 g138 (
    .A(n135),
    .B(n134),
    .X(n138)
  );
  sky130_fd_sc_hd__or2_1 g139 (
    .A(n137),
    .B(n138),
    .X(n139)
  );
  sky130_fd_sc_hd__xor2_1 g140 (
    .A(i48),
    .B(i15),
    .X(n140)
  );
  sky130_fd_sc_hd__xor2_1 g141 (
    .A(n140),
    .B(n139),
    .X(o15)
  );
  sky130_fd_sc_hd__and2_1 g142 (
    .A(i48),
    .B(i15),
    .X(n142)
  );
  sky130_fd_sc_hd__and2_1 g143 (
    .A(n140),
    .B(n139),
    .X(n143)
  );
  sky130_fd_sc_hd__or2_1 g144 (
    .A(n142),
    .B(n143),
    .X(n144)
  );
  sky130_fd_sc_hd__xor2_1 g145 (
    .A(i49),
    .B(i16),
    .X(n145)
  );
  sky130_fd_sc_hd__xor2_1 g146 (
    .A(n145),
    .B(n144),
    .X(o16)
  );
  sky130_fd_sc_hd__and2_1 g147 (
    .A(i49),
    .B(i16),
    .X(n147)
  );
  sky130_fd_sc_hd__and2_1 g148 (
    .A(n145),
    .B(n144),
    .X(n148)
  );
  sky130_fd_sc_hd__or2_1 g149 (
    .A(n147),
    .B(n148),
    .X(n149)
  );
  sky130_fd_sc_hd__xor2_1 g150 (
    .A(i50),
    .B(i17),
    .X(n150)
  );
  sky130_fd_sc_hd__xor2_1 g151 (
    .A(n150),
    .B(n149),
    .X(o17)
  );
  sky130_fd_sc_hd__and2_1 g152 (
    .A(i50),
    .B(i17),
    .X(n152)
  );
  sky130_fd_sc_hd__and2_1 g153 (
    .A(n150),
    .B(n149),
    .X(n153)
  );
  sky130_fd_sc_hd__or2_1 g154 (
    .A(n152),
    .B(n153),
    .X(n154)
  );
  sky130_fd_sc_hd__xor2_1 g155 (
    .A(i51),
    .B(i18),
    .X(n155)
  );
  sky130_fd_sc_hd__xor2_1 g156 (
    .A(n155),
    .B(n154),
    .X(o18)
  );
  sky130_fd_sc_hd__and2_1 g157 (
    .A(i51),
    .B(i18),
    .X(n157)
  );
  sky130_fd_sc_hd__and2_1 g158 (
    .A(n155),
    .B(n154),
    .X(n158)
  );
  sky130_fd_sc_hd__or2_1 g159 (
    .A(n157),
    .B(n158),
    .X(n159)
  );
  sky130_fd_sc_hd__xor2_1 g160 (
    .A(i52),
    .B(i19),
    .X(n160)
  );
  sky130_fd_sc_hd__xor2_1 g161 (
    .A(n160),
    .B(n159),
    .X(o19)
  );
  sky130_fd_sc_hd__and2_1 g162 (
    .A(i52),
    .B(i19),
    .X(n162)
  );
  sky130_fd_sc_hd__and2_1 g163 (
    .A(n160),
    .B(n159),
    .X(n163)
  );
  sky130_fd_sc_hd__or2_1 g164 (
    .A(n162),
    .B(n163),
    .X(n164)
  );
  sky130_fd_sc_hd__xor2_1 g165 (
    .A(i53),
    .B(i20),
    .X(n165)
  );
  sky130_fd_sc_hd__xor2_1 g166 (
    .A(n165),
    .B(n164),
    .X(o20)
  );
  sky130_fd_sc_hd__and2_1 g167 (
    .A(i53),
    .B(i20),
    .X(n167)
  );
  sky130_fd_sc_hd__and2_1 g168 (
    .A(n165),
    .B(n164),
    .X(n168)
  );
  sky130_fd_sc_hd__or2_1 g169 (
    .A(n167),
    .B(n168),
    .X(n169)
  );
  sky130_fd_sc_hd__xor2_1 g170 (
    .A(i54),
    .B(i21),
    .X(n170)
  );
  sky130_fd_sc_hd__xor2_1 g171 (
    .A(n170),
    .B(n169),
    .X(o21)
  );
  sky130_fd_sc_hd__and2_1 g172 (
    .A(i54),
    .B(i21),
    .X(n172)
  );
  sky130_fd_sc_hd__and2_1 g173 (
    .A(n170),
    .B(n169),
    .X(n173)
  );
  sky130_fd_sc_hd__or2_1 g174 (
    .A(n172),
    .B(n173),
    .X(n174)
  );
  sky130_fd_sc_hd__xor2_1 g175 (
    .A(i55),
    .B(i22),
    .X(n175)
  );
  sky130_fd_sc_hd__xor2_1 g176 (
    .A(n175),
    .B(n174),
    .X(o22)
  );
  sky130_fd_sc_hd__and2_1 g177 (
    .A(i55),
    .B(i22),
    .X(n177)
  );
  sky130_fd_sc_hd__and2_1 g178 (
    .A(n175),
    .B(n174),
    .X(n178)
  );
  sky130_fd_sc_hd__or2_1 g179 (
    .A(n177),
    .B(n178),
    .X(n179)
  );
  sky130_fd_sc_hd__xor2_1 g180 (
    .A(i56),
    .B(i23),
    .X(n180)
  );
  sky130_fd_sc_hd__xor2_1 g181 (
    .A(n180),
    .B(n179),
    .X(o23)
  );
  sky130_fd_sc_hd__and2_1 g182 (
    .A(i56),
    .B(i23),
    .X(n182)
  );
  sky130_fd_sc_hd__and2_1 g183 (
    .A(n180),
    .B(n179),
    .X(n183)
  );
  sky130_fd_sc_hd__or2_1 g184 (
    .A(n182),
    .B(n183),
    .X(n184)
  );
  sky130_fd_sc_hd__xor2_1 g185 (
    .A(i57),
    .B(i24),
    .X(n185)
  );
  sky130_fd_sc_hd__xor2_1 g186 (
    .A(n185),
    .B(n184),
    .X(o24)
  );
  sky130_fd_sc_hd__and2_1 g187 (
    .A(i57),
    .B(i24),
    .X(n187)
  );
  sky130_fd_sc_hd__and2_1 g188 (
    .A(n185),
    .B(n184),
    .X(n188)
  );
  sky130_fd_sc_hd__or2_1 g189 (
    .A(n187),
    .B(n188),
    .X(n189)
  );
  sky130_fd_sc_hd__xor2_1 g190 (
    .A(i58),
    .B(i25),
    .X(n190)
  );
  sky130_fd_sc_hd__xor2_1 g191 (
    .A(n190),
    .B(n189),
    .X(o25)
  );
  sky130_fd_sc_hd__and2_1 g192 (
    .A(i58),
    .B(i25),
    .X(n192)
  );
  sky130_fd_sc_hd__and2_1 g193 (
    .A(n190),
    .B(n189),
    .X(n193)
  );
  sky130_fd_sc_hd__or2_1 g194 (
    .A(n192),
    .B(n193),
    .X(n194)
  );
  sky130_fd_sc_hd__xor2_1 g195 (
    .A(i59),
    .B(i26),
    .X(n195)
  );
  sky130_fd_sc_hd__xor2_1 g196 (
    .A(n195),
    .B(n194),
    .X(o26)
  );
  sky130_fd_sc_hd__and2_1 g197 (
    .A(i59),
    .B(i26),
    .X(n197)
  );
  sky130_fd_sc_hd__and2_1 g198 (
    .A(n195),
    .B(n194),
    .X(n198)
  );
  sky130_fd_sc_hd__or2_1 g199 (
    .A(n197),
    .B(n198),
    .X(n199)
  );
  sky130_fd_sc_hd__xor2_1 g200 (
    .A(i60),
    .B(i27),
    .X(n200)
  );
  sky130_fd_sc_hd__xor2_1 g201 (
    .A(n200),
    .B(n199),
    .X(o27)
  );
  sky130_fd_sc_hd__and2_1 g202 (
    .A(i60),
    .B(i27),
    .X(n202)
  );
  sky130_fd_sc_hd__and2_1 g203 (
    .A(n200),
    .B(n199),
    .X(n203)
  );
  sky130_fd_sc_hd__or2_1 g204 (
    .A(n202),
    .B(n203),
    .X(n204)
  );
  sky130_fd_sc_hd__xor2_1 g205 (
    .A(i61),
    .B(i28),
    .X(n205)
  );
  sky130_fd_sc_hd__xor2_1 g206 (
    .A(n205),
    .B(n204),
    .X(o28)
  );
  sky130_fd_sc_hd__and2_1 g207 (
    .A(i61),
    .B(i28),
    .X(n207)
  );
  sky130_fd_sc_hd__and2_1 g208 (
    .A(n205),
    .B(n204),
    .X(n208)
  );
  sky130_fd_sc_hd__or2_1 g209 (
    .A(n207),
    .B(n208),
    .X(n209)
  );
  sky130_fd_sc_hd__xor2_1 g210 (
    .A(i62),
    .B(i29),
    .X(n210)
  );
  sky130_fd_sc_hd__xor2_1 g211 (
    .A(n210),
    .B(n209),
    .X(o29)
  );
  sky130_fd_sc_hd__and2_1 g212 (
    .A(i62),
    .B(i29),
    .X(n212)
  );
  sky130_fd_sc_hd__and2_1 g213 (
    .A(n210),
    .B(n209),
    .X(n213)
  );
  sky130_fd_sc_hd__or2_1 g214 (
    .A(n212),
    .B(n213),
    .X(n214)
  );
  sky130_fd_sc_hd__xor2_1 g215 (
    .A(i63),
    .B(i30),
    .X(n215)
  );
  sky130_fd_sc_hd__xor2_1 g216 (
    .A(n215),
    .B(n214),
    .X(o30)
  );
  sky130_fd_sc_hd__and2_1 g217 (
    .A(i63),
    .B(i30),
    .X(n217)
  );
  sky130_fd_sc_hd__and2_1 g218 (
    .A(n215),
    .B(n214),
    .X(n218)
  );
  sky130_fd_sc_hd__or2_1 g219 (
    .A(n217),
    .B(n218),
    .X(n219)
  );
  sky130_fd_sc_hd__xor2_1 g220 (
    .A(i64),
    .B(i31),
    .X(n220)
  );
  sky130_fd_sc_hd__xor2_1 g221 (
    .A(n220),
    .B(n219),
    .X(o31)
  );
  sky130_fd_sc_hd__xor2_1 g65 (
    .A(i33),
    .B(i0),
    .X(n65)
  );
  sky130_fd_sc_hd__xor2_1 g66 (
    .A(n65),
    .B(i32),
    .X(o0)
  );
  sky130_fd_sc_hd__and2_1 g67 (
    .A(i33),
    .B(i0),
    .X(n67)
  );
  sky130_fd_sc_hd__and2_1 g68 (
    .A(n65),
    .B(i32),
    .X(n68)
  );
  sky130_fd_sc_hd__or2_1 g69 (
    .A(n67),
    .B(n68),
    .X(n69)
  );
  sky130_fd_sc_hd__xor2_1 g70 (
    .A(i34),
    .B(i1),
    .X(n70)
  );
  sky130_fd_sc_hd__xor2_1 g71 (
    .A(n70),
    .B(n69),
    .X(o1)
  );
  sky130_fd_sc_hd__and2_1 g72 (
    .A(i34),
    .B(i1),
    .X(n72)
  );
  sky130_fd_sc_hd__and2_1 g73 (
    .A(n70),
    .B(n69),
    .X(n73)
  );
  sky130_fd_sc_hd__or2_1 g74 (
    .A(n72),
    .B(n73),
    .X(n74)
  );
  sky130_fd_sc_hd__xor2_1 g75 (
    .A(i35),
    .B(i2),
    .X(n75)
  );
  sky130_fd_sc_hd__xor2_1 g76 (
    .A(n75),
    .B(n74),
    .X(o2)
  );
  sky130_fd_sc_hd__and2_1 g77 (
    .A(i35),
    .B(i2),
    .X(n77)
  );
  sky130_fd_sc_hd__and2_1 g78 (
    .A(n75),
    .B(n74),
    .X(n78)
  );
  sky130_fd_sc_hd__or2_1 g79 (
    .A(n77),
    .B(n78),
    .X(n79)
  );
  sky130_fd_sc_hd__xor2_1 g80 (
    .A(i36),
    .B(i3),
    .X(n80)
  );
  sky130_fd_sc_hd__xor2_1 g81 (
    .A(n80),
    .B(n79),
    .X(o3)
  );
  sky130_fd_sc_hd__and2_1 g82 (
    .A(i36),
    .B(i3),
    .X(n82)
  );
  sky130_fd_sc_hd__and2_1 g83 (
    .A(n80),
    .B(n79),
    .X(n83)
  );
  sky130_fd_sc_hd__or2_1 g84 (
    .A(n82),
    .B(n83),
    .X(n84)
  );
  sky130_fd_sc_hd__xor2_1 g85 (
    .A(i37),
    .B(i4),
    .X(n85)
  );
  sky130_fd_sc_hd__xor2_1 g86 (
    .A(n85),
    .B(n84),
    .X(o36)
  );
  sky130_fd_sc_hd__and2_1 g87 (
    .A(i37),
    .B(i4),
    .X(n87)
  );
  sky130_fd_sc_hd__and2_1 g88 (
    .A(n85),
    .B(n84),
    .X(n88)
  );
  sky130_fd_sc_hd__or2_1 g89 (
    .A(n87),
    .B(n88),
    .X(n89)
  );
  sky130_fd_sc_hd__xor2_1 g90 (
    .A(i38),
    .B(i5),
    .X(n90)
  );
  sky130_fd_sc_hd__xor2_1 g91 (
    .A(n90),
    .B(n89),
    .X(o37)
  );
  sky130_fd_sc_hd__and2_1 g92 (
    .A(i38),
    .B(i5),
    .X(n92)
  );
  sky130_fd_sc_hd__and2_1 g93 (
    .A(n90),
    .B(n89),
    .X(n93)
  );
  sky130_fd_sc_hd__or2_1 g94 (
    .A(n92),
    .B(n93),
    .X(n94)
  );
  sky130_fd_sc_hd__xor2_1 g95 (
    .A(i39),
    .B(i6),
    .X(n95)
  );
  sky130_fd_sc_hd__xor2_1 g96 (
    .A(n95),
    .B(n94),
    .X(o38)
  );
  sky130_fd_sc_hd__and2_1 g97 (
    .A(i39),
    .B(i6),
    .X(n97)
  );
  sky130_fd_sc_hd__and2_1 g98 (
    .A(n95),
    .B(n94),
    .X(n98)
  );
  sky130_fd_sc_hd__or2_1 g99 (
    .A(n97),
    .B(n98),
    .X(n99)
  );
  assign o63 = o31;
  assign o62 = o30;
  assign o61 = o29;
  assign o60 = o28;
  assign o59 = o27;
  assign o58 = o26;
  assign o57 = o25;
  assign o56 = o24;
  assign o55 = o23;
  assign o54 = o22;
  assign o53 = o21;
  assign o52 = o20;
  assign o51 = o19;
  assign o50 = o18;
  assign o49 = o17;
  assign o48 = o16;
  assign o47 = o15;
  assign o46 = o14;
  assign o45 = o13;
  assign o44 = o12;
  assign o43 = o11;
  assign o42 = o10;
  assign o35 = o3;
  assign o34 = o2;
  assign o33 = o1;
  assign o32 = o0;
  assign o9 = o41;
  assign o8 = o40;
  assign o7 = o39;
  assign o6 = o38;
  assign o5 = o37;
  assign o4 = o36;
endmodule
