/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module memif(addr, funct3, mem_we, rs2, rdata_raw, load_out, wdata_mem, be);
  input [1:0] addr;
  wire [1:0] addr;
  input [2:0] funct3;
  wire [2:0] funct3;
  input mem_we;
  wire mem_we;
  input [31:0] rs2;
  wire [31:0] rs2;
  input [31:0] rdata_raw;
  wire [31:0] rdata_raw;
  output [31:0] load_out;
  wire [31:0] load_out;
  output [31:0] wdata_mem;
  wire [31:0] wdata_mem;
  output [3:0] be;
  wire [3:0] be;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire [7:0] lane_b;
  wire [15:0] lane_h;
  sky130_fd_sc_hd__clkinv_1 _098_ (
    .A(funct3[1]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _099_ (
    .A(addr[1]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(funct3[1]),
    .B(funct3[2]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _101_ (
    .A(funct3[1]),
    .SLEEP(funct3[2]),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(rs2[4]),
    .B(_002_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(funct3[1]),
    .B(funct3[0]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _104_ (
    .A(funct3[1]),
    .SLEEP(funct3[0]),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor3_1 _105_ (
    .A(funct3[1]),
    .B(funct3[0]),
    .C(funct3[2]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__or3_1 _106_ (
    .A(funct3[1]),
    .B(funct3[0]),
    .C(funct3[2]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(rs2[4]),
    .B(_007_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _108_ (
    .A(rs2[12]),
    .B(_008_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(_009_),
    .B(_010_),
    .Y(wdata_mem[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _110_ (
    .A(funct3[0]),
    .SLEEP(funct3[1]),
    .X(_011_)
  );
  sky130_fd_sc_hd__nand2b_1 _111_ (
    .A_N(funct3[1]),
    .B(funct3[0]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor3b_1 _112_ (
    .A(funct3[1]),
    .B(funct3[2]),
    .C_N(funct3[0]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a211oi_1 _113_ (
    .A1(rs2[4]),
    .A2(_002_),
    .B1(_013_),
    .C1(rs2[28]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a31oi_1 _114_ (
    .A1(_002_),
    .A2(_009_),
    .A3(_010_),
    .B1(_014_),
    .Y(wdata_mem[28])
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(rs2[3]),
    .B(_002_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(rs2[3]),
    .B(_007_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _117_ (
    .A(rs2[11]),
    .B(_008_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _118_ (
    .A(_016_),
    .B(_017_),
    .Y(wdata_mem[11])
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(rs2[27]),
    .B(_013_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a32oi_1 _120_ (
    .A1(_002_),
    .A2(_016_),
    .A3(_017_),
    .B1(_018_),
    .B2(_015_),
    .Y(wdata_mem[27])
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(rs2[2]),
    .B(_002_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(rs2[2]),
    .B(_007_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _123_ (
    .A(rs2[10]),
    .B(_008_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _124_ (
    .A(_020_),
    .B(_021_),
    .Y(wdata_mem[10])
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(rs2[26]),
    .B(_013_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a32oi_1 _126_ (
    .A1(_002_),
    .A2(_020_),
    .A3(_021_),
    .B1(_022_),
    .B2(_019_),
    .Y(wdata_mem[26])
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(rs2[1]),
    .B(_002_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(rs2[1]),
    .B(_007_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(rs2[9]),
    .B(_008_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _130_ (
    .A(_024_),
    .B(_025_),
    .Y(wdata_mem[9])
  );
  sky130_fd_sc_hd__a211oi_1 _131_ (
    .A1(rs2[1]),
    .A2(_002_),
    .B1(_013_),
    .C1(rs2[25]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a31oi_1 _132_ (
    .A1(_002_),
    .A2(_024_),
    .A3(_025_),
    .B1(_026_),
    .Y(wdata_mem[25])
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(rs2[0]),
    .B(_002_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(rs2[0]),
    .B(_007_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _135_ (
    .A(rs2[8]),
    .B(_008_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _136_ (
    .A(_028_),
    .B(_029_),
    .Y(wdata_mem[8])
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(rs2[24]),
    .B(_013_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a32oi_1 _138_ (
    .A1(_002_),
    .A2(_028_),
    .A3(_029_),
    .B1(_030_),
    .B2(_027_),
    .Y(wdata_mem[24])
  );
  sky130_fd_sc_hd__nand2_1 _139_ (
    .A(rs2[7]),
    .B(_002_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(rs2[23]),
    .B(_003_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _141_ (
    .A(_031_),
    .B(_032_),
    .Y(wdata_mem[23])
  );
  sky130_fd_sc_hd__nand2_1 _142_ (
    .A(rs2[6]),
    .B(_002_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(rs2[22]),
    .B(_003_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(_033_),
    .B(_034_),
    .Y(wdata_mem[22])
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(rs2[5]),
    .B(_002_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(rs2[21]),
    .B(_003_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _147_ (
    .A(_035_),
    .B(_036_),
    .Y(wdata_mem[21])
  );
  sky130_fd_sc_hd__nand2_1 _148_ (
    .A(rs2[20]),
    .B(_003_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_004_),
    .B(_037_),
    .Y(wdata_mem[20])
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(rs2[19]),
    .B(_003_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_015_),
    .B(_038_),
    .Y(wdata_mem[19])
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(rs2[18]),
    .B(_003_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _153_ (
    .A(_019_),
    .B(_039_),
    .Y(wdata_mem[18])
  );
  sky130_fd_sc_hd__nand2_1 _154_ (
    .A(rs2[17]),
    .B(_003_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _155_ (
    .A(_023_),
    .B(_040_),
    .Y(wdata_mem[17])
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(rs2[16]),
    .B(_003_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_027_),
    .B(_041_),
    .Y(wdata_mem[16])
  );
  sky130_fd_sc_hd__nand2_1 _158_ (
    .A(rs2[7]),
    .B(_007_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _159_ (
    .A(rs2[15]),
    .B(_008_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(_042_),
    .B(_043_),
    .Y(wdata_mem[15])
  );
  sky130_fd_sc_hd__nand2_1 _161_ (
    .A(rs2[6]),
    .B(_007_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(rs2[14]),
    .B(_008_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(_044_),
    .B(_045_),
    .Y(wdata_mem[14])
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(rs2[5]),
    .B(_007_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _165_ (
    .A(rs2[13]),
    .B(_008_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(_046_),
    .B(_047_),
    .Y(wdata_mem[13])
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(rdata_raw[7]),
    .A1(rdata_raw[23]),
    .S(addr[1]),
    .X(lane_h[7])
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(rdata_raw[15]),
    .A1(rdata_raw[31]),
    .S(addr[1]),
    .X(lane_h[15])
  );
  sky130_fd_sc_hd__mux4_2 _169_ (
    .A0(rdata_raw[7]),
    .A1(rdata_raw[23]),
    .A2(rdata_raw[15]),
    .A3(rdata_raw[31]),
    .S0(addr[1]),
    .S1(addr[0]),
    .X(lane_b[7])
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(funct3[1]),
    .B(rdata_raw[30]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(_007_),
    .B(lane_b[7]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a22oi_1 _172_ (
    .A1(_013_),
    .A2(lane_h[15]),
    .B1(lane_b[7]),
    .B2(_007_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_048_),
    .B(_050_),
    .Y(load_out[30])
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(funct3[1]),
    .B(rdata_raw[29]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _175_ (
    .A(_050_),
    .B(_051_),
    .Y(load_out[29])
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(funct3[1]),
    .B(rdata_raw[28]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(_050_),
    .B(_052_),
    .Y(load_out[28])
  );
  sky130_fd_sc_hd__nand2_1 _178_ (
    .A(funct3[1]),
    .B(rdata_raw[27]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_050_),
    .B(_053_),
    .Y(load_out[27])
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(funct3[1]),
    .B(rdata_raw[26]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(_050_),
    .B(_054_),
    .Y(load_out[26])
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(funct3[1]),
    .B(rdata_raw[25]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(_050_),
    .B(_055_),
    .Y(load_out[25])
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(funct3[1]),
    .B(rdata_raw[24]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_050_),
    .B(_056_),
    .Y(load_out[24])
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(funct3[1]),
    .B(rdata_raw[23]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(_050_),
    .B(_057_),
    .Y(load_out[23])
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(funct3[1]),
    .B(rdata_raw[22]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(_050_),
    .B(_058_),
    .Y(load_out[22])
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(funct3[1]),
    .B(rdata_raw[21]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(_050_),
    .B(_059_),
    .Y(load_out[21])
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(funct3[1]),
    .B(rdata_raw[20]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(_050_),
    .B(_060_),
    .Y(load_out[20])
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(funct3[1]),
    .B(rdata_raw[19]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(_050_),
    .B(_061_),
    .Y(load_out[19])
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(funct3[1]),
    .B(rdata_raw[18]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_050_),
    .B(_062_),
    .Y(load_out[18])
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(funct3[1]),
    .B(rdata_raw[17]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_050_),
    .B(_063_),
    .Y(load_out[17])
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(funct3[1]),
    .B(rdata_raw[16]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(_050_),
    .B(_064_),
    .Y(load_out[16])
  );
  sky130_fd_sc_hd__a22oi_1 _202_ (
    .A1(funct3[1]),
    .A2(rdata_raw[15]),
    .B1(_011_),
    .B2(lane_h[15]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_049_),
    .B(_065_),
    .Y(load_out[15])
  );
  sky130_fd_sc_hd__mux2_1 _204_ (
    .A0(rdata_raw[14]),
    .A1(rdata_raw[30]),
    .S(addr[1]),
    .X(lane_h[14])
  );
  sky130_fd_sc_hd__a22oi_1 _205_ (
    .A1(funct3[1]),
    .A2(rdata_raw[14]),
    .B1(_011_),
    .B2(lane_h[14]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_049_),
    .B(_066_),
    .Y(load_out[14])
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(rdata_raw[13]),
    .A1(rdata_raw[29]),
    .S(addr[1]),
    .X(lane_h[13])
  );
  sky130_fd_sc_hd__a22oi_1 _208_ (
    .A1(funct3[1]),
    .A2(rdata_raw[13]),
    .B1(_011_),
    .B2(lane_h[13]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_049_),
    .B(_067_),
    .Y(load_out[13])
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(rdata_raw[12]),
    .A1(rdata_raw[28]),
    .S(addr[1]),
    .X(lane_h[12])
  );
  sky130_fd_sc_hd__a22oi_1 _211_ (
    .A1(funct3[1]),
    .A2(rdata_raw[12]),
    .B1(_011_),
    .B2(lane_h[12]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_049_),
    .B(_068_),
    .Y(load_out[12])
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(rdata_raw[11]),
    .A1(rdata_raw[27]),
    .S(addr[1]),
    .X(lane_h[11])
  );
  sky130_fd_sc_hd__a22oi_1 _214_ (
    .A1(funct3[1]),
    .A2(rdata_raw[11]),
    .B1(_011_),
    .B2(lane_h[11]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_049_),
    .B(_069_),
    .Y(load_out[11])
  );
  sky130_fd_sc_hd__mux2_1 _216_ (
    .A0(rdata_raw[10]),
    .A1(rdata_raw[26]),
    .S(addr[1]),
    .X(lane_h[10])
  );
  sky130_fd_sc_hd__a22oi_1 _217_ (
    .A1(funct3[1]),
    .A2(rdata_raw[10]),
    .B1(_011_),
    .B2(lane_h[10]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_049_),
    .B(_070_),
    .Y(load_out[10])
  );
  sky130_fd_sc_hd__mux2_1 _219_ (
    .A0(rdata_raw[9]),
    .A1(rdata_raw[25]),
    .S(addr[1]),
    .X(lane_h[9])
  );
  sky130_fd_sc_hd__a22oi_1 _220_ (
    .A1(funct3[1]),
    .A2(rdata_raw[9]),
    .B1(_011_),
    .B2(lane_h[9]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(_049_),
    .B(_071_),
    .Y(load_out[9])
  );
  sky130_fd_sc_hd__mux2_1 _222_ (
    .A0(rdata_raw[8]),
    .A1(rdata_raw[24]),
    .S(addr[1]),
    .X(lane_h[8])
  );
  sky130_fd_sc_hd__a22oi_1 _223_ (
    .A1(funct3[1]),
    .A2(rdata_raw[8]),
    .B1(_011_),
    .B2(lane_h[8]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_049_),
    .B(_072_),
    .Y(load_out[8])
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(funct3[1]),
    .B(rdata_raw[7]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a22oi_1 _226_ (
    .A1(_011_),
    .A2(lane_h[7]),
    .B1(lane_b[7]),
    .B2(_005_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_073_),
    .B(_074_),
    .Y(load_out[7])
  );
  sky130_fd_sc_hd__mux2_1 _228_ (
    .A0(rdata_raw[6]),
    .A1(rdata_raw[22]),
    .S(addr[1]),
    .X(lane_h[6])
  );
  sky130_fd_sc_hd__mux4_2 _229_ (
    .A0(rdata_raw[6]),
    .A1(rdata_raw[14]),
    .A2(rdata_raw[22]),
    .A3(rdata_raw[30]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[6])
  );
  sky130_fd_sc_hd__nor2_1 _230_ (
    .A(_012_),
    .B(lane_h[6]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__o22ai_1 _231_ (
    .A1(_000_),
    .A2(rdata_raw[6]),
    .B1(_006_),
    .B2(lane_b[6]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(_075_),
    .B(_076_),
    .Y(load_out[6])
  );
  sky130_fd_sc_hd__mux2_1 _233_ (
    .A0(rdata_raw[5]),
    .A1(rdata_raw[21]),
    .S(addr[1]),
    .X(lane_h[5])
  );
  sky130_fd_sc_hd__mux4_2 _234_ (
    .A0(rdata_raw[5]),
    .A1(rdata_raw[13]),
    .A2(rdata_raw[21]),
    .A3(rdata_raw[29]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[5])
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_012_),
    .B(lane_h[5]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o22ai_1 _236_ (
    .A1(_000_),
    .A2(rdata_raw[5]),
    .B1(_006_),
    .B2(lane_b[5]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _237_ (
    .A(_077_),
    .B(_078_),
    .Y(load_out[5])
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(rdata_raw[4]),
    .A1(rdata_raw[20]),
    .S(addr[1]),
    .X(lane_h[4])
  );
  sky130_fd_sc_hd__mux4_2 _239_ (
    .A0(rdata_raw[4]),
    .A1(rdata_raw[12]),
    .A2(rdata_raw[20]),
    .A3(rdata_raw[28]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[4])
  );
  sky130_fd_sc_hd__nor2_1 _240_ (
    .A(_012_),
    .B(lane_h[4]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o22ai_1 _241_ (
    .A1(_000_),
    .A2(rdata_raw[4]),
    .B1(_006_),
    .B2(lane_b[4]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _242_ (
    .A(_079_),
    .B(_080_),
    .Y(load_out[4])
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(rdata_raw[3]),
    .A1(rdata_raw[19]),
    .S(addr[1]),
    .X(lane_h[3])
  );
  sky130_fd_sc_hd__mux4_2 _244_ (
    .A0(rdata_raw[3]),
    .A1(rdata_raw[11]),
    .A2(rdata_raw[19]),
    .A3(rdata_raw[27]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[3])
  );
  sky130_fd_sc_hd__nor2_1 _245_ (
    .A(_012_),
    .B(lane_h[3]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o22ai_1 _246_ (
    .A1(_000_),
    .A2(rdata_raw[3]),
    .B1(_006_),
    .B2(lane_b[3]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _247_ (
    .A(_081_),
    .B(_082_),
    .Y(load_out[3])
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(rdata_raw[2]),
    .A1(rdata_raw[18]),
    .S(addr[1]),
    .X(lane_h[2])
  );
  sky130_fd_sc_hd__mux4_2 _249_ (
    .A0(rdata_raw[2]),
    .A1(rdata_raw[10]),
    .A2(rdata_raw[18]),
    .A3(rdata_raw[26]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[2])
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(_006_),
    .B(lane_b[2]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o22ai_1 _251_ (
    .A1(_000_),
    .A2(rdata_raw[2]),
    .B1(_012_),
    .B2(lane_h[2]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _252_ (
    .A(_083_),
    .B(_084_),
    .Y(load_out[2])
  );
  sky130_fd_sc_hd__mux2_1 _253_ (
    .A0(rdata_raw[1]),
    .A1(rdata_raw[17]),
    .S(addr[1]),
    .X(lane_h[1])
  );
  sky130_fd_sc_hd__mux4_2 _254_ (
    .A0(rdata_raw[1]),
    .A1(rdata_raw[9]),
    .A2(rdata_raw[17]),
    .A3(rdata_raw[25]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[1])
  );
  sky130_fd_sc_hd__a222oi_1 _255_ (
    .A1(funct3[1]),
    .A2(rdata_raw[1]),
    .B1(_011_),
    .B2(lane_h[1]),
    .C1(lane_b[1]),
    .C2(_005_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__clkinv_1 _256_ (
    .A(_085_),
    .Y(load_out[1])
  );
  sky130_fd_sc_hd__mux2_1 _257_ (
    .A0(rdata_raw[0]),
    .A1(rdata_raw[16]),
    .S(addr[1]),
    .X(lane_h[0])
  );
  sky130_fd_sc_hd__mux4_2 _258_ (
    .A0(rdata_raw[0]),
    .A1(rdata_raw[8]),
    .A2(rdata_raw[16]),
    .A3(rdata_raw[24]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(lane_b[0])
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_011_),
    .B(lane_h[0]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__a22oi_1 _260_ (
    .A1(funct3[1]),
    .A2(rdata_raw[0]),
    .B1(_005_),
    .B2(lane_b[0]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_086_),
    .B(_087_),
    .Y(load_out[0])
  );
  sky130_fd_sc_hd__nor2_1 _262_ (
    .A(addr[0]),
    .B(_008_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _263_ (
    .A1(_001_),
    .A2(_003_),
    .B1(mem_we),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_088_),
    .B(_089_),
    .Y(be[1])
  );
  sky130_fd_sc_hd__a21oi_1 _265_ (
    .A1(addr[0]),
    .A2(_007_),
    .B1(_089_),
    .Y(be[0])
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(addr[1]),
    .A2(_003_),
    .B1(mem_we),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nor2_1 _267_ (
    .A(_088_),
    .B(_090_),
    .Y(be[3])
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(rs2[15]),
    .B(_013_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a22oi_1 _269_ (
    .A1(rs2[31]),
    .A2(_003_),
    .B1(_007_),
    .B2(rs2[7]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(_091_),
    .B(_092_),
    .Y(wdata_mem[31])
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(funct3[1]),
    .B(rdata_raw[31]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_050_),
    .B(_093_),
    .Y(load_out[31])
  );
  sky130_fd_sc_hd__a21oi_1 _273_ (
    .A1(addr[0]),
    .A2(_007_),
    .B1(_090_),
    .Y(be[2])
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(rs2[14]),
    .B(_013_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a22oi_1 _275_ (
    .A1(rs2[30]),
    .A2(_003_),
    .B1(_007_),
    .B2(rs2[6]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(_094_),
    .B(_095_),
    .Y(wdata_mem[30])
  );
  sky130_fd_sc_hd__nor2_1 _277_ (
    .A(rs2[29]),
    .B(_013_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(funct3[0]),
    .A2(rs2[13]),
    .B1(_003_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _279_ (
    .A1(_096_),
    .A2(_097_),
    .B1(_046_),
    .Y(wdata_mem[29])
  );
  assign wdata_mem[7:0] = rs2[7:0];
endmodule
