"""Shared transcript + git parser for the campaign ledger tools.

Owner: the EVIDENCE seat. Charter: docs/measurement-preregistration.md
(frozen 2026-08-06, Council I) and its dated addenda.

This module is the single place where a session transcript record is
classified as "a human typed this" or "the harness injected this". Both
the silence-window ledger and the token meter import it, so the two
published tables can never disagree about who was present.

METHODOLOGY, IN ONE PARAGRAPH
-----------------------------
Claude Code writes one JSONL record per event under
``~/.claude/projects/<mangled-cwd>/``. Records with ``"type": "user"``
are NOT all human: agent-completion notices, loop-timer ticks, cron
pings, peer-seat messages and context-compaction summaries are all
injected with ``role: "user"``. Counting them as human presence is the
error caught in salt triple-campaign Amendment 2 (it moved the >=1h
silence share from 0.3% to 21.5%). This module rejects them by the
record's own provenance fields -- ``origin.kind``, ``promptSource`` and
``isMeta`` -- and falls back to string patterns only for records written
by older clients that predate those fields. Every rejection is counted
and printed, so the filter is auditable from the published table.

THE FIREWALL
------------
Employer-lane projects (``loca``, ``holl``) are never read. Not by
default, not behind a flag -- the denylist is enforced in code, and the
consequence is stated in the output: silence here means "no human
direction reached the personal-lane fleet", never "the human was
asleep".
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

TZ = ZoneInfo("America/Los_Angeles")
PROJECTS_ROOT = Path.home() / ".claude" / "projects"

# ⛔⛔ THE DISCOVERY BLIND SPOT, born 2026-08-08 and flagged by the maestro at
# 19:51 after the Captain asked "are we recording tokens?".
#
# Until today every seat wrote into ``~/.claude/projects``. The per-seat
# ISOLATION moved four of them to ``${SEAT_CONFIG_DIR}
# evidence}/projects/`` -- and this module knew only the original root, so every
# tool built on ``discover_personal_projects`` silently measured ONE seat's
# transcripts and reported it as the fleet's.
#
# 🔑 THE PART THAT IS MINE: I BUILT A CROSS-SEAT READER AT 15:1x TODAY
# (``watch_transport_census.py`` enumerates all five roots by name) AND NEVER
# ASKED WHETHER MY OTHER INSTRUMENTS HAD THE SAME BLIND SPOT. I had the fact and
# did not carry it one file sideways. [[a-count-is-not-a-scope]]
#
# ⚠️ AND THE FAILURE IS SILENT BY CONSTRUCTION: a missing root yields no error,
# no warning and a smaller number -- the shape that reads as "less happened",
# never as "I looked in fewer places". ``roots_report()`` exists so a run can
# SAY where it looked, because an unstated scope is how this survived at all.
def _project_roots() -> list[Path]:
    roots = [PROJECTS_ROOT]
    for d in sorted(Path.home().glob("${SEAT_CONFIG_DIR}")):
        p = d / "projects"
        if p.is_dir():
            roots.append(p)
    return [r for r in roots if r.is_dir()]


PROJECTS_ROOTS = _project_roots()


def roots_report() -> str:
    """Human-readable statement of WHERE a run looked. Print it beside totals."""
    return " · ".join(f"{r.parent.name}:{len(list(r.glob('*/*.jsonl')))}"
                      for r in PROJECTS_ROOTS)

# --- the firewall (portfolio CLAUDE.md, JYH-ratified 2026-07-21) -----------
# Outside-lane material never enters a personal-lane artifact. These are
# matched against the project directory name; the check is substring-based
# and deliberately blunt.
EMPLOYER_LANE = ("-claude-loca", "-claude-holl")

# Personal-lane repos whose seats can carry human presence. A seat not in
# this list is still readable if named explicitly on the command line,
# unless it is employer-lane.
PERSONAL_LANE_HINTS = (
    "-claude-salt",
    "-claude-saltworks",
    "-claude-jas",
    "-claude-mandelbrot",
    "-claude-metaprl",
    "-claude-libmojave",
    "-claude-omake",
    "-claude-jacobian-gist",
)

# ---------------------------------------------------------------------------
# provenance classification
# ---------------------------------------------------------------------------

# String prefixes that identify a harness injection in records written
# before ``origin``/``promptSource`` existed. Order matters only for the
# label that gets reported.
LEGACY_INJECTION_PREFIXES = (
    ("<task-notification>", "task-notification"),
    ("<system-reminder>", "system-reminder"),
    ("[SYSTEM NOTIFICATION", "task-notification"),
    ("# Autonomous loop", "loop-tick"),
    ("Another Claude session sent a message:", "peer-message"),
    ("This session is being continued from a previous conversation", "compaction-summary"),
    ("Caveat: The messages below were generated by the user", "slash-command-echo"),
    ("<local-command-caveat>", "slash-command-echo"),
    ("<local-command-stdout>", "slash-command-echo"),
    ("<bash-input>", "bash-mode"),
    ("<bash-stdout>", "bash-mode"),
    ("<bash-stderr>", "bash-mode"),
)

# Human touches we count. ``typed`` is a message the human wrote;
# ``slash-command`` is a command they invoked (/model, /login -- proof of a
# hand on the keyboard); ``interrupt`` is an ESC press mid-response.
HUMAN_KINDS = ("typed", "slash-command", "interrupt", "legacy-fallback")


@dataclass
class Touch:
    """One moment at which a human demonstrably touched a seat."""

    when: datetime  # tz-aware, America/Los_Angeles
    kind: str  # one of HUMAN_KINDS
    project: str  # project directory name
    session: str
    chars: int = 0


@dataclass
class UsageEvent:
    """One API request, deduplicated by requestId."""

    when: datetime
    project: str
    model: str
    tier: str
    input_tokens: int
    output_tokens: int
    cache_creation: int
    cache_read: int
    session: str
    subagent: bool
    effort: str = ""


@dataclass
class ParseStats:
    """Everything the filter threw away, so the filter can be audited."""

    files: int = 0
    records: int = 0
    bad_json: int = 0
    user_records: int = 0
    rejected: Counter = field(default_factory=Counter)
    accepted: Counter = field(default_factory=Counter)
    queue_corrections: int = 0
    queue_max_shift_s: float = 0.0
    dedup_dropped: int = 0
    synthetic_dropped: int = 0
    # earliest / latest timestamp of ANY record in the transcripts read.
    # Outside [corpus_start, corpus_end] nothing is observed, and a
    # silence window there is unmeasured rather than long.
    corpus_start: datetime | None = None
    corpus_end: datetime | None = None

    def see(self, when: datetime) -> None:
        if self.corpus_start is None or when < self.corpus_start:
            self.corpus_start = when
        if self.corpus_end is None or when > self.corpus_end:
            self.corpus_end = when

    def merge(self, other: "ParseStats") -> None:
        self.files += other.files
        self.records += other.records
        self.bad_json += other.bad_json
        self.user_records += other.user_records
        self.rejected.update(other.rejected)
        self.accepted.update(other.accepted)
        self.queue_corrections += other.queue_corrections
        self.queue_max_shift_s = max(self.queue_max_shift_s, other.queue_max_shift_s)
        self.dedup_dropped += other.dedup_dropped
        self.synthetic_dropped += other.synthetic_dropped
        if other.corpus_start:
            self.see(other.corpus_start)
        if other.corpus_end:
            self.see(other.corpus_end)


def parse_ts(s: str) -> datetime:
    """ISO-8601 (UTC, trailing Z) -> tz-aware local datetime."""
    return datetime.fromisoformat(s.replace("Z", "+00:00")).astimezone(TZ)


def mangle(path: str | Path) -> str:
    """/Users/jyh/projects/claude/salt -> -Users-jyh-projects-claude-salt"""
    return str(path).rstrip("/").replace("/", "-")


def project_dir_for_repo(repo: str | Path) -> Path:
    return PROJECTS_ROOT / mangle(Path(repo).resolve())


def is_employer_lane(name: str) -> bool:
    return any(tag in name for tag in EMPLOYER_LANE)


def discover_personal_projects() -> list[Path]:
    """Every personal-lane project directory that holds a session transcript.

    Outside-lane directories are excluded here and nowhere else -- this is
    the only gate, and it is unconditional.
    """
    # ⛔ UNIONS ALL ROOTS — it must NOT switch to the seat roots. Compiler's
    # in-seat ground truth, 19:5x: its history is SPLIT, not moved —
    # ~/.claude/projects holds Aug 6 → Aug 8 08:23, the seat root holds 13:13
    # onward. Repointing would silently drop the majority of the campaign FROM
    # THE EARLY END, which is exactly the half the T0 rows depend on.
    # ✅ Union is safe from double-counting: the roots share ZERO session ids
    # (checked by identity, not by date range — adjacent ranges would have
    # looked the same and proved less).
    out = []
    for root in PROJECTS_ROOTS:
        for d in sorted(root.iterdir()):
            if not d.is_dir() or is_employer_lane(d.name):
                continue
            if not any(hint in d.name for hint in PERSONAL_LANE_HINTS):
                continue
            # scratchpad mirrors carry no human messages; skip the noise
            if "scratchpad" in d.name:
                continue
            if not list(d.glob("*.jsonl")):
                continue
            out.append(d)
    return out


def session_files(project_dir: Path) -> list[Path]:
    """Top-level session transcripts only (never subagent sidechains)."""
    return sorted(project_dir.glob("*.jsonl"))


def subagent_files(project_dir: Path) -> list[Path]:
    """Subagent / workflow-agent transcripts (sidechains)."""
    return sorted(project_dir.glob("*/subagents/**/agent-*.jsonl"))


def _iter_json(path: Path, stats: ParseStats):
    stats.files += 1
    with open(path, "r", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            stats.records += 1
            try:
                yield json.loads(line)
            except Exception:
                stats.bad_json += 1


def classify_user_record(rec: dict) -> tuple[str, str]:
    """Return (verdict, label). verdict is 'human' or 'reject'.

    Decision order -- provenance fields first, strings only as a fallback
    for records written before those fields existed:

      1. a tool result carried back to the model            -> reject
      2. a sidechain (subagent) record                      -> reject
      3. origin.kind == human                               -> HUMAN
      4. origin.kind in {task-notification, peer,
                         coordinator}                       -> reject
      5. isMeta and promptSource == system                  -> reject
         (loop ticks, cron pings, remote triggers)
      6. slash-command echo triple                          -> HUMAN
         (the human typed /model; the echo is the evidence)
      7. '[Request interrupted by user]'                    -> HUMAN
      8. legacy string patterns                             -> reject
      9. otherwise                                          -> HUMAN
         (counted separately as 'legacy-fallback')
    """
    if "toolUseResult" in rec:
        return "reject", "tool-result"
    if rec.get("isSidechain"):
        return "reject", "sidechain"

    origin_kind = (rec.get("origin") or {}).get("kind")
    if origin_kind == "human":
        return "human", "typed"
    if origin_kind in ("task-notification", "peer", "coordinator"):
        return "reject", origin_kind

    if rec.get("isMeta") and rec.get("promptSource") == "system":
        return "reject", "harness-injection"

    content = rec.get("message", {}).get("content")

    if isinstance(content, list):
        texts = [b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text"]
        joined = "\n".join(texts).strip()
        if joined == "[Request interrupted by user]":
            return "human", "interrupt"
        if any(isinstance(b, dict) and b.get("type") in ("image", "document") for b in content):
            return "human", "legacy-fallback"  # a pasted image is a human act
        content = joined

    if not isinstance(content, str):
        return "reject", "non-text"

    stripped = content.lstrip()
    if stripped.startswith("<command-name>"):
        return "human", "slash-command"
    for prefix, label in LEGACY_INJECTION_PREFIXES:
        if stripped.startswith(prefix):
            return "reject", label
    if "<<autonomous-loop" in stripped[:2000]:
        return "reject", "loop-tick"
    if not stripped:
        return "reject", "empty"

    if rec.get("promptSource") is not None or origin_kind is not None:
        # a modern record that reached here is a human message the
        # provenance fields did not label; treat as human but say so
        return "human", "legacy-fallback"
    return "human", "legacy-fallback"


def human_touches(project_dirs, stats: ParseStats | None = None) -> tuple[list[Touch], ParseStats]:
    """Every human touch across the given seats, sorted by time.

    Only top-level session transcripts are read. Subagent transcripts are
    excluded by construction: a subagent's prompt is written by an agent,
    never by a person.
    """
    stats = stats or ParseStats()
    touches: list[Touch] = []
    for pdir in project_dirs:
        pdir = Path(pdir)
        if is_employer_lane(pdir.name):
            raise ValueError(f"refusing to read outside-lane transcripts: {pdir.name}")
        for path in session_files(pdir):
            enqueues: dict[str, list[datetime]] = {}
            pending: list[tuple[Touch, str]] = []
            for rec in _iter_json(path, stats):
                rtype = rec.get("type")
                if rec.get("timestamp"):
                    stats.see(parse_ts(rec["timestamp"]))
                if rtype == "queue-operation" and rec.get("operation") == "enqueue":
                    content = rec.get("content")
                    if isinstance(content, str):
                        enqueues.setdefault(content, []).append(parse_ts(rec["timestamp"]))
                    continue
                if rtype != "user":
                    continue
                stats.user_records += 1
                verdict, label = classify_user_record(rec)
                if verdict != "human":
                    stats.rejected[label] += 1
                    continue
                ts_raw = rec.get("timestamp")
                if not ts_raw:
                    stats.rejected["no-timestamp"] += 1
                    continue
                content = rec.get("message", {}).get("content")
                text = content if isinstance(content, str) else ""
                touch = Touch(
                    when=parse_ts(ts_raw),
                    kind=label,
                    project=pdir.name,
                    session=path.stem,
                    chars=len(text),
                )
                stats.accepted[label] += 1
                pending.append((touch, text))

            # A message typed while the model was busy is written to the
            # transcript when it is dequeued. The enqueue record carries the
            # moment the human actually typed it; prefer that.
            for touch, text in pending:
                cands = enqueues.get(text)
                if cands:
                    best = min(cands, key=lambda t: abs((touch.when - t).total_seconds()))
                    shift = (touch.when - best).total_seconds()
                    if 0 < shift < 3600:
                        stats.queue_corrections += 1
                        stats.queue_max_shift_s = max(stats.queue_max_shift_s, shift)
                        touch.when = best
                touches.append(touch)

    touches.sort(key=lambda t: t.when)
    return touches, stats


MODEL_TIERS = (
    ("opus-5", "Opus 5"),
    ("opus-4-8", "Opus 4.8"),
    ("opus", "Opus (other)"),
    ("fable", "Fable 5"),
    ("sonnet", "Sonnet 5"),
    ("haiku", "Haiku 4.5"),
)


def model_tier(model: str) -> str:
    m = (model or "").lower()
    for key, label in MODEL_TIERS:
        if key in m:
            return label
    return model or "unknown"


def usage_events(
    project_dirs,
    include_subagents: bool = True,
    stats: ParseStats | None = None,
) -> tuple[list[UsageEvent], ParseStats]:
    """Every API request, deduplicated.

    THE DEDUP RULE, AND WHY IT MATTERS. Claude Code writes one assistant
    record per content block, and every record of a single API response
    repeats that response's whole ``usage`` block. Measured on this
    machine: 26 assistant records carried 9 distinct requestIds, with
    byte-identical usage inside each group. Summing records instead of
    requests inflates every token figure by roughly 3x. Events are keyed
    by ``requestId`` (falling back to the API ``message.id``) and counted
    once.

    ``<synthetic>`` records -- API errors and client-side notices -- carry
    all-zero usage and are dropped, counted separately.
    """
    stats = stats or ParseStats()
    seen: set[str] = set()
    events: list[UsageEvent] = []
    for pdir in project_dirs:
        pdir = Path(pdir)
        if is_employer_lane(pdir.name):
            raise ValueError(f"refusing to read outside-lane transcripts: {pdir.name}")
        paths = [(p, False) for p in session_files(pdir)]
        if include_subagents:
            paths += [(p, True) for p in subagent_files(pdir)]
        for path, is_sub in paths:
            for rec in _iter_json(path, stats):
                if rec.get("type") != "assistant":
                    continue
                msg = rec.get("message", {}) or {}
                model = msg.get("model") or ""
                if model == "<synthetic>":
                    stats.synthetic_dropped += 1
                    continue
                key = rec.get("requestId") or msg.get("id")
                if not key:
                    key = f"{path.name}:{rec.get('uuid')}"
                if key in seen:
                    stats.dedup_dropped += 1
                    continue
                seen.add(key)
                usage = msg.get("usage") or {}
                ts_raw = rec.get("timestamp")
                if not ts_raw:
                    continue
                events.append(
                    UsageEvent(
                        when=parse_ts(ts_raw),
                        project=pdir.name,
                        model=model,
                        tier=model_tier(model),
                        input_tokens=int(usage.get("input_tokens") or 0),
                        output_tokens=int(usage.get("output_tokens") or 0),
                        cache_creation=int(usage.get("cache_creation_input_tokens") or 0),
                        cache_read=int(usage.get("cache_read_input_tokens") or 0),
                        session=path.stem,
                        subagent=is_sub,
                        effort=rec.get("effort") or "",
                    )
                )
    events.sort(key=lambda e: e.when)
    return events, stats


# ---------------------------------------------------------------------------
# git
# ---------------------------------------------------------------------------


@dataclass
class Commit:
    when: datetime
    sha: str
    subject: str
    insertions: int = 0
    ext_insertions: int = 0  # insertions in files matching the tracked extension


def git_commits(
    repo: str | Path,
    since: str,
    until: str | None = None,
    ext: str = ".lean",
) -> list[Commit]:
    """Commits in [since, until), newest last, with insertion counts.

    ``since``/``until`` MUST carry an explicit time. ``--since='2026-07-23'``
    without one is parsed as UTC and silently drops commits (measured in the
    leg-1 harvest: 654 vs 712 over the same nominal window).
    """
    repo = str(Path(repo).resolve())
    args = [
        "git",
        "-C",
        repo,
        "log",
        f"--since={since}",
        "--numstat",
        "--date=format-local:%Y-%m-%dT%H:%M:%S%z",
        "--format=@@%H|%ad|%s",
        "--no-merges",
    ]
    if until:
        args.insert(6, f"--until={until}")
    env = dict(os.environ, TZ="America/Los_Angeles")
    out = subprocess.run(args, capture_output=True, text=True, env=env, check=True).stdout

    commits: list[Commit] = []
    cur: Commit | None = None
    for line in out.splitlines():
        if line.startswith("@@"):
            sha, ad, subject = line[2:].split("|", 2)
            cur = Commit(when=datetime.fromisoformat(ad).astimezone(TZ), sha=sha, subject=subject)
            commits.append(cur)
            continue
        if not line.strip() or cur is None:
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        added, _removed, path = parts
        if added == "-":
            continue  # binary
        n = int(added)
        cur.insertions += n
        if path.endswith(ext):
            cur.ext_insertions += n
    commits.sort(key=lambda c: c.when)
    return commits


# a ceremonial seat prefix: "play M: ", "saltworks: ", "evidence: "
PREFIX_RE = re.compile(r"^[A-Za-z][\w .+-]{0,20}:\s+")
TAG_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9'.’-]*)")
STOPWORDS = {"THE", "A", "AN", "OUR", "ITS"}


def wave_label(subject: str) -> str:
    """A coarse wave tag from a commit subject.

    Waves in this fleet are named in the subject line -- ``N4B-W2c(...)``,
    ``WEIL-TRIO W4-e ...``, ``THE PEARL --- ...`` -- usually behind a
    ceremonial seat prefix (``play M: ``, ``saltworks: ``). This strips up
    to two such prefixes and takes the leading token, keeping a second
    word when the first is an article. It is deliberately dumb: a grouping
    aid for the token table, not a measured quantity.
    """
    s = subject.strip()
    for _ in range(2):
        m = PREFIX_RE.match(s)
        if not m:
            break
        s = s[m.end():]
    m = TAG_RE.match(s)
    if not m:
        return "(unlabelled)"
    tag = m.group(1)
    if tag.upper() in STOPWORDS:
        rest = s[len(tag):].lstrip()
        m2 = TAG_RE.match(rest)
        if m2:
            tag = f"{tag} {m2.group(1)}"
    if len(tag) < 2:
        return "(unlabelled)"
    return tag


def fmt_int(n: int | float) -> str:
    return f"{int(n):,}"


def fmt_hours(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    return f"{h}h {m:02d}m"


def fmt_dur_h(seconds: float) -> str:
    """A duration that CANNOT round across a bucket boundary.

    §2 of the silence ledger buckets at 1 / 2 / 4 / 8 / 12 h. The old form
    here was ``f"{seconds/3600:.1f} h"``, which printed a **59.14-minute**
    window as **"1.0 h"** in §4 beside a ``≥ 1 h → 0 commits`` row computed
    from the same run. Two correct tables that read as contradicting each
    other — measured 2026-08-06, when the campaign's longest window to date
    came in at 0.9856 h and **missed the headline bucket by 51 seconds**.

    Below an hour the unit is minutes; at or above it, hours and minutes are
    printed exactly. Both branches TRUNCATE, so a duration is never rounded
    UP into a threshold it did not reach.
    """
    if seconds < 3600:
        return f"{int(seconds // 60)} min"
    return fmt_hours(seconds)


# --- record coverage: is a silence MEASURED, or merely UNRECORDED? ---------
#
# Charter §E is "unobserved ≠ silent", and until 2026-08-06 this code modelled
# it in one direction only: a commit PREDATING the earliest readable
# transcript is excluded from every share. The laptop→Mac-Mini migration that
# afternoon produced the other direction — a hole in the MIDDLE. The runbook
# re-synced the repos and the kit before cutover but not `~/.claude/`, so the
# transcript record stopped at 14:07:56 while git carried work to 14:30:08.
# The ledger read the difference as the campaign's longest silence window.
#
# THE RULE THAT SEPARATES THEM NEEDS NO NEW DATA: a commit is made BY a
# session, and a session writes records. So a commit sitting in a stretch
# where NO personal-lane session wrote anything at all is proof of a hole in
# the record — not evidence that nobody was directing.
#
# CALIBRATED BEFORE IT WAS SHIPPED, over 862 commits spanning the whole leg-1
# harvest window and the campaign to date:
#
#     median  0.4 s      p90  2.2 s      p99  5.1 s
#     largest normal commit   3.08 min
#     the migration hole     22.19 min
#
# The default 5-minute tolerance therefore sits in a MEASURED VOID — above
# every one of the 861 normal commits and 7× below the one real hole. It
# flagged exactly 1 of 862, and that one was identified independently first.

RECORD_TOL_S = 300

# Compact (`"timestamp":"…"`) is what the harness writes; the spaced form is
# what `json.dump` writes, which is what the SELF-TEST fixtures are made of.
# The first version of this scanner matched the compact form with `str.find`
# and returned an EMPTY trace on the fixtures — i.e. "no holes found",
# cheerfully, from a parser that had matched nothing at all. That is the day-1
# failure mode in the very instrument written to catch it, so the guard below
# is not decoration: a scan that reads lines and extracts no stamp RAISES.
_TS_RE = re.compile(r'"timestamp"\s*:\s*"([^"]{19,32})"')


def activity_trace(project_dirs) -> list[datetime]:
    """Every moment ANY personal-lane session wrote a record, of any type.

    Human or harness, session or subagent — this is liveness, not presence.
    Timestamps are lifted with ``str.find`` rather than ``json.loads``: it is
    a full scan of ~2 GB, the field is a fixed prefix, and — the part that
    matters — **nothing here interprets the record, so nothing here can
    misclassify one.** The classification questions all live in
    :func:`classify_user_record`; this function deliberately asks none of
    them.
    """
    raw: list[str] = []
    lines_read = 0
    for d in project_dirs:
        if is_employer_lane(Path(d).name):  # the firewall, restated locally
            continue
        for f in list(session_files(Path(d))) + list(subagent_files(Path(d))):
            with open(f, "r", errors="replace") as fh:
                for line in fh:
                    lines_read += 1
                    m = _TS_RE.search(line)
                    if m:
                        raw.append(m.group(1))
    if lines_read and not raw:
        raise ValueError(
            "activity_trace read %d transcript lines and extracted ZERO "
            "timestamps — the record format has changed and this detector is "
            "silently blind. It must fail loudly rather than report 'no holes'."
            % lines_read)
    raw.sort()
    out: list[datetime] = []
    for s in raw:
        try:
            out.append(parse_ts(s))
        except Exception:
            continue  # a malformed stamp is one fewer witness, never a false one
    out.sort()
    return out


def record_distances(commits, trace: list[datetime]) -> list[tuple]:
    """``[(commit, seconds_to_nearest_record)]`` for EVERY commit, in order.

    An empty trace puts every commit at infinity: with no record at all,
    nothing is observed, and the honest report is "all of it", not "none".
    """
    import bisect

    out = []
    for c in commits:
        if not trace:
            out.append((c, float("inf")))
            continue
        i = bisect.bisect_left(trace, c.when)
        before = (c.when - trace[i - 1]).total_seconds() if i > 0 else float("inf")
        after = (trace[i] - c.when).total_seconds() if i < len(trace) else float("inf")
        out.append((c, min(before, after)))
    return out


def unrecorded_commits(commits, trace: list[datetime], tol_s: float = RECORD_TOL_S):
    """``[(commit, seconds)]`` for the commits whose nearest record is a hole."""
    return [(c, d) for c, d in record_distances(commits, trace) if d > tol_s]


def separation(distances: list[float], tol_s: float = RECORD_TOL_S) -> dict:
    """The live calibration: does the tolerance still sit in an empty region?

    A threshold is only honest while the data it separates stays separated.
    This recomputes, on every run, the gap between the worst commit BELOW the
    tolerance and the best one above it — so the number in the report is
    measured by the run that prints it and can never go stale. The frozen
    2026-08-06 baseline is kept in the module docstring above for comparison;
    this is what the current corpus says.
    """
    below = sorted(d for d in distances if d <= tol_s)
    above = sorted(d for d in distances if d > tol_s)

    def pct(p):
        if not below:
            return None
        return below[min(len(below) - 1, int(p * (len(below) - 1)))]

    return {
        "n": len(distances),
        "n_below": len(below),
        "n_above": len(above),
        "median": pct(0.5),
        "p99": pct(0.99),
        "worst_below": below[-1] if below else None,
        "best_above": above[0] if above else None,
    }


def rejection_table(stats: ParseStats) -> str:
    """The Amendment-2 disclosure block, rendered as markdown."""
    lines = [
        "| Record class | Verdict | Count |",
        "|---|---|---:|",
    ]
    for label, n in sorted(stats.accepted.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{label}` | **counted as human** | {fmt_int(n)} |")
    for label, n in sorted(stats.rejected.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{label}` | rejected | {fmt_int(n)} |")
    return "\n".join(lines)


def now_local() -> datetime:
    return datetime.now(TZ)


def iso_local(dt: datetime) -> str:
    return dt.astimezone(TZ).strftime("%Y-%m-%d %H:%M")


def day_local(dt: datetime) -> str:
    return dt.astimezone(TZ).strftime("%Y-%m-%d")


def write_atomic(path: str | Path, text: str) -> Path:
    """Publish ``text`` at ``path`` by RENAME, never by truncating in place.

    THE WRITE IDIOM FOLLOWS THE READER (fleet law, 2026-08-09). Every report
    this kit emits is consumed by SNAPSHOT readers -- the maestro's rsync to
    ``seat/``, a council read, a git add -- which open the file by NAME at a
    point in time. ``Path.write_text`` truncates first and fills after, so such
    a reader can observe an empty or half-written report that is
    indistinguishable from a finished one. ``os.replace`` is atomic within a
    filesystem: the reader gets the previous COMPLETE file or the new one.

    The temp name carries the pid so two concurrent runs cannot share it, and
    it is written beside the target (not in /tmp) because a rename across
    filesystems is not atomic and would silently degrade to a copy.
    """
    path = Path(path).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp{os.getpid()}")
    try:
        tmp.write_text(text, encoding="utf-8")
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)     # never leave a partial temp behind
        raise
    return path
