"""Shared transcript + git parser for the campaign ledger tools.

Owner: the EVIDENCE seat. Charter: docs/measurement-preregistration.md
(frozen 2026-08-06, Council I) and its dated addenda.

This module is the single place where a session transcript record is
classified as "a human typed this" or "the harness injected this". Both
the silence-window ledger and the token meter import it, so the two
published tables can never disagree about who was present.

METHODOLOGY, IN ONE PARAGRAPH
-----------------------------
Claude Code writes one JSONL record per event under
``~/.claude/projects/<mangled-cwd>/``. Records with ``"type": "user"``
are NOT all human: agent-completion notices, loop-timer ticks, cron
pings, peer-seat messages and context-compaction summaries are all
injected with ``role: "user"``. Counting them as human presence is the
error caught in salt triple-campaign Amendment 2 (it moved the >=1h
silence share from 0.3% to 21.5%). This module rejects them by the
record's own provenance fields -- ``origin.kind``, ``promptSource`` and
``isMeta`` -- and falls back to string patterns only for records written
by older clients that predate those fields. Every rejection is counted
and printed, so the filter is auditable from the published table.

THE FIREWALL
------------
Employer-lane projects (``loca``, ``holl``) are never read. Not by
default, not behind a flag -- the denylist is enforced in code, and the
consequence is stated in the output: silence here means "no human
direction reached the personal-lane fleet", never "the human was
asleep".
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

TZ = ZoneInfo("America/Los_Angeles")
PROJECTS_ROOT = Path.home() / ".claude" / "projects"

# --- the firewall (portfolio CLAUDE.md, JYH-ratified 2026-07-21) -----------
# Outside-lane material never enters a personal-lane artifact. These are
# matched against the project directory name; the check is substring-based
# and deliberately blunt.
EMPLOYER_LANE = ("-claude-loca", "-claude-holl")

# Personal-lane repos whose seats can carry human presence. A seat not in
# this list is still readable if named explicitly on the command line,
# unless it is employer-lane.
PERSONAL_LANE_HINTS = (
    "-claude-salt",
    "-claude-saltworks",
    "-claude-jas",
    "-claude-mandelbrot",
    "-claude-metaprl",
    "-claude-libmojave",
    "-claude-omake",
    "-claude-jacobian-gist",
)

# ---------------------------------------------------------------------------
# provenance classification
# ---------------------------------------------------------------------------

# String prefixes that identify a harness injection in records written
# before ``origin``/``promptSource`` existed. Order matters only for the
# label that gets reported.
LEGACY_INJECTION_PREFIXES = (
    ("<task-notification>", "task-notification"),
    ("<system-reminder>", "system-reminder"),
    ("[SYSTEM NOTIFICATION", "task-notification"),
    ("# Autonomous loop", "loop-tick"),
    ("Another Claude session sent a message:", "peer-message"),
    ("This session is being continued from a previous conversation", "compaction-summary"),
    ("Caveat: The messages below were generated by the user", "slash-command-echo"),
    ("<local-command-caveat>", "slash-command-echo"),
    ("<local-command-stdout>", "slash-command-echo"),
    ("<bash-input>", "bash-mode"),
    ("<bash-stdout>", "bash-mode"),
    ("<bash-stderr>", "bash-mode"),
)

# Human touches we count. ``typed`` is a message the human wrote;
# ``slash-command`` is a command they invoked (/model, /login -- proof of a
# hand on the keyboard); ``interrupt`` is an ESC press mid-response.
HUMAN_KINDS = ("typed", "slash-command", "interrupt", "legacy-fallback")


@dataclass
class Touch:
    """One moment at which a human demonstrably touched a seat."""

    when: datetime  # tz-aware, America/Los_Angeles
    kind: str  # one of HUMAN_KINDS
    project: str  # project directory name
    session: str
    chars: int = 0


@dataclass
class UsageEvent:
    """One API request, deduplicated by requestId."""

    when: datetime
    project: str
    model: str
    tier: str
    input_tokens: int
    output_tokens: int
    cache_creation: int
    cache_read: int
    session: str
    subagent: bool
    effort: str = ""


@dataclass
class ParseStats:
    """Everything the filter threw away, so the filter can be audited."""

    files: int = 0
    records: int = 0
    bad_json: int = 0
    user_records: int = 0
    rejected: Counter = field(default_factory=Counter)
    accepted: Counter = field(default_factory=Counter)
    queue_corrections: int = 0
    queue_max_shift_s: float = 0.0
    dedup_dropped: int = 0
    synthetic_dropped: int = 0
    # earliest / latest timestamp of ANY record in the transcripts read.
    # Outside [corpus_start, corpus_end] nothing is observed, and a
    # silence window there is unmeasured rather than long.
    corpus_start: datetime | None = None
    corpus_end: datetime | None = None

    def see(self, when: datetime) -> None:
        if self.corpus_start is None or when < self.corpus_start:
            self.corpus_start = when
        if self.corpus_end is None or when > self.corpus_end:
            self.corpus_end = when

    def merge(self, other: "ParseStats") -> None:
        self.files += other.files
        self.records += other.records
        self.bad_json += other.bad_json
        self.user_records += other.user_records
        self.rejected.update(other.rejected)
        self.accepted.update(other.accepted)
        self.queue_corrections += other.queue_corrections
        self.queue_max_shift_s = max(self.queue_max_shift_s, other.queue_max_shift_s)
        self.dedup_dropped += other.dedup_dropped
        self.synthetic_dropped += other.synthetic_dropped
        if other.corpus_start:
            self.see(other.corpus_start)
        if other.corpus_end:
            self.see(other.corpus_end)


def parse_ts(s: str) -> datetime:
    """ISO-8601 (UTC, trailing Z) -> tz-aware local datetime."""
    return datetime.fromisoformat(s.replace("Z", "+00:00")).astimezone(TZ)


def mangle(path: str | Path) -> str:
    """/Users/jyh/projects/claude/salt -> -Users-jyh-projects-claude-salt"""
    return str(path).rstrip("/").replace("/", "-")


def project_dir_for_repo(repo: str | Path) -> Path:
    return PROJECTS_ROOT / mangle(Path(repo).resolve())


def is_employer_lane(name: str) -> bool:
    return any(tag in name for tag in EMPLOYER_LANE)


def discover_personal_projects() -> list[Path]:
    """Every personal-lane project directory that holds a session transcript.

    Outside-lane directories are excluded here and nowhere else -- this is
    the only gate, and it is unconditional.
    """
    out = []
    if not PROJECTS_ROOT.is_dir():
        return out
    for d in sorted(PROJECTS_ROOT.iterdir()):
        if not d.is_dir() or is_employer_lane(d.name):
            continue
        if not any(hint in d.name for hint in PERSONAL_LANE_HINTS):
            continue
        # scratchpad mirrors carry no human messages; skip the noise
        if "scratchpad" in d.name:
            continue
        if not list(d.glob("*.jsonl")):
            continue
        out.append(d)
    return out


def session_files(project_dir: Path) -> list[Path]:
    """Top-level session transcripts only (never subagent sidechains)."""
    return sorted(project_dir.glob("*.jsonl"))


def subagent_files(project_dir: Path) -> list[Path]:
    """Subagent / workflow-agent transcripts (sidechains)."""
    return sorted(project_dir.glob("*/subagents/**/agent-*.jsonl"))


def _iter_json(path: Path, stats: ParseStats):
    stats.files += 1
    with open(path, "r", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            stats.records += 1
            try:
                yield json.loads(line)
            except Exception:
                stats.bad_json += 1


def classify_user_record(rec: dict) -> tuple[str, str]:
    """Return (verdict, label). verdict is 'human' or 'reject'.

    Decision order -- provenance fields first, strings only as a fallback
    for records written before those fields existed:

      1. a tool result carried back to the model            -> reject
      2. a sidechain (subagent) record                      -> reject
      3. origin.kind == human                               -> HUMAN
      4. origin.kind in {task-notification, peer,
                         coordinator}                       -> reject
      5. isMeta and promptSource == system                  -> reject
         (loop ticks, cron pings, remote triggers)
      6. slash-command echo triple                          -> HUMAN
         (the human typed /model; the echo is the evidence)
      7. '[Request interrupted by user]'                    -> HUMAN
      8. legacy string patterns                             -> reject
      9. otherwise                                          -> HUMAN
         (counted separately as 'legacy-fallback')
    """
    if "toolUseResult" in rec:
        return "reject", "tool-result"
    if rec.get("isSidechain"):
        return "reject", "sidechain"

    origin_kind = (rec.get("origin") or {}).get("kind")
    if origin_kind == "human":
        return "human", "typed"
    if origin_kind in ("task-notification", "peer", "coordinator"):
        return "reject", origin_kind

    if rec.get("isMeta") and rec.get("promptSource") == "system":
        return "reject", "harness-injection"

    content = rec.get("message", {}).get("content")

    if isinstance(content, list):
        texts = [b.get("text", "") for b in content if isinstance(b, dict) and b.get("type") == "text"]
        joined = "\n".join(texts).strip()
        if joined == "[Request interrupted by user]":
            return "human", "interrupt"
        if any(isinstance(b, dict) and b.get("type") in ("image", "document") for b in content):
            return "human", "legacy-fallback"  # a pasted image is a human act
        content = joined

    if not isinstance(content, str):
        return "reject", "non-text"

    stripped = content.lstrip()
    if stripped.startswith("<command-name>"):
        return "human", "slash-command"
    for prefix, label in LEGACY_INJECTION_PREFIXES:
        if stripped.startswith(prefix):
            return "reject", label
    if "<<autonomous-loop" in stripped[:2000]:
        return "reject", "loop-tick"
    if not stripped:
        return "reject", "empty"

    if rec.get("promptSource") is not None or origin_kind is not None:
        # a modern record that reached here is a human message the
        # provenance fields did not label; treat as human but say so
        return "human", "legacy-fallback"
    return "human", "legacy-fallback"


def human_touches(project_dirs, stats: ParseStats | None = None) -> tuple[list[Touch], ParseStats]:
    """Every human touch across the given seats, sorted by time.

    Only top-level session transcripts are read. Subagent transcripts are
    excluded by construction: a subagent's prompt is written by an agent,
    never by a person.
    """
    stats = stats or ParseStats()
    touches: list[Touch] = []
    for pdir in project_dirs:
        pdir = Path(pdir)
        if is_employer_lane(pdir.name):
            raise ValueError(f"refusing to read outside-lane transcripts: {pdir.name}")
        for path in session_files(pdir):
            enqueues: dict[str, list[datetime]] = {}
            pending: list[tuple[Touch, str]] = []
            for rec in _iter_json(path, stats):
                rtype = rec.get("type")
                if rec.get("timestamp"):
                    stats.see(parse_ts(rec["timestamp"]))
                if rtype == "queue-operation" and rec.get("operation") == "enqueue":
                    content = rec.get("content")
                    if isinstance(content, str):
                        enqueues.setdefault(content, []).append(parse_ts(rec["timestamp"]))
                    continue
                if rtype != "user":
                    continue
                stats.user_records += 1
                verdict, label = classify_user_record(rec)
                if verdict != "human":
                    stats.rejected[label] += 1
                    continue
                ts_raw = rec.get("timestamp")
                if not ts_raw:
                    stats.rejected["no-timestamp"] += 1
                    continue
                content = rec.get("message", {}).get("content")
                text = content if isinstance(content, str) else ""
                touch = Touch(
                    when=parse_ts(ts_raw),
                    kind=label,
                    project=pdir.name,
                    session=path.stem,
                    chars=len(text),
                )
                stats.accepted[label] += 1
                pending.append((touch, text))

            # A message typed while the model was busy is written to the
            # transcript when it is dequeued. The enqueue record carries the
            # moment the human actually typed it; prefer that.
            for touch, text in pending:
                cands = enqueues.get(text)
                if cands:
                    best = min(cands, key=lambda t: abs((touch.when - t).total_seconds()))
                    shift = (touch.when - best).total_seconds()
                    if 0 < shift < 3600:
                        stats.queue_corrections += 1
                        stats.queue_max_shift_s = max(stats.queue_max_shift_s, shift)
                        touch.when = best
                touches.append(touch)

    touches.sort(key=lambda t: t.when)
    return touches, stats


MODEL_TIERS = (
    ("opus-5", "Opus 5"),
    ("opus-4-8", "Opus 4.8"),
    ("opus", "Opus (other)"),
    ("fable", "Fable 5"),
    ("sonnet", "Sonnet 5"),
    ("haiku", "Haiku 4.5"),
)


def model_tier(model: str) -> str:
    m = (model or "").lower()
    for key, label in MODEL_TIERS:
        if key in m:
            return label
    return model or "unknown"


def usage_events(
    project_dirs,
    include_subagents: bool = True,
    stats: ParseStats | None = None,
) -> tuple[list[UsageEvent], ParseStats]:
    """Every API request, deduplicated.

    THE DEDUP RULE, AND WHY IT MATTERS. Claude Code writes one assistant
    record per content block, and every record of a single API response
    repeats that response's whole ``usage`` block. Measured on this
    machine: 26 assistant records carried 9 distinct requestIds, with
    byte-identical usage inside each group. Summing records instead of
    requests inflates every token figure by roughly 3x. Events are keyed
    by ``requestId`` (falling back to the API ``message.id``) and counted
    once.

    ``<synthetic>`` records -- API errors and client-side notices -- carry
    all-zero usage and are dropped, counted separately.
    """
    stats = stats or ParseStats()
    seen: set[str] = set()
    events: list[UsageEvent] = []
    for pdir in project_dirs:
        pdir = Path(pdir)
        if is_employer_lane(pdir.name):
            raise ValueError(f"refusing to read outside-lane transcripts: {pdir.name}")
        paths = [(p, False) for p in session_files(pdir)]
        if include_subagents:
            paths += [(p, True) for p in subagent_files(pdir)]
        for path, is_sub in paths:
            for rec in _iter_json(path, stats):
                if rec.get("type") != "assistant":
                    continue
                msg = rec.get("message", {}) or {}
                model = msg.get("model") or ""
                if model == "<synthetic>":
                    stats.synthetic_dropped += 1
                    continue
                key = rec.get("requestId") or msg.get("id")
                if not key:
                    key = f"{path.name}:{rec.get('uuid')}"
                if key in seen:
                    stats.dedup_dropped += 1
                    continue
                seen.add(key)
                usage = msg.get("usage") or {}
                ts_raw = rec.get("timestamp")
                if not ts_raw:
                    continue
                events.append(
                    UsageEvent(
                        when=parse_ts(ts_raw),
                        project=pdir.name,
                        model=model,
                        tier=model_tier(model),
                        input_tokens=int(usage.get("input_tokens") or 0),
                        output_tokens=int(usage.get("output_tokens") or 0),
                        cache_creation=int(usage.get("cache_creation_input_tokens") or 0),
                        cache_read=int(usage.get("cache_read_input_tokens") or 0),
                        session=path.stem,
                        subagent=is_sub,
                        effort=rec.get("effort") or "",
                    )
                )
    events.sort(key=lambda e: e.when)
    return events, stats


# ---------------------------------------------------------------------------
# git
# ---------------------------------------------------------------------------


@dataclass
class Commit:
    when: datetime
    sha: str
    subject: str
    insertions: int = 0
    ext_insertions: int = 0  # insertions in files matching the tracked extension


def git_commits(
    repo: str | Path,
    since: str,
    until: str | None = None,
    ext: str = ".lean",
) -> list[Commit]:
    """Commits in [since, until), newest last, with insertion counts.

    ``since``/``until`` MUST carry an explicit time. ``--since='2026-07-23'``
    without one is parsed as UTC and silently drops commits (measured in the
    leg-1 harvest: 654 vs 712 over the same nominal window).
    """
    repo = str(Path(repo).resolve())
    args = [
        "git",
        "-C",
        repo,
        "log",
        f"--since={since}",
        "--numstat",
        "--date=format-local:%Y-%m-%dT%H:%M:%S%z",
        "--format=@@%H|%ad|%s",
        "--no-merges",
    ]
    if until:
        args.insert(6, f"--until={until}")
    env = dict(os.environ, TZ="America/Los_Angeles")
    out = subprocess.run(args, capture_output=True, text=True, env=env, check=True).stdout

    commits: list[Commit] = []
    cur: Commit | None = None
    for line in out.splitlines():
        if line.startswith("@@"):
            sha, ad, subject = line[2:].split("|", 2)
            cur = Commit(when=datetime.fromisoformat(ad).astimezone(TZ), sha=sha, subject=subject)
            commits.append(cur)
            continue
        if not line.strip() or cur is None:
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        added, _removed, path = parts
        if added == "-":
            continue  # binary
        n = int(added)
        cur.insertions += n
        if path.endswith(ext):
            cur.ext_insertions += n
    commits.sort(key=lambda c: c.when)
    return commits


# a ceremonial seat prefix: "play M: ", "saltworks: ", "evidence: "
PREFIX_RE = re.compile(r"^[A-Za-z][\w .+-]{0,20}:\s+")
TAG_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9'.’-]*)")
STOPWORDS = {"THE", "A", "AN", "OUR", "ITS"}


def wave_label(subject: str) -> str:
    """A coarse wave tag from a commit subject.

    Waves in this fleet are named in the subject line -- ``N4B-W2c(...)``,
    ``WEIL-TRIO W4-e ...``, ``THE PEARL --- ...`` -- usually behind a
    ceremonial seat prefix (``play M: ``, ``saltworks: ``). This strips up
    to two such prefixes and takes the leading token, keeping a second
    word when the first is an article. It is deliberately dumb: a grouping
    aid for the token table, not a measured quantity.
    """
    s = subject.strip()
    for _ in range(2):
        m = PREFIX_RE.match(s)
        if not m:
            break
        s = s[m.end():]
    m = TAG_RE.match(s)
    if not m:
        return "(unlabelled)"
    tag = m.group(1)
    if tag.upper() in STOPWORDS:
        rest = s[len(tag):].lstrip()
        m2 = TAG_RE.match(rest)
        if m2:
            tag = f"{tag} {m2.group(1)}"
    if len(tag) < 2:
        return "(unlabelled)"
    return tag


def fmt_int(n: int | float) -> str:
    return f"{int(n):,}"


def fmt_hours(seconds: float) -> str:
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    return f"{h}h {m:02d}m"


def fmt_dur_h(seconds: float) -> str:
    return f"{seconds / 3600:.1f} h"


def rejection_table(stats: ParseStats) -> str:
    """The Amendment-2 disclosure block, rendered as markdown."""
    lines = [
        "| Record class | Verdict | Count |",
        "|---|---|---:|",
    ]
    for label, n in sorted(stats.accepted.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{label}` | **counted as human** | {fmt_int(n)} |")
    for label, n in sorted(stats.rejected.items(), key=lambda kv: -kv[1]):
        lines.append(f"| `{label}` | rejected | {fmt_int(n)} |")
    return "\n".join(lines)


def now_local() -> datetime:
    return datetime.now(TZ)


def iso_local(dt: datetime) -> str:
    return dt.astimezone(TZ).strftime("%Y-%m-%d %H:%M")


def day_local(dt: datetime) -> str:
    return dt.astimezone(TZ).strftime("%Y-%m-%d")
