-- GENERATED by SaltWorks/Silicon/Importer/import_netlist.py
-- source: comparator_nl.v
-- DO NOT EDIT. The generator is UNTRUSTED; this datum is checked
-- per-instance by the importer's round-trip census, and its cell
-- expansions are proved against Liberty in SaltWorks.Silicon.Cells.Sky130.
import SaltWorks.Silicon.Equiv.BitSliced

namespace SaltWorks.Silicon.Imported

/-- comparatorNL: 127 gates, 16 primary inputs. -/
def comparatorNL : SaltWorks.Silicon.Netlist := [
  .inp 0,
  .inp 1,
  .inp 2,
  .inp 3,
  .inp 4,
  .inp 5,
  .inp 6,
  .inp 7,
  .inp 8,
  .inp 9,
  .inp 10,
  .inp 11,
  .inp 12,
  .inp 13,
  .inp 14,
  .inp 15,
  .not 15,
  .not 16,
  .not 7,
  .or 17 18,
  .not 14,
  .and 6 20,
  .not 13,
  .and 5 22,
  .not 4,
  .and 12 24,
  .not 5,
  .and 26 13,
  .or 25 27,
  .not 28,
  .or 12 24,
  .not 3,
  .and 11 31,
  .not 2,
  .and 10 33,
  .not 34,
  .not 1,
  .and 9 36,
  .not 37,
  .and 35 38,
  .or 9 36,
  .not 0,
  .or 41 8,
  .and 40 42,
  .not 43,
  .and 39 44,
  .not 3,
  .or 11 46,
  .or 10 33,
  .and 47 48,
  .not 49,
  .or 45 50,
  .not 51,
  .or 32 52,
  .and 30 53,
  .not 54,
  .and 29 55,
  .or 21 23,
  .or 57 56,
  .not 58,
  .or 16 7,
  .or 6 20,
  .and 60 61,
  .not 62,
  .or 59 63,
  .and 19 64,
  .not 65,
  .not 66,
  .and 0 67,
  .and 8 66,
  .or 68 69,
  .not 66,
  .and 1 71,
  .and 9 66,
  .or 72 73,
  .not 66,
  .and 2 75,
  .and 10 66,
  .or 76 77,
  .not 66,
  .and 3 79,
  .and 11 66,
  .or 80 81,
  .not 66,
  .and 4 83,
  .and 12 66,
  .or 84 85,
  .not 66,
  .and 26 87,
  .and 22 66,
  .or 88 89,
  .not 90,
  .not 66,
  .and 6 92,
  .and 14 66,
  .or 93 94,
  .and 15 7,
  .not 66,
  .and 8 97,
  .and 0 66,
  .or 98 99,
  .not 66,
  .and 9 101,
  .and 1 66,
  .or 102 103,
  .not 66,
  .and 10 105,
  .and 2 66,
  .or 106 107,
  .not 66,
  .and 11 109,
  .and 3 66,
  .or 110 111,
  .not 66,
  .and 12 113,
  .and 4 66,
  .or 114 115,
  .not 66,
  .and 22 117,
  .and 26 66,
  .or 118 119,
  .not 120,
  .not 66,
  .and 14 122,
  .and 6 66,
  .or 123 124,
  .or 15 7
]

/-- Output net indices, in the CALLER'S `--outputs` order (then state,
then cuts). NOT declaration order — this importer discards that. -/
def comparatorNL_outs : List Nat := [70, 74, 78, 82, 86, 91, 95, 96, 100, 104, 108, 112, 116, 121, 125, 126]

/-- DESIGN output NAMES, positionally aligned with `comparatorNL_outs`:
`comparatorNL_outs[k]` is the net carrying the port named at position k.
Each name is VALIDATED against the module's declared outputs (C-V3),
never derived from declaration order. One entry per EMITTED BIT. -/
def comparatorNL_out_names : List String := ["lo[0]", "lo[1]", "lo[2]", "lo[3]", "lo[4]", "lo[5]", "lo[6]", "lo[7]", "hi[0]", "hi[1]", "hi[2]", "hi[3]", "hi[4]", "hi[5]", "hi[6]", "hi[7]"]

/-- Declared outputs the caller did NOT request, sorted. PRESENT EVEN
WHEN EMPTY: an absent line means an old-format datum, an empty line is a
measured zero. A sub-cone import is legitimate — this DECLARES the scope
rather than refusing it, so a reader can see what the datum leaves out. -/
def comparatorNL_outs_omitted : List String := []

/-- DESIGN input NAMES, positionally aligned with the primary input
indices: input i is the port named at position i, for every i < this
list's length. Lets a proof cite a RECORDED name rather than trusting the
caller's --inputs order. ⚠️ CROSS-CHECK AVAILABILITY IS CLASS-DEPENDENT:
`_ndesign_in` is emitted ONLY for datums carrying state, so a stateful
datum can check this list's length against it and a combinational one
cannot. That asymmetry is the very defect this file's ndesign_out comment
forbids — an anchor that is a property of the datum's CLASS — and it is
reported to the helm rather than fixed here, because the ruling asked for
NAME TABLES and changing another field's emission is scope I was not given. -/
def comparatorNL_in_names : List String := ["a[0]", "a[1]", "a[2]", "a[3]", "a[4]", "a[5]", "a[6]", "a[7]", "b[0]", "b[1]", "b[2]", "b[3]", "b[4]", "b[5]", "b[6]", "b[7]"]


/-- Number of DESIGN outputs. `comparatorNL_outs` entries from here on are
next-state bits then cut roots, paired by position with the state inputs;
on a datum with neither, this is simply the length of `comparatorNL_outs`. -/
def comparatorNL_ndesign_out : Nat := 16

end SaltWorks.Silicon.Imported