-- GENERATED by SaltWorks/Silicon/Importer/import_netlist.py
-- source: ce_c_nl.v
-- DO NOT EDIT. The generator is UNTRUSTED; this datum is checked
-- per-instance by the importer's round-trip census, and its cell
-- expansions are proved against Liberty in SaltWorks.Silicon.Cells.Sky130.
import SaltWorks.Silicon.Equiv.BitSliced

namespace SaltWorks.Silicon.Imported

/-- ceCNL: 41 gates, 7 primary inputs. -/
def ceCNL : SaltWorks.Silicon.Netlist := [
  .inp 0,
  .inp 1,
  .inp 2,
  .inp 3,
  .inp 4,
  .inp 5,
  .inp 6,
  .not 0,
  .and 3 7,
  .and 8 4,
  .not 8,
  .and 5 7,
  .not 11,
  .xor 1 2,
  .and 12 13,
  .not 1,
  .and 15 2,
  .and 14 16,
  .and 6 7,
  .and 11 18,
  .and 19 13,
  .not 2,
  .and 1 21,
  .and 20 22,
  .or 17 23,
  .and 10 24,
  .or 9 25,
  .not 26,
  .and 27 1,
  .and 26 2,
  .or 28 29,
  .and 27 2,
  .and 26 1,
  .or 31 32,
  .or 14 20,
  .or 8 34,
  .not 11,
  .and 1 2,
  .and 12 37,
  .and 11 18,
  .or 38 39
]

/-- Output net indices, in declaration order. -/
def ceCNL_outs : List Nat := [30, 33, 35, 26, 36, 40]

end SaltWorks.Silicon.Imported