-- GENERATED by SaltWorks/Silicon/Importer/import_netlist.py
-- source: ce_elem_nl.v
-- DO NOT EDIT. The generator is UNTRUSTED; this datum is checked
-- per-instance by the importer's round-trip census, and its cell
-- expansions are proved against Liberty in SaltWorks.Silicon.Cells.Sky130.
import SaltWorks.Silicon.Equiv.BitSliced

namespace SaltWorks.Silicon.Imported

/-- ceNL: 50 gates, 7 primary inputs. -/
def ceNL : SaltWorks.Silicon.Netlist := [
  .inp 0,
  .inp 1,
  .inp 2,
  .inp 3,
  .inp 4,
  .inp 5,
  .inp 6,
  .not 0,
  .and 7 5,
  .not 8,
  .not 9,
  .and 6 10,
  .not 4,
  .and 12 3,
  .not 13,
  .and 1 14,
  .not 2,
  .or 15 16,
  .not 17,
  .and 18 9,
  .or 11 19,
  .not 20,
  .not 21,
  .and 4 22,
  .and 3 21,
  .or 23 24,
  .not 21,
  .and 3 26,
  .and 4 21,
  .or 27 28,
  .not 21,
  .and 2 30,
  .and 1 21,
  .or 31 32,
  .not 21,
  .and 1 34,
  .and 2 21,
  .or 35 36,
  .and 7 5,
  .or 38 18,
  .not 3,
  .and 40 4,
  .not 41,
  .and 2 42,
  .or 1 2,
  .not 44,
  .or 43 45,
  .not 46,
  .or 39 47,
  .not 21
]

/-- Output net indices, in the CALLER'S `--outputs` order (then state,
then cuts). NOT declaration order — this importer discards that. -/
def ceNL_outs : List Nat := [25, 29, 33, 37, 48, 49]

/-- DESIGN output NAMES, positionally aligned with `ceNL_outs`:
`ceNL_outs[k]` is the net carrying the port named at position k.
Each name is VALIDATED against the module's declared outputs (C-V3),
never derived from declaration order. One entry per EMITTED BIT. -/
def ceNL_out_names : List String := ["out0", "out1", "oact0", "oact1"]

/-- Declared outputs the caller did NOT request, sorted. PRESENT EVEN
WHEN EMPTY: an absent line means an old-format datum, an empty line is a
measured zero. A sub-cone import is legitimate — this DECLARES the scope
rather than refusing it, so a reader can see what the datum leaves out. -/
def ceNL_outs_omitted : List String := []


/-- Number of DESIGN outputs. `ceNL_outs` entries from here on are
next-state bits then cut roots, paired by position with the state inputs;
on a datum with neither, this is simply the length of `ceNL_outs`. -/
def ceNL_ndesign_out : Nat := 4

/-! ## The flop treatment — 2 flops cut, Q as leaf, D as root

This netlist is the COMBINATIONAL part of a sequential design. Every flop
was cut: its `Q` became a primary input (current state) and its `D` an
output (next state). The two vectors are PAIRED BY POSITION —
state bit `i` is input `5 + i` and output `4 + i`,
and both belong to the same flop, listed below in `Q`-net order.

Soundness: all 2 flops were checked to latch on one common event —
clock root `clk`, inversion parity 0, reached
through 1 distinct CLK net(s) of the synthesised clock tree.

* `  0`  Q `decided`  ←— `dec_n`   (_22_, dfxtp_1)
* `  1`  Q `swap`  ←— `sw`   (_23_, dfxtp_1)
-/

/-- Number of DESIGN primary inputs; inputs from here on are state bits. -/
def ceNL_ndesign_in : Nat := 5

/-- Number of flops cut by the treatment. -/
def ceNL_nstate : Nat := 2

end SaltWorks.Silicon.Imported