/-
Copyright (c) 2026 Jason Hickey. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jason Hickey, Claude
-/
-- GENERATED by SaltWorks/Silicon/Importer/import_netlist.py
-- source: bitserial_switch_nl.v
-- DO NOT EDIT. The generator is UNTRUSTED; this datum is checked
-- per-instance by the importer's round-trip census, and its cell
-- expansions are proved against Liberty in SaltWorks.Silicon.Cells.Sky130.
import SaltWorks.Silicon.Equiv.BitSliced

namespace SaltWorks.Silicon.Imported

/-- switchNL: 53 gates, 9 primary inputs. -/
def switchNL : SaltWorks.Silicon.Netlist := [
  .inp 0,
  .inp 1,
  .inp 2,
  .inp 3,
  .inp 4,
  .inp 5,
  .inp 6,
  .inp 7,
  .inp 8,
  .and 3 5,
  .not 9,
  .or 7 10,
  .and 4 6,
  .not 12,
  .or 13 8,
  .and 11 14,
  .not 15,
  .and 7 3,
  .and 17 5,
  .not 18,
  .and 8 4,
  .and 20 6,
  .not 21,
  .and 19 22,
  .not 23,
  .not 1,
  .and 5 25,
  .and 3 1,
  .or 26 27,
  .not 28,
  .not 29,
  .and 0 30,
  .not 1,
  .and 6 32,
  .and 4 1,
  .or 33 34,
  .not 35,
  .not 36,
  .and 0 37,
  .not 2,
  .and 7 39,
  .and 3 2,
  .or 40 41,
  .not 42,
  .not 43,
  .and 0 44,
  .not 2,
  .and 8 46,
  .and 4 2,
  .or 47 48,
  .not 49,
  .not 50,
  .and 0 51
]

/-- Output net indices, in the CALLER'S `--outputs` order (then state,
then cuts). NOT declaration order — this importer discards that. -/
def switchNL_outs : List Nat := [16, 24, 31, 38, 45, 52]

/-- DESIGN output NAMES, positionally aligned with `switchNL_outs`:
`switchNL_outs[k]` is the net carrying the port named at position k.
Each name is VALIDATED against the module's declared outputs (C-V3),
never derived from declaration order. One entry per EMITTED BIT. -/
def switchNL_out_names : List String := ["out0", "out1", "_00_", "_01_", "_02_", "_03_"]

/-- Declared outputs the caller did NOT request, sorted. PRESENT EVEN
WHEN EMPTY: an absent line means an old-format datum, an empty line is a
measured zero. A sub-cone import is legitimate — this DECLARES the scope
rather than refusing it, so a reader can see what the datum leaves out. -/
def switchNL_outs_omitted : List String := []

/-- DESIGN input NAMES, positionally aligned with the primary input
indices: input i is the port named at position i, for every i < this
list's length. Lets a proof cite a RECORDED name rather than trusting the
caller's --inputs order. ⚠️ CROSS-CHECK AVAILABILITY IS CLASS-DEPENDENT:
`_ndesign_in` is emitted ONLY for datums carrying state, so a stateful
datum can check this list's length against it and a combinational one
cannot. That asymmetry is the very defect this file's ndesign_out comment
forbids — an anchor that is a property of the datum's CLASS — and it is
reported to the helm rather than fixed here, because the ruling asked for
NAME TABLES and changing another field's emission is scope I was not given. -/
def switchNL_in_names : List String := ["rst_n", "act_stb", "sel_stb", "in0", "in1", "act0", "act1", "sel0", "sel1"]


/-- Number of DESIGN outputs. `switchNL_outs` entries from here on are
next-state bits then cut roots, paired by position with the state inputs;
on a datum with neither, this is simply the length of `switchNL_outs`. -/
def switchNL_ndesign_out : Nat := 6

end SaltWorks.Silicon.Imported