#!/bin/bash
# REIMPORT — regenerate every committed Lean netlist datum and byte-compare.
#
# ## Why this file exists
#
# Each `Imported/*.lean` datum carries the line "GENERATED by import_netlist.py"
# — and until 2026-08-06 the COMMAND that generated it was recorded nowhere. The
# input net order is not derivable from the netlist (it is the caller's choice,
# and D3.5's proofs depend on it bit-for-bit), so "regenerated" was not a thing
# anyone could actually do. The orders below were recovered by reading the bit
# assignments back out of `SwitchRefinement.lean` and re-deriving them until the
# output matched byte-for-byte.
#
# That makes this script two things at once:
#   * the PROVENANCE record — the missing half of "GENERATED by".
#   * a REGRESSION TEST — any importer change that perturbs a committed datum
#     fails here, which is how the flop treatment was shown not to disturb the
#     two combinational imports that predate it.
#
# Usage:  ./reimport.sh          check committed data are reproducible (default)
#         ./reimport.sh --write  regenerate in place (after an INTENDED change)
set -u
# Resolve SELF to an ABSOLUTE path BEFORE the cd — the footer's coverage check
# greps this script for its own `run` lines, and a relative $0 stops resolving
# the moment we leave the invoking directory. A coverage check that cannot read
# itself reports "nothing uncovered" unconditionally, which is the exact shape
# of a check that has never been shown to fail.
SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
cd "$(dirname "$0")/../../.." || exit 2
IMP=SaltWorks/Silicon/Importer/import_netlist.py
OUT=SaltWorks/Silicon/Imported
MODE=${1:-check}
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
fail=0; n=0

seq8() { python3 -c "print(','.join(f'$1[{i}]' for i in range(8)))"; }

run() {  # run <name> <lean-basename> <netlist> <top> <inputs> <outputs>
  local name=$1 base=$2 nl=$3 top=$4 ins=$5 outs=$6
  n=$((n+1))
  python3 "$IMP" "$nl" --top "$top" --out "$TMP/$base" --name "$name" \
      --inputs "$ins" --outputs "$outs" >"$TMP/$base.log" 2>&1
  if [ $? -ne 0 ]; then
    echo "  ✗ $base — importer FAILED"; sed 's/^/      /' "$TMP/$base.log"; fail=1; return
  fi
  if [ "$MODE" = "--write" ]; then
    cp "$TMP/$base" "$OUT/$base"; echo "  ↻ $base written"
  elif cmp -s "$TMP/$base" "$OUT/$base"; then
    echo "  ✅ $base reproduces byte-for-byte"
  else
    echo "  ✗ $base DIFFERS from committed"; fail=1
  fi
}

echo "reimport: regenerating committed netlist data"

# --- comparator: 8-bit min/max, PURELY COMBINATIONAL (0 flops). ------------
run comparatorNL Comparator.lean SaltWorks/Silicon/Flow/comparator_nl.v comparator \
    "$(seq8 a),$(seq8 b)" "$(seq8 lo),$(seq8 hi)"

# --- bitserial switch: 4 flops, cut BY HAND before the treatment existed. --
# Input order is load-bearing: SwitchRefinement.lean's `switchSpec` indexes
# 0=rst_n 1=act_stb 2=sel_stb 3=in0 4=in1 5=act0 6=act1 7=sel0 8=sel1, and the
# last four are flop Q nets. Outputs are out0,out1 then the four flop D nets, so
# the caller's manual cut already paired state with next-state by position —
# which is exactly what the flop treatment now does automatically.
run switchNL Switch.lean SaltWorks/Silicon/Flow/bitserial_switch_nl.v bitserial_switch \
    "rst_n,act_stb,sel_stb,in0,in1,act0,act1,sel0,sel1" \
    "out0,out1,_00_,_01_,_02_,_03_"

# --- compare-exchange element: 2 flops, auto-cut by the flop treatment. -----
# ADDED 8/12. These two were committed, importer-GENERATED, and their sources
# are in this repo — yet they were neither run here nor excluded with a reason,
# so the regression net covered 2 of the 4 eligible data while reporting only
# "2 datum(s), ALL REPRODUCE". The count was true; the DENOMINATOR was absent,
# which is why the footer below now states coverage against the committed
# population rather than against itself.
#
# Their port orders were unrecorded (the same gap this file exists to close for
# the other two). Recovered the same way: propose the module's own declaration
# order and let the byte-comparison adjudicate — a guess that reproduces the
# committed bytes IS the proof the order was right. Both matched first attempt.
run ceNL CompareExchange.lean SaltWorks/Silicon/Flow/ce_elem_nl.v ce_elem \
    "rst,act0,act1,in0,in1" "out0,out1,oact0,oact1"

# ce_c is the COMBINATIONAL variant — the same element with its two flops cut
# into ports by hand (7 in / 6 out), which is why its order is simply i0..i6.
run ceCNL CompareExchangeC.lean SaltWorks/Silicon/Flow/ce_c_nl.v ce_c \
    "i0,i1,i2,i3,i4,i5,i6" "o0,o1,o2,o3,o4,o5"

# NOTE: RefComparator.lean is NOT listed — it is hand-written on purpose, a
# structurally different reference design so that agreeing with the imported
# netlist is a real check rather than a tautology. Adding it here would be a
# category error. (It is also the ONE datum in Imported/ whose header does not
# say "GENERATED by .../import_netlist.py"; the other six do.)
#
# NOTE: Fabric.lean and FabricCut.lean are NOT listed either, and that is a
# provenance decision, not an oversight. Their source is
# `tt_submission/tt_um_saltworks_banyan.v` — a CI BUILD ARTIFACT from run
# 31140274735, not a file in this repository. A check that silently regenerated
# them from whatever copy happened to be on disk would assert reproducibility it
# cannot establish; three copies were present tonight with three different
# checksums. See Flow-docs/flop-treatment-0806.md for the pinned artifact
# identity and both exact commands (they differ only by `--cut`).

# A COUNT IS NOT A SCOPE. "$n datum(s), ALL REPRODUCE" is true no matter how few
# are listed above, so the footer states the DENOMINATOR it was measured against
# and names every committed datum this run did NOT reproduce. A datum that is
# neither run nor named here is the failure this block exists to make impossible.
committed=$(ls "$OUT"/*.lean 2>/dev/null | wc -l | tr -d ' ')
excluded="RefComparator.lean(hand-written reference) Fabric.lean(CI-artifact source) FabricCut.lean(CI-artifact source)"
uncovered=""
for f in "$OUT"/*.lean; do
  b=$(basename "$f")
  grep -q "^run .* $b " "$SELF" && continue
  case " $excluded " in *" $b("*) continue;; esac
  uncovered="$uncovered $b"
done
# ⛔ THE DEBT IS PRINTED, NOT MERELY HELD. This used to say "3 excluded with
# cause" and keep the cause in the source, then print a bare "ALL REPRODUCE" — a
# TOTALITY CLAIM with its own exclusions invisible to every reader of the output.
# The helm's 18:05:38 ruling requires the opposite in words: every totality-style
# predicate reads "on every REGENERABLE datum" WITH THE DEBT LIST PRINTED BESIDE
# IT. And silicon's own 19:13 criterion says why it matters generally:
# ⇒ A CAVEAT THAT LIVES ONLY IN THE SOURCE IS NOT CARRIED BY THE OUTPUT, AND THE
#   OUTPUT IS WHAT TRAVELS. This file's exclusions were correct, reasoned and
#   dated at :91-:111 — and none of that ever reached a reader of a green run.
# ⚠️ SPLIT ON ')' AND NOT ON WHITESPACE. My first version of this block used
# `for _e in $excluded` and `wc -w` — but each entry is `Name.lean(cause with
# spaces)`, so word-splitting cut them mid-entry and reported SIX exclusions
# where there are THREE. I had replaced a CORRECT hardcoded 3 with a DERIVED
# count that was wrong: deriving a figure is not automatically better than a
# constant that happens to be right, and a derivation is only an improvement if
# its delimiter matches the data.
_nexcl=$(printf '%s' "$excluded" | tr ')' '\n' | grep -c '[A-Za-z]')
echo "reimport: $n of $committed committed datum(s) reproduced, $_nexcl excluded — REGISTERED DEBT, named:"
printf '%s' "$excluded" | tr ')' '\n' | sed '/[A-Za-z]/!d; s/^ *//; s/$/)/; s/^/    · /' 
[ -n "$uncovered" ] && { echo "  ⛔ UNACCOUNTED (neither run nor excluded):$uncovered"; fail=1; }
echo "reimport: $( [ $fail -eq 0 ] && echo "ALL REGENERABLE DATUMS REPRODUCE (not all committed — see the debt above)" || echo "FAILURES ABOVE" )"
exit $fail
