#!/bin/sh
# run_step0.sh — STEP 0 (helm route 2026-10-04 @75,145,900): measure the FABRICATED core32 against
# RV32I. Reproduces every figure in docs/silicon-step0-core32-conformance-1004.md from named objects.
#   DUT (RTL)  tt-neural-dataflow-fabric @ 01e19f7 (the shuttle slot's commit_id), via `git show`
#   DUT (GL)   tt_submission artifact of gds run 34058427540, the signed-off netlist
#   SUITE      riscv-tests @ RVTESTS_SHA, rv32ui, self-checking; env/ is this directory's own
# env: TTDIR (tape-out clone) · GLNL (netlist; fetched if absent) · RVTESTS (riscv-tests clone) · OUT
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
TTDIR=${TTDIR:-$HOME/projects/claude/seats/silicon/tt-neural-dataflow-fabric}
OUT=${OUT:?set OUT to a scratch directory}; mkdir -p "$OUT"
RVTESTS_SHA=bcffa2b; REF=01e19f7; RUN=34058427540
GL_SHA256=38a4686f264fe8143f2a1e6939bd2058c14c28abd5d77a05f9f85fd3aede209c
CORE_BLOB=e8a918015484e542d3d0cee2ded4722add55910a
PDKV=8afc8346a57fe1ab7934ba5a6056ea8b43078e71
SRCS="tt_um_saltworks_ndf_c32.v banyan_fabric.v bitserial_switch.v busadapt8.v core32.v mac_cell_signed_shell.v plane32bus.v ser_organ.v"

# ---- objects, each verified, never assumed ---------------------------------------------------
mkdir -p "$OUT/rtl"
for f in $SRCS; do git -C "$TTDIR" show "$REF:src/$f" > "$OUT/rtl/$f"; done
git -C "$TTDIR" show "$REF:test/sky130_models.v" > "$OUT/rtl/sky130_models.v"
[ "$(git hash-object "$OUT/rtl/core32.v")" = "$CORE_BLOB" ] || { echo "⛔ core32.v at $REF is not blob $CORE_BLOB"; exit 2; }
GLNL=${GLNL:-$OUT/gl/tt_submission/tt_um_saltworks_ndf_c32.v}
[ -f "$GLNL" ] || gh run download "$RUN" -R jyh/tt-neural-dataflow-fabric -n tt_submission -D "$OUT/gl"
[ "$(shasum -a 256 "$GLNL" | cut -d' ' -f1)" = "$GL_SHA256" ] || { echo "⛔ netlist sha256 mismatch"; exit 2; }
PDK=$(find "$HOME/.volare" -type d -path "*$PDKV/sky130A/libs.ref/sky130_fd_sc_hd/verilog" 2>/dev/null | head -1)
[ -n "$PDK" ] || { echo "⛔ sky130A $PDKV cell models not found (the run's own pdk.json version)"; exit 2; }
RVTESTS=${RVTESTS:-$OUT/riscv-tests}
[ -d "$RVTESTS/isa" ] || git clone -q https://github.com/riscv-software-src/riscv-tests.git "$RVTESTS"
git -C "$RVTESTS" cat-file -e "$RVTESTS_SHA^{commit}" 2>/dev/null || { echo "⛔ riscv-tests lacks $RVTESTS_SHA"; exit 2; }
git -C "$RVTESTS" -c advice.detachedHead=false checkout -q "$RVTESTS_SHA"

# ---- the benches: fabricated RTL · GL · four CONTROL variants (RTL, patched) -------------------
python3 - "$HERE" <<'PY'
import sys
v=lambda n:'{'+', '.join('user_project.\\core.u_core.%s[%d] '%(n,i) for i in range(31,-1,-1))+'}'
open(sys.argv[1]+'/glnames.vh','w').write('// GENERATED by run_step0.sh — the keep nets survive by name in the signed-off netlist\n`define PC_Q  %s\n`define ALU_Y %s\n'%(v('pc_q'),v('alu_y')))
PY
iverilog -g2012 -o "$OUT/rtl.vvp" -I "$HERE" "$HERE/tb_host.v" "$OUT"/rtl/*.v
iverilog -g2012 -DGL_TEST -DFUNCTIONAL -DUSE_POWER_PINS -DSIM -DUNIT_DELAY=#1 -o "$OUT/gl.vvp" -I "$HERE" \
  "$HERE/tb_host.v" "$PDK/primitives.v" "$PDK/sky130_fd_sc_hd.v" "$GLNL"
for c in imm sra shift all; do
  mkdir -p "$OUT/ctl_$c"; cp "$OUT"/rtl/*.v "$OUT/ctl_$c/"
  python3 "$HERE/patch_variants.py" "$OUT/ctl_$c" "$c" >/dev/null
  iverilog -g2012 -o "$OUT/ctl_$c.vvp" -I "$HERE" "$HERE/tb_host.v" "$OUT/ctl_$c"/*.v
done
BENCHES="rtl gl ctl_imm ctl_sra ctl_shift ctl_all"

run() { vvp -n "$OUT/$1.vvp" +hex="$2.hex" +tohost="$(cat "$2.tohost")" $3 | grep -E '^(ST|SUMMARY) '; }

# ---- (A) and the LW probe: pins-only, image < 256 B -------------------------------------------
for p in sra_probe lw_probe; do
  "$HERE/build.sh" "$HERE/progs/$p.S" "$OUT/b" 2>/dev/null
  for b in $BENCHES; do run "$b" "$OUT/b/$p" "" > "$OUT/$p.$b.txt"; done
done
python3 - "$OUT" <<'PY'
import sys,re
O=sys.argv[1]; M=0xffffffff
def sra(x,s): x&=M; return ((x-(1<<32) if x>>31 else x)>>s)&M
def srl(x,s): return (x&M)>>s
N=-16&M
# expected from the RV32I definition, one row per stored result in progs/sra_probe.S, in order
A=[("SRAI -16,2",sra(N,2)),("SRA  -16,2",sra(N,2)),("SRLI -16,2 (ctl)",srl(N,2)),("SRL  -16,2 (ctl)",srl(N,2)),
   ("SRAI 15,1 (ctl)",sra(15,1)),("SRAI -16,31",sra(N,31)),("SRA  -16,31",sra(N,31)),("SRAI -16,0 (ctl)",sra(N,0)),
   ("SRAI 0x80000000,4",sra(0x80000000,4)),("SUB 0-2 (ctl)",(0-2)&M),("ADDI -1024 (ctl)",(-1024)&M)]
L=[("LW dat[0]",0x11111111),("LW dat[1]",0x22222222),("LW dat[2]",0x33333333),("LW dat[2] again",0x33333333),
   ("LW dat[0]",0x11111111),("ADDI 77 (ctl)",77)]
B="rtl gl ctl_imm ctl_sra ctl_shift ctl_all".split()
for p,E in (("sra_probe",A),("lw_probe",L)):
    got={b:[int(l.split()[2],16) for l in open(f"{O}/{p}.{b}.txt") if l.startswith("ST ")][:len(E)] for b in B}
    summ={b:[l for l in open(f"{O}/{p}.{b}.txt") if l.startswith("SUMMARY")][0].split() for b in B}
    print(f"\n### {p}  (pins-only; every value is a STORE reassembled from uo_out)")
    print("| row | RV32I expects | "+" | ".join(B)+" |"); print("|---|---|"+"---|"*len(B))
    for i,(n,e) in enumerate(E):
        print(f"| {n} | `{e:08x}` | "+" | ".join(("`%08x`"%got[b][i])+(" ✅" if got[b][i]==e else " ❌") for b in B)+" |")
    print("| run | | "+" | ".join(" ".join(x for x in summ[b] if x.startswith(("halted","phase_mismatch")))for b in B)+" |")
PY

# ---- (B) rv32ui, self-checking, full-address host (+addrnet) ---------------------------------
EXCL="lb lbu lh lhu sb sh ld_st st_ld ma_data fence_i"
echo; echo "### rv32ui @ riscv-tests $RVTESTS_SHA  (PASS = the test's own pass store reached tohost)"
echo "| test | fabricated RTL | signed-off GL | ctl_shift | ctl_all |"; echo "|---|---|---|---|---|"
for s in "$RVTESTS"/isa/rv32ui/*.S; do
  t=$(basename "$s" .S)
  case " $EXCL " in *" $t "*) echo "| $t | EXCLUDED | EXCLUDED | | |"; continue;; esac
  RVTESTS="$RVTESTS" "$HERE/build.sh" "$s" "$OUT/rv" 2>/dev/null
  row="| $t |"
  for b in rtl gl ctl_shift ctl_all; do
    r=$(run "$b" "$OUT/rv/$t" "+addrnet +cycles=20000" | grep '^SUMMARY')
    hv=$(echo "$r" | sed -n 's/.*haltval=\([0-9a-f]*\).*/\1/p'); h=$(echo "$r" | sed -n 's/.*halted=\([01]\).*/\1/p')
    cy=$(echo "$r" | sed -n 's/.* cycles=\([0-9]*\).*/\1/p'); pm=$(echo "$r" | sed -n 's/.*phase_mismatch=\([0-9]*\).*/\1/p')
    [ "$pm" = 0 ] || { row="$row VOID(phase) |"; continue; }
    if [ "$h" = 1 ] && [ "$hv" = 00000001 ]; then row="$row PASS ($cy cyc) |"
    elif [ "$h" = 1 ]; then row="$row **FAIL test $(( 0x$hv >> 1 ))** |"
    else row="$row TIMEOUT |"; fi
  done
  echo "$row"
done

# ---- (D) the erratum's SOFTWARE WORKAROUNDS (desk AAL, 2026-10-05), full-address host --------
# fabricated RTL · signed-off GL · ctl_all (a corrected core: the sequences must hold there too)
"$HERE/build.sh" "$HERE/progs/workaround_probe.S" "$OUT/wa" 2>/dev/null
for b in rtl gl ctl_all; do run "$b" "$OUT/wa/workaround_probe" "+addrnet +cycles=40000" > "$OUT/workaround_probe.$b.txt"; done
python3 - "$OUT" <<'PY'
import sys
O=sys.argv[1]; M=0xffffffff
def sra(x,s): x&=M; return ((x-(1<<32) if x>>31 else x)>>s)&M
N=-16&M
# one row per stored result in progs/workaround_probe.S, in order; the in-pair store (sw x0) is dropped by position (below)
E=[("LW×2 dat[0], first load after reset",0x11111111),("LW×2 dat[1]",0x22222222),("LW×2 dat[2], a store between",0x33333333),
   ("LW×2 dat[0] again",0x11111111),("SRA_W -16,2",sra(N,2)),("SRA_W -16,31",sra(N,31)),("SRA_W -16,0",sra(N,0)),
   ("SRA_W 0x80000000,4",sra(0x80000000,4)),("SRA_W 15,1",sra(15,1)),("SRA_W 0x7fffffff,31",sra(0x7fffffff,31)),
   ("SRAI_W -16,2",sra(N,2)),("SRAI_W -16,31",sra(N,31)),("SRAI_W 0x80000000,4",sra(0x80000000,4)),
   ("SRAI_W 0x12345678,8",sra(0x12345678,8)),("SRAI_W 0x87654321,8",sra(0x87654321,8))]
B="rtl gl ctl_all".split()
def st(b):
    rows=[l.split() for l in open(f"{O}/workaround_probe.{b}.txt") if l.startswith("ST ")]
    out=[int(r[2],16) for r in rows]
    # the program's stores land in order; the 3rd store is the in-pair `sw x0` (r2's mid-pair store) and is dropped
    return out[:2]+out[3:3+len(E)-2]
got={b:st(b) for b in B}
summ={b:[l for l in open(f"{O}/workaround_probe.{b}.txt") if l.startswith("SUMMARY")][0].split() for b in B}
print("\n### workaround_probe  (+addrnet for the address; every value is a STORE reassembled from uo_out)")
print("| row | RV32I expects | "+" | ".join(B)+" |"); print("|---|---|"+"---|"*len(B))
for i,(n,e) in enumerate(E):
    print(f"| {n} | `{e:08x}` | "+" | ".join(("`%08x`"%got[b][i])+(" ✅" if got[b][i]==e else " ❌") for b in B)+" |")
print("| run | | "+" | ".join(" ".join(x for x in summ[b] if x.startswith(("halted","phase_mismatch")))for b in B)+" |")
PY
