#!/usr/bin/env python3
"""fig4_render.py — Figure 4, rendered from the SHUTTLE'S OWN PLACEMENT.

Usage:
    fig4_render.py <placement.def> <classes.tsv> <out-prefix>
        -> <out-prefix>.svg  and  <out-prefix>.png

WHY THIS EXISTS
    The 2026-08-14 Figure-4 PNG has NO GENERATOR ANYWHERE — swept across the
    saltworks tools, the method doc and the paper repo. This is the same
    recover-as-code the join got: the picture becomes a script whose inputs are
    named by sha, so the next hand regenerates it instead of quoting it.
    A RESULT WITHOUT ITS PRODUCER IS NOT REPRODUCIBLE, IT IS ONLY QUOTABLE.

DEPENDENCIES: NONE. Python 3 standard library only.
    Measured on this machine 2026-08-23: matplotlib, numpy, gdstk, gdspy,
    klayout and magic are ALL ABSENT. DEF is text and SVG is text, so the vector
    output needs no library; the PNG is written by a ~40-line zlib+struct
    encoder in this file.
    ⛔ `qlmanage` IS present and is DELIBERATELY NOT USED: it is macOS-only, so a
    figure that depends on it cannot be regenerated by a peer on Linux. That
    trades a dependency I can read for one I cannot.

INPUT SHAS — recorded here because recording the input hash is precisely what
made the lost 0812 join recoverable ten days later:
    _c32 gate netlist   8f413b2705ce4c815034c861f888fb4a5b8adee391afd3f817ebddb4aca4bf54
    _ndf gate netlist   3a8577e019d26e0921892c44353b0db74a6dcf76dd43f57879fe8a17ed15a541
    placement DEF       from GDS_logs of TT run 32284710003 (commit 7d2b275),
                        runs/wokwi/53-odb-cellfrequencytables/*.def
                        ⚠️ There is NO DEF in the `tt_submission` artifact; the
                        placement exists only in `GDS_logs`.
    re-fetch:  gh run download 32284710003 -R jyh/tt-neural-dataflow-fabric \\
                   -n GDS_logs -D gdslogs

WHAT THIS IS NOT
    Not pixel-identical to the Aug-14 render, by explicit allowance — that
    figure's generator is gone and forging its exact output would be a worse
    claim than an honest reproducible one.
"""
import sys, re, zlib, struct, hashlib
from collections import defaultdict

# ── palette: function classes ────────────────────────────────────────────────
# CLASS NAME RATIFIED AT COUNCIL 2026-08-23 — "hold & fanout buffering".
# Ordered darkest-to-lightest by narrative weight, not by count.
COLORS = {
    "mac_island_cell0":       (0x1f, 0x77, 0xb4),
    "mac_island_cell1":       (0x2e, 0x8b, 0xc8),
    "mac_island_cell2":       (0x4f, 0xa3, 0xd9),
    "serializer_ser0":        (0xff, 0x7f, 0x0e),
    "serializer_ser1":        (0xff, 0x95, 0x3a),
    "serializer_ser2":        (0xff, 0xab, 0x66),
    "core_combinational":     (0x9e, 0x9e, 0x9e),
    "core_mux":               (0x6d, 0x6d, 0x6d),
    "core_sequential":        (0x2c, 0xa0, 0x2c),
    "clock_tree":             (0xd6, 0x27, 0x28),
    "hold_fanout_buffering":  (0x94, 0x67, 0xbd),
    "tie":                    (0x8c, 0x56, 0x4b),
}
LEGEND = [
    ("mac_island_cell0", "MAC island (kernel-emitted)"),
    ("serializer_ser0",  "serializer (kernel-emitted)"),
    ("core_combinational", "core combinational"),
    ("core_mux",         "core mux"),
    ("core_sequential",  "core sequential"),
    ("clock_tree",       "clock tree"),
    ("hold_fanout_buffering", "hold & fanout buffering"),
    ("tie",              "tie"),
]

def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()

# ── DEF ──────────────────────────────────────────────────────────────────────
COMP = re.compile(
    r"^\s*-\s+(\S+)\s+(\S+)\s+.*?\+\s+(?:PLACED|FIXED)\s+\(\s*(-?\d+)\s+(-?\d+)\s*\)"
)

def read_def(path):
    """Return (units, diearea, components). Field-aware: a DEF row may carry
    `+ SOURCE TIMING`, `+ FIXED`, etc. between the cell type and the placement,
    so the placement is matched by KEYWORD, never by column position — a
    positional parse silently mis-reads exactly the timing-repair cells this
    figure is about."""
    units, die, comps = 1000, None, []
    in_comp = False
    with open(path, "r", errors="replace") as f:
        for line in f:
            if die is None and line.startswith("DIEAREA"):
                n = [int(v) for v in re.findall(r"-?\d+", line)]
                if len(n) >= 4:
                    die = (n[0], n[1], n[2], n[3])
                continue
            if line.startswith("UNITS DISTANCE MICRONS"):
                units = int(re.findall(r"\d+", line)[0]); continue
            if line.startswith("COMPONENTS"):
                in_comp = True; continue
            if line.startswith("END COMPONENTS"):
                in_comp = False; continue
            if in_comp:
                m = COMP.match(line)
                if m:
                    comps.append((m.group(1), m.group(2), int(m.group(3)), int(m.group(4))))
    return units, die, comps

def derive_widths(comps):
    """Cell widths from the DEF's OWN ROW PACKING.

    ⛔ Why not a LEF: 26 of the placed logic types (clkbuf_*, dlygate4sd3_1,
    clkdlybuf4s25_1, buf_*, _4/_8 drive variants) are inserted AFTER synthesis,
    so yosys reports no area for them — and those are exactly the hold & fanout
    cells this figure exists to show. No sky130 cell LEF is present on this
    machine either.
    ✅ The rows are fill-packed, so within a row the x-delta to the next
    instance IS the width. Physical cells (fill/decap/tap) are kept HERE as
    neighbours precisely because they are what makes the packing complete, even
    though they are never drawn.
    Returns {celltype: width_in_dbu} using the modal width per type."""
    rows = defaultdict(list)
    for name, ctype, x, y in comps:
        rows[y].append((x, ctype))
    tally = defaultdict(lambda: defaultdict(int))
    for y, cells in rows.items():
        cells.sort()
        for i in range(len(cells) - 1):
            w = cells[i + 1][0] - cells[i][0]
            if 0 < w < 100000:
                tally[cells[i][1]][w] += 1
    return {t: max(d.items(), key=lambda kv: kv[1])[0] for t, d in tally.items()}

def read_classes(path):
    cls = {}
    with open(path) as f:
        next(f)
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) >= 4:
                cls[p[0]] = p[3]
    return cls

# ── PNG, pure stdlib ─────────────────────────────────────────────────────────
def write_png(path, w, h, px):
    raw = b"".join(b"\x00" + bytes(px[y * w * 3:(y + 1) * w * 3]) for y in range(h))
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n")
        f.write(chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)))
        f.write(chunk(b"IDAT", zlib.compress(raw, 9)))
        f.write(chunk(b"IEND", b""))

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: fig4_render.py <placement.def> <classes.tsv> <out-prefix>")
    defp, tsvp, out = sys.argv[1:4]
    units, die, comps = read_def(defp)
    if die is None:
        sys.exit("fig4_render: no DIEAREA in DEF")
    cls = read_classes(tsvp)
    widths = derive_widths(comps)

    x0, y0, x1, y1 = die
    dw, dh = x1 - x0, y1 - y0
    ROWH = 2720  # sky130_fd_sc_hd row height, 2.72 um in DBU@1000

    drawn = defaultdict(int)
    unclassed = 0
    rects = []
    for name, ctype, x, y in comps:
        c = cls.get(name)
        if c is None:
            unclassed += 1          # physical fill/decap/tap/diode: never drawn
            continue
        w = widths.get(ctype, 460)  # site width fallback, counted below
        rects.append((x, y, w, ROWH, COLORS.get(c, (0, 0, 0))))
        drawn[c] += 1

    # ── SVG ──
    SCALE = 1.0
    pad = 40
    W = int(dw / 1000 * 2.2) + pad * 2
    H = int(dh / 1000 * 2.2) + pad * 2 + 120
    sx = (W - 2 * pad) / dw
    sy = (H - 2 * pad - 120) / dh
    with open(out + ".svg", "w") as f:
        f.write(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
                f'viewBox="0 0 {W} {H}">\n<rect width="{W}" height="{H}" fill="#ffffff"/>\n')
        f.write(f'<rect x="{pad}" y="{pad}" width="{dw*sx:.1f}" height="{dh*sy:.1f}" '
                f'fill="none" stroke="#000" stroke-width="1"/>\n')
        for (x, y, w, h, col) in rects:
            X = pad + (x - x0) * sx
            Y = pad + (dh - (y - y0) - h) * sy
            f.write(f'<rect x="{X:.2f}" y="{Y:.2f}" width="{max(w*sx,0.35):.2f}" '
                    f'height="{max(h*sy,0.6):.2f}" fill="rgb{col}"/>\n')
        ly = pad + dh * sy + 28
        # Legend counts: the three MAC islands and three serializers are summed,
        # because the legend names the CLASS while the palette distinguishes the
        # instances — showing one island's count beside a label that reads
        # "MAC island" would understate it by two thirds.
        def legend_count(key):
            if key.startswith("mac_island"):
                return sum(v for k, v in drawn.items() if k.startswith("mac_island"))
            if key.startswith("serializer"):
                return sum(v for k, v in drawn.items() if k.startswith("serializer"))
            return drawn.get(key, 0)
        for i, (k, label) in enumerate(LEGEND):
            cx = pad + (i % 4) * ((W - 2 * pad) / 4)
            cy = ly + (i // 4) * 22
            f.write(f'<rect x="{cx}" y="{cy-9}" width="12" height="12" fill="rgb{COLORS[k]}"/>\n')
            f.write(f'<text x="{cx+18}" y="{cy+1}" font-family="Helvetica,Arial" '
                    f'font-size="11" fill="#000">{label} ({legend_count(k):,})</text>\n')
        f.write("</svg>\n")

    # ── PNG ──
    PW = 1600
    PH = max(1, int(PW * dh / dw))
    px = bytearray(b"\xff" * (PW * PH * 3))
    for (x, y, w, h, col) in rects:
        px0 = int((x - x0) / dw * PW); px1 = max(px0 + 1, int((x - x0 + w) / dw * PW))
        py0 = int((dh - (y - y0) - h) / dh * PH); py1 = max(py0 + 1, int((dh - (y - y0)) / dh * PH))
        for yy in range(max(0, py0), min(PH, py1)):
            base = (yy * PW + max(0, px0)) * 3
            for xx in range(max(0, px0), min(PW, px1)):
                o = (yy * PW + xx) * 3
                px[o], px[o+1], px[o+2] = col
    # DIE OUTLINE — the caption's own claim is that the placed logic is seen
    # against the TRUE DIE EDGE, so a PNG without the frame drops the very thing
    # that makes the white space meaningful (it is fill/decap, not empty die).
    def hline(y, x0p, x1p, col=(0, 0, 0)):
        if 0 <= y < PH:
            for xx in range(max(0, x0p), min(PW, x1p)):
                o = (y * PW + xx) * 3; px[o], px[o+1], px[o+2] = col
    def vline(x, y0p, y1p, col=(0, 0, 0)):
        if 0 <= x < PW:
            for yy in range(max(0, y0p), min(PH, y1p)):
                o = (yy * PW + x) * 3; px[o], px[o+1], px[o+2] = col
    hline(0, 0, PW); hline(PH - 1, 0, PW); vline(0, 0, PH); vline(PW - 1, 0, PH)
    write_png(out + ".png", PW, PH, px)

    fb = sum(1 for _, ctype, _, _ in comps if ctype not in widths)
    print(f"def            {defp}")
    print(f"def sha256     {sha256(defp)}")
    print(f"classes        {tsvp}")
    print(f"die            {dw/units:.2f} x {dh/units:.2f} um")
    print(f"components     {len(comps)}")
    print(f"drawn (logic)  {sum(drawn.values())}")
    print(f"not drawn      {unclassed}  (physical fill/decap/tap/diode)")
    print(f"width fallback {fb}  (types with no packing-derived width)")
    for k, v in sorted(drawn.items(), key=lambda kv: -kv[1]):
        print(f"  {k:<26} {v}")
    print(f"wrote          {out}.svg  {out}.png ({PW}x{PH})")

if __name__ == "__main__":
    main()
